### ISSUE TITLE
How can I customize switch case indentation?

### ISSUE THREAD

**Issue by sabyasachi** [mooz/js2-mode#111]
For example, how could I get this:

``` JavaScript
switch (a) {
    case 1:
        doSomething();
        break;
    case 2:
        doSomethingElse();
        break;
}
```

Instead of default:

``` JavaScript
switch (a) {
case 1:
    doSomething();
    break;
case 2:
    doSomethingElse();
    break;
}
```

**Comment by jdivock** [comment]
Just ran across this, thanks!

**Comment by jordonbiondo** [comment]
What happened to `js2-indent-switch-body`? It appears to have been removed and I don't see a way to customize the behavior in another way. Is there an alternative now that I can use to have a switch body be indented?

**Comment by dgutov** [comment]
Yes: `js-switch-indent-offset`.

**Comment by jordonbiondo** [comment]
Thanks!

**Comment by marc0s** [comment]
Sorry to bump this, but, any clue on how to achieve this if using `TAB`s for indentation?

**Comment by dgutov** [comment]
js2-mode itself doesn't (and cannot) care about tabs.

See http://emacs.stackexchange.com/questions/22247/tab-width-and-lang-indent-offset-difference/22248#22248.

**Comment by marc0s** [comment]
@dgutov thanks for the link.  I understand it now (and have it working by setting `js-switch-indent-offset` to the same value of my `tab-width`).  Thanks.

**Comment by computersarecool** [comment]
This sounds picky but is there a way to have it indent by two spaces? I have `js2-basic-offset 2` so it feels like a bit of a a bug that this switch case indents by four.

Reason being is that at least one or two popular style guides (the same ones that want the case indented) want it indented by two spaces...

**Comment by ibrahima** [comment]
In case you're finding this issue through Google, the setting has changed as per https://github.com/mooz/js2-mode/issues/277#issuecomment-257098326

> On Emacs 25, js2-mode uses the js-mode indentation. To have case indented within switch, and also the case contents further indented, add something like `(setq js-switch-indent-offset 4)` to your js2-mode-hook.
