### ISSUE TITLE
Support for Harmony String interpolation

### ISSUE THREAD

**Issue by nhunzaker** [mooz/js2-mode#136]
Is there any work being done to add ES6 `${"string interpolation"}` to js2?

**Comment by aifreedom** [comment]
@dgutov It seem Mozilla has fixed it https://bugzilla.mozilla.org/show_bug.cgi?id=688857. Are you going to add support in js2-mode?

**Comment by dgutov** [comment]
@aifreedom Does it work for you already?

**Comment by aifreedom** [comment]
@dgutov Yeah, it works. I was making a mistake. Thanks!
