### ISSUE TITLE
Is use of c-basic-offset in emacs file variables for setting js2 indent supported?

### ISSUE THREAD

**Issue by anaran** [mooz/js2-mode#144]
Many mozilla/gecko-dev js files use `c-basic-offset` in emacs file variables.

A few of them, like
https://github.com/mozilla/gecko-dev/blob/master/browser/base/content/safeMode.js#L1
set js2 mode specifically.

While js2-mode.el has [following code](https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L233-L236) it fails to use the indentation value provided in the emacs file variable.

Instead it uses the default js2-basic-offset 4.

My take on this is that the defcustom is evaluated first, taking the default value of c-basic-offset before that gets set to 2.

People using a value of 2 in their init files won't notice the breakage, but this is incorrect usage in the emacs file variable, right?

```
(defcustom js2-basic-offset (if (and (boundp 'c-basic-offset)
                                     (numberp c-basic-offset))
                                c-basic-offset
                              4)
```

**Comment by vendethiel** [comment]
I found this issue because I spent the last two hours or so trying to make js2-mode respect my indentation config (I also hit a (seemingly) but in emacs' .dir-locals.el stuff...).

I had to use `c-basic-offset` to configure how much js2-mode would indent. Will this be chaged? In the meantime, can this **please** be documented? (I'll gladly send a minor README.md patch)

**Comment by dgutov** [comment]
@vendethiel Why not set `js2-basic-offset` instead?

**Comment by vendethiel** [comment]
cf my edit. my emacs-foo is weak. I looked at all the "indent" stuff in the .el file, and "tab-width". no  luck.

**Comment by dgutov** [comment]
Have you seen the usage instructions you get upon pressing RET on a js2-mode in the `M-x list-packages` list?

**Comment by vendethiel** [comment]
No, I only install packages with `install-package` and read their READMEs.
