### ISSUE TITLE
Async / Await

### ISSUE THREAD

**Issue by arcanis** [mooz/js2-mode#185]
Async and await are considered for inclusion in ES7. Even if they are not yet in Spidermonky, since it seems to be mainly a matter of adding two keywords, could it be possible to support them ? Traceur is already able to transpile it.

```js
var foo = async function ( ) {
    await bar( );
};

async function foo( ) {
    await bar( );
};

class Foo {
    async function foo( ) {
        await bar( );
    }
}
```

**Comment by mooz** [comment]
Implemented `async`/`await` based on the proposal, and pushed to https://github.com/mooz/js2-mode/tree/es7-async-await branch. Since [`6to5`](https://github.com/6to5/6to5), a quite popular ES6/7 to ES5 transpiler, already supports `async`/`await` (experimentally), I think it's good if `js2-mode` also supports it.

If there is no problem, I'll merge the branch to `master`.

**Comment by dgutov** [comment]
@arcanis Do you have a link that actually describes the changes to the grammar? Are `async` and `await` supposed to be new "proper" keywords, or contextual keywords? @mooz changed the implementation for the latter, but if they turns out to be the former, it will be unnecessary complexity.

**Comment by mooz** [comment]
@dgutov @arcanis

According to ES6 draft and tc39's discussion for ES7,

- `async` won't be reserved (is a contextual keyword) (https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-18.md#413-add-async-as-futurereservedword) [tc39's discussion],
- `await` is a future reserved word only if a program is parsed as a module (?) (https://people.mozilla.org/~jorendorff/es6-draft.html#sec-future-reserved-words)[spec].

**Comment by arcanis** [comment]
@mooz Your commits work fine, except for class methods (which should work according to [Traceur](http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--async-functions%20%0A%0Aclass%20Foo%20%7B%0A%20%20%0A%20%20static%20async%20myFunc()%20%7B%0A%20%20%7D%0A%0A%20%20async%20myFunc()%20%7B%0A%20%20%7D%0A%0A%7D%0A))

**Comment by amasad** [comment]
n00b question. How do I install this from the branch?

**Comment by arcanis** [comment]
@mooz Do you think you could support the `class { async foo() { } }` syntax on your branch? I've looked, but I'm far from being fluent enough in lisp to understand what to change to be clean :(

**Comment by mooz** [comment]
@arcanis I've just added the support for async methods and object property shorthands, say:

```javascript
class A {
  async b() { ... }
}
```
and

```javascript
var B = { async c() { ... } }
```

I think we already support `async ( ) => { }`.

**Comment by arcanis** [comment]
Thanks @mooz, it works fine! I've rebased your commits on the following branch if you need to merge it in master at some point:

https://github.com/arcanis/js2-mode/commits/es7-async-await

**Comment by volh** [comment]
Hi, 

is there any blocker on this issue? 

I was looking if js2-mode supports async/await and found this pull request, seems like it's stuck.

**Comment by dgutov** [comment]
@arcanis Why rebase?

@mooz If you think the branch is okay to merge, please make a pull request for it. Or merge it yourself, of course.

**Comment by volh** [comment]
Seems like static class members are not supported, not sure if they should be:

    export default class API {
        static async request(entity, method, data={}) {
            return await xhrFunction(url, {method, data});
        }

        static async get(entity, data) {
            return await this.request(entity, 'get', data);
        }

        static async post(entity, data) {
            return await this.request(entity, 'post', data);
        }
    }

**Comment by osv** [comment]
just bump request :)

**Comment by andresmrm** [comment]
+1

**Comment by XeCycle** [comment]
@volh they should be.

ES6 p. 256 14.5 Class Definitions:
```
ClassElement[Yield]:
  MethodDefinition[?Yield]
  static MethodDefinition[?yield]
  ;
```
http://tc39.github.io/ecmascript-asyncawait/#MethodDefinition adds `AsyncMethod` to the list of `MethodDefinition`, so this definitely is valid.
