### ISSUE TITLE
Publish new version to melpa

### ISSUE THREAD

**Issue by brianloveswords** [mooz/js2-mode#194]
The version up on MELPA (http://melpa.org/#/js2-mode, 20141230.717) doesn't support ES6 module syntax, but the current `master` does. Can you publish a new version to MELPA soon?

**Comment by dgutov** [comment]
MELPA published new versions automatically.

What exactly doesn't work for you?

**Comment by dgutov** [comment]
Scratch that. Everything is fine with `master`?

I've just extracted `js2-mode.el` from http://melpa.org/packages/js2-mode-20141230.717.tar, and it has exactly the same contents.

**Comment by brianloveswords** [comment]
I'm so sorry for wasting your time, I should have restarted after I upgraded before, everything's working fine now!

**Comment by dgutov** [comment]
No problem.

By the way, you might be happy to know that Emacs 25 will force-reload code after package installation. No need for restarts.

**Comment by brianloveswords** [comment]
Oh that's great news! Looking forward to that.
