### ISSUE TITLE
Multiline function arguments indentation

### ISSUE THREAD

**Issue by NicolasPetton** [mooz/js2-mode#196]
It would be nice to have an option to indent multiline function arguments with no vertical indentation. 
There could be a custom variable similar to `js2-pretty-multiline-declarations` but for function arguments.

``` javascript
function foo(bar, 
    baz) {
}
```

vs

``` javascript
function foo(bar, 
             baz) {
}
```

**Comment by pangwa** [comment]
+1 any workaround for this issue?

**Comment by NicolasPetton** [comment]
I have a local fix, but I plan to commit a fix in Emacs js-mode for this.

**Comment by dgutov** [comment]
@NicolasPetton When you do, it should be easy to backport to `js2-old-indent`, too.

But if you don't commit it to `emacs-25` branch now, the users of Emacs 25.1 will have to miss out on it.

**Comment by NicolasPetton** [comment]
@dgutov since emacs-25 is in feature freeze, it won't be in Emacs 25.1 anyway :/

**Comment by dgutov** [comment]
You can always ask...

**Comment by vxcamiloxv** [comment]
+1

**Comment by vxcamiloxv** [comment]
js2-mode should be have different options for indentation like: https://github.com/thomblake/js3-mode/wiki/AlternateStyles

**Comment by dgutov** [comment]
Emacs 26 now has `js-indent-align-list-continuation`.
