### ISSUE TITLE
"Undeclared variable or function 'define'" whenever entering a buffer

### ISSUE THREAD

**Issue by phtrivier** [mooz/js2-mode#198]
Most of my js files are requirejs modules, with the structure

    define(function (require) {
      ....
    });

Whenever I navigate to a buffer with a js file open, I get the "Undeclared variable or function 'define'" message in the minibuffer. 
(If i change the "define" function call to "foobar", I get the "Undeclared.... 'foobar'" message, so it's really about this top level function call.)

How can I avoid that? I tried setting js2-global-externs to "define", with no effect...

Thanks

**Comment by dgutov** [comment]
It's really about any function js2-mode doesn't see the definition of, top level or not.

> I tried setting js2-global-externs to "define", with no effect...

It's a list. Add an element to it.

**Comment by phtrivier** [comment]
Hum, ok, I forgot a quote in the configuration, and I had to exit the mode to make it work. 
Thanks.

**Comment by dgutov** [comment]
> I had to exit the mode to make it work

Odd. I just had to make a buffer modification, and the change was picked up instantly.
