### ISSUE TITLE
js2-additional-externs not honored until after change

### ISSUE THREAD

**Issue by magnars** [mooz/js2-mode#20]
With additional externs in `js2-mode-hook`, the new externs are still marked as undefined until you actually make a change to the document.

The same happens after a `js2-mode-reset`, which will temporarily forget the externs in `js2-additional-externs`.

Right now I worked around it by adding: 

```
(insert " ") 
(undo) 
```

after my definition. Which is quite horrible. :-) 

Anyone else have this problem, or am I doing something wrong?

Here's my complete code:

```
(add-hook 'js2-mode-hook
      (lambda ()
        (when (string-match-p "oppdrag-services" (buffer-file-name))
          (setq js2-additional-externs '("FINN" "assert" "refute" "testCase"))
          (insert " ")
          (undo))))
```

**Comment by ryanprior** [comment]
Hi, this appears to be back in the latest version. The source file reports version "20150909."

I'm setting js2-additional-externs using a directory-local variable like so:
```
((js2-mode
  (js2-additional-externs
   . (list "jest" "describe" "expect" "require" "beforeEach" "require" "it" "spyOn")))
```
When a file in the directory is loaded in js2-mode, those externs are not honored until making a change (as described above.)

Perhaps this is related to the change that made js2-mode derive from js-mode?

**Comment by dgutov** [comment]
@ryanprior Thanks. I don't think adding externs via dir-locals has ever worked properly, but it should now.
