### ISSUE TITLE
Can not parse correctly of nest functions

### ISSUE THREAD

**Issue by freizl** [mooz/js2-mode#200]
It looks good as below or just wrap with immediate function `(function ($) { ... })(jQuery)`.
But can not get `foo` and `Company` when wrap with `define(function () { ... })`, which is [requireJS](http://requirejs.org/).

```
	function foo (a, b) {
		return a+b
	}

	var bar = function (c, d) {
		return c - d
	}

	function Company (name) {
		this.name = name
	}

	Company.prototype.getName = function () {
		return this.name
	}
	Company.prototype.setName = function (name) {
		this.name = name
	}
```

- Expected result when invoke `imenu`

```
foo
bar
Company
getName
setName
```

- Actual result

```
bar
getName
setName
```

I'm using prelude with following extra config
```
(setq js2-global-externs (list "$" "jQuery" "window" "document" "define" "require"))
```

Platform: Emacs 24.3.1 + ubuntu14

**Comment by dgutov** [comment]
What do you mean by "can not get out"?

**Comment by freizl** [comment]
Add expected result and actual result. Sorry for confusion.

**Comment by dgutov** [comment]
Thanks for clarification. Now I see it's about Imenu index generation.

I'll try to keep this in mind, but no promises: the relevant code is already complex, and we already support ES6 modules. I'd recommend trying them with a transpiler instead (if the circumstances allow).

**Comment by dgutov** [comment]
> function Company is not captured as <definition-1>

It *is* recorded as `Company / <definition-1>`. Yes, this is by design, due to the Imenu index format.

**Comment by freizl** [comment]
I see. Thank you and it'll be great to support that. :+1: 
Does that suggest adding a new framework wont help but need to "hack" imenu?

**Comment by dgutov** [comment]
I don't understand the question. We don't hack Imenu, we provide index in the format it supports.

**Comment by freizl** [comment]
fixed.
probably latest imenu has more capability.
