### ISSUE TITLE
js2-mode doesn't recognize class reference

### ISSUE THREAD

**Issue by tensai-cirno** [mooz/js2-mode#204]
I have following code:

```javascript
class Foo { }

export default Foo;
```

js2-mode highlights `Foo` in `export default Foo;` as undeclared variable or function.

I'm using Emacs 24.4.1 and git HEAD version of js2-mode.

**Comment by dgutov** [comment]
Thanks for the report.

**Comment by tensai-cirno** [comment]
Thanks!
