### ISSUE TITLE
Semicolon warning on function declaration export

### ISSUE THREAD

**Issue by simenheg** [mooz/js2-mode#207]
Consider the following export declaration:

```js
export function foo () {}
```

`js2-mode` marks it with the following warning: "missing ; after statement".

According to the [ES6 spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports), function declaration exports don't need a trailing semicolon.

**Comment by dgutov** [comment]
Indeed.

@cowboyd, could you look into this?

**Comment by dgutov** [comment]
It seems we need to add `js2-EXPORT` to `js2-no-semi-insertion`, and then call `js2-auto-insert-semicolon` just for certain exports.

**Comment by cowboyd** [comment]
@dgutov Yeah, I can have a look.

**Comment by cowboyd** [comment]
Is there a way to assert that there are no warnings?

**Comment by dgutov** [comment]
Take the current ast, look up its warnings slot, and assert that it's nil?
