### ISSUE TITLE
Arrow function implicit return "has no side-effect"

### ISSUE THREAD

**Issue by cjohansen** [mooz/js2-mode#209]
ES6 arrow functions have implicit return. js2-mode marks these as code with no side-effects:

```js
[1, 2, 3].map(a => { a * 2; });
```

**Comment by dgutov** [comment]
Are you sure this function does what you think it does? In Firefox: 

```js
[1, 2, 3].map(a => {a * 2});
=> Array [ undefined, undefined, undefined ]
[1, 2, 3].map(a => a * 2);
=> Array [ 2, 4, 6 ]
```

**Comment by cjohansen** [comment]
Nope, I mistakenly thought arrow functions would implicitly return the last statement in the function body. Really I should file this bug with the ES people :P
