### ISSUE TITLE
"Invalid property id" raised for method definitions in ES6 classes

### ISSUE THREAD

**Issue by eush77** [mooz/js2-mode#216]
```js
class Class {
  delete() {
  }
}
```

Expected behavior: no error.
Actual behavior: “Invalid property id”.

As [described][1] in ES6 draft, keys in method definitions are PropertyNames and PropertyNames are IdentifierNames:

```
PropertyName → LiteralPropertyName → IdentifierName
```

Related discussion: #183.

[1]: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-method-definitions

**Comment by dgutov** [comment]
Thanks for the report.

**Comment by eush77** [comment]
This is still considered an error:

```js
class Class {
  constructor() {
  }
  delete() {
  }
}
```

**Comment by dgutov** [comment]
It should work now too. Thanks.
