### ISSUE TITLE
Missing semicolon warning

### ISSUE THREAD

**Issue by madhavan020985** [mooz/js2-mode#217]
I am setting two global variables in my emacs during startup::::
````lisp
(setq js2-strict-missing-semi-warning t)
(setq js2-missing-semi-one-line-override t)
````
But still, i see 
````javascript
Missing ; after statement
````
I use js2-mode as major mode & Tern as minor-mode, emacs versioned 24.3.1, js2-mode version 20141118.

**Comment by dgutov** [comment]
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by dgutov** [comment]
What do you want to do? Why do you set these variables?

**Comment by madhavan020985** [comment]
hi dutov, i set this variable to tell js2-mode, that missing semicolons i am okay with it & don't highlight it as a warning/error. after setting the variables, js2-mode mark the missing semicolon areas in red which is my concern....

**Comment by dgutov** [comment]
I never see them highlighted in red.

And why do you set these variables to t? That only enables them. Set the first one to nil.

**Comment by madhavan020985** [comment]
my stupidity... thanks dgutov....

**Comment by vasspilka** [comment]
@madhavan020985 Your stupidity saved me a lot of time :+1: :) :)

**Comment by zachlatta** [comment]
:+1: stupidity. Also saved me time.

**Comment by alexbrillant** [comment]
same

**Comment by viktorstrate** [comment]
Keep up the stupidity 👍 😄
