### ISSUE TITLE
Inserting characters toggling bounce indent

### ISSUE THREAD

**Issue by kzar** [mooz/js2-mode#226]
I really like the bounce indentation feature but recently it keeps getting toggled when I insert syntactically significant characters. For example if I go to the end of a line and keep hitting `;` the indentation bounces around the same as if I was hitting the tab key.

I'm not sure what is causing this, or if it is even a js2-mode issue but it's driving me crazy. Here's a gif to show you what I mean:

![js2-mode-bounce-on-insert](https://cloud.githubusercontent.com/assets/155710/6657166/b2ac0744-cb3a-11e4-8179-a71eb0b5fe59.gif)

For now I've had to just disable bounce indentation which is a shame. I've tried updating js2-mode but no joy. I'm running version 20150304.1821 from the package manager.

**Comment by dgutov** [comment]
That's `electric-indent-mode`. You can toggle it off globally, or if you're using at least Emacs 24.4:

```
(add-hook 'js2-mode-hook (lambda () (electric-indent-local-mode -1)))
```

Or if you're fine with it but don't like the bouncing in this specific scenario, I could look into this deeper.

**Comment by kzar** [comment]
Aha, I had not heard of `electric-indent-mode`. Adding that hook makes things behave exactly as I had wanted! Thanks for the help :+1:
