### ISSUE TITLE
js2 syntax coloring

### ISSUE THREAD

**Issue by zen0x90** [mooz/js2-mode#228]
Hi,

I have a conflict with js2 and solarized. When I enable js2-mode my solarized theme get "overlaped" by js2 syntax coloring. Is is possible to disable js2 syntax coloring ?

Cheers,

**Comment by dgutov** [comment]
> my solarized theme get "overlaped" by js2 syntax coloring

What does that mean?

**Comment by zen0x90** [comment]
It seems that solarized theme is replaced js2 syntax coloring.

**Comment by dgutov** [comment]
Post a screenshot, please.

**Comment by zen0x90** [comment]
Left   = js2-mode enable
Right = js2-mode disable (solarize theme)

![js2](https://cloud.githubusercontent.com/assets/11389647/6997155/7b0d5b54-dbb0-11e4-91dc-fafcbd919cda.png)

**Comment by dgutov** [comment]
Why would you enable `js2-mode` in an HTML file? Don't do that. Of course it shows you errors because it can't parse HTML code (not to mention the CSS declarations).

**Comment by zen0x90** [comment]
Because of the indentation.

Ok no js2-mode for HTML.
