### ISSUE TITLE
js2-mode highlights trailing bracket instead of function key

### ISSUE THREAD

**Issue by dradetsky** [mooz/js2-mode#234]
If I write

    {
        a: function() {},
        b: 3
    }

js2 used to recognize that a was the key of a function, and color it differently from other keys (blue). but now, instead of this, it colors the closing bracket right before the comma blue.

It also appears to be coloring thing wrong in general. If I write:

            _.extend(inAct, {
                created: created,
                begin: begin,
                stop: false,
                done: false,
                fail: false
            });

It used to color keys yellow, values white. It is now coloring them the other way around.

I have tried byte-recompiling js2, to no avail.

This issue appeared around the time I tried to install tern-mode and json-mode. I believe I installed some tern-related highlighter. I uninstalled everything except json-mode and recompiled, no joy. I also tried uninstalling json-mode, but I don't remember if I recompiled js2-mode after that. I don't know if this is related. 

js2-version is 1.8.5. I got it from melpa, so I think it's more or less tip of the repo.

Let me know if you need more info.

**Comment by dgutov** [comment]
It was a regression from a recent change. Now fixed, thanks for the report.
