### ISSUE TITLE
`C-k` on line with missing semicolon freezes Emacs in js2-mode.

### ISSUE THREAD

**Issue by masondesu** [mooz/js2-mode#235]
For some strange reason, when in js2-mode (version 20150514.550), when I <kbd>C-k</kbd> on a line that looks like this...

```js
var abc123
```

...I get a "Missing semicolon" warning and Emacs completely freezes up. It appear to hang forever, no keystrokes, no errors, nothing. This problem *doesn't* occur as soon as I turn off js2-mode, but can be reproduced reliably when it's enabled.
 
I'm using [Emacs Mac Port](https://github.com/railwaycat/emacs-mac-port) GNU Emacs 24.4.1 (x86_64-apple-darwin12.5.0, Carbon Version 155 AppKit 1187.4) on OS X 10.8.5.

I realize that js2-mode may be a red herring here. Any ideas on this?

**Comment by dgutov** [comment]
It doesn't freeze for me. Do you have a self-contained example and a scenario starting with `emacs -Q`?

**Comment by masondesu** [comment]
Sorry for the trouble, this turns out to have been unrelated to js2-mode. Red herring! Thanks!
