### ISSUE TITLE
`const` and strict mode

### ISSUE THREAD

**Issue by jacksonrayhamilton** [mooz/js2-mode#236]
According to the [ES6 draft](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations), `const` variables are now block-scoped (scoped in the same way as `let` variables:

> `let` and `const` declarations define variables that are scoped to the [running execution context](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-execution-contexts)’s [LexicalEnvironment](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-execution-contexts).

[In contrast](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-variable-statement) to `var`, which is scoped to a script or function:

> A `var` statement declares variables that are scoped to the [running execution context](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-execution-contexts)’s [VariableEnvironment](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-execution-contexts).

When `const` was just a non-standard Mozilla extension, and while in ES6 non-strict mode, it is scoped the same as `var`.

It might be a good idea to check if the current scope is running in strict mode so that `const` can be added to the correct scope. I expect the variables to be scoped like this:

<p align="center"><img src="http://img42.com/EBmlC+"> <img src="http://img42.com/xeZ18+"></p>

But right now in `js2-mode` they are scoped like this (in strict mode the `c` is still blue):

<p align="center"><img src="http://img42.com/gvcDf+"> <img src="http://img42.com/xeZ18+"></p>

I've taken a look at the source and haven't found any indication that ECMAScript strict mode can be detected. There is a `js2-mode-show-strict-warnings` flag which claims to show "Ecma strict-mode warnings", but these warnings include trailing commas, missing semicolons, inconsistent return values, variable redeclarations, ironically *none* of which are actually observed by `"use strict";`.

Therefore, I'd like to request *real* strict mode support.

(For the implementation, note that `"use strict"` must appear as the first statement in a function:)

```js
(function () { 'use strict'; {const a = 1;} console.log(a); }());
// Uncaught ReferenceError: a is not defined

(function () { void 0; 'use strict'; {const a = 1;} console.log(a); }());
// 1
```

**Comment by dgutov** [comment]
Makes sense. Would you like to provide a patch?

`js2-mode-show-strict-warnings` is referring to the "strict mode" from ECMAScript 5, not "use strict". It could use an update as well.

**Comment by jacksonrayhamilton** [comment]
I might like to. :)

Actually, I can see the implementation as being pretty simple. Modify the function / script parsers to check for a single string statement(?) which is `"use strict"`, and if so, set a flag on the the function / script node indicating that it runs in strict mode.

To detect strict mode from a node, check that node (or its parents recursively) until a node is found that is in strict mode, and if so return `t`, `nil` otherwise.

Finally to solve my original problem, update `js2-define-symbol` to check for strict mode before adding a `const` to a scope. Think I need to update any `const`-handling logic anywhere else?

Additional features that utilize `js2-node-strict-mode-p` can be added incrementally as desired.

**Comment by dgutov** [comment]
> for a single string statement(?)

It will be an expr-stmt-node wrapping a string-node, I think.

> Finally to solve my original problem, update js2-define-symbol to check for strict mode before adding a const to a scope. Think I need to update any const-handling logic anywhere else?

Probably not.

> To detect strict mode from a node, check that node (or its parents recursively) until a node is found that is in strict mode, and if so return t, nil otherwise.

This could be fast enough, but you could also have a dynamic variable. Let-bind it to the existing value around `js2-parse-function-body`, and if the first statement is `use strict`, set it to t. This way, the check would be simpler.

You could also look at how SpiderMonkey tracks the strict mode, maybe that'll bring up some better idea. Although IIRC their approach would be clunkier in Elisp.

> Additional features that utilize js2-node-strict-mode-p can be added incrementally as desired.

Indeed, we don't really check for any strict mode limitations currently. Such as `with` being a syntax error, for example.
