### ISSUE TITLE
Parse /* jslint */ declarations

### ISSUE THREAD

**Issue by strugee** [mooz/js2-mode#237]
js2-mode should be able to parse `/* jslint */` declarations. This is especially useful for e.g. Node.js code, where you'd want to have `/* jslint node */`.

Looking at `M-x customize-group RET js2-mode`, it appears that `js2-mode` already has the capability to do this. It just needs to be hooked up to some parsing logic.

**Comment by dgutov** [comment]
> js2-mode already has the capability to do this

Indeed. And someone will have to decide whether to use our lists for `node`, `browser`, `ecma-262`, or obey JSLint, which assigns somewhat different meanings to all of them except `node`, it seems. `browser` is vastly different.

Patch welcome.
