### ISSUE TITLE
"missing ; after statement" is often not a syntax _error_

### ISSUE THREAD

**Issue by mentalisttraceur** [mooz/js2-mode#238]
It seems to me that js2-mode flags all statements not ending with semicolons as errors. However, JavaScript spec has well-defined rules for when semicolons can be omitted.

For example, the following is completely legal code:
```
var foo = 3
var bar = function(qux)
{
    qux += 1
    console.log(qux)
    return qux
}
foo = bar(foo)
```
...yet the majority of those lines are marked in a way that looks like errors to me.

There are of course places where those are legitimately errors that are flagged in the same manner:
```
// Illegal:
'hello' foo = bar
// Legal:
'hello'
foo = bar
```
..which makes me worry that the parsing logic is mistaken about the actual specification of the language syntax.

Holy wars regarding the topic of whether people should code with omitted semicolons aside, I would expect/want a syntax checker to genuinely check the code for syntactical correctness, rather than convention, or worse, be based on an erroneous understanding of what syntax is actually legal.

I can understand it strongly warning about that syntactical choice by default if the authors felt it ought to, but even so I'd also expect some configurable variable one could set in their emacs configuration file(s) to disable said warning.

Is there such an option already?

**Comment by mentalisttraceur** [comment]
Also, perhaps my usage of the word "error" above is different terminology than what is used in js2-mode: The core point is that it seems to flag it both the legal and illegal/broken syntax the same.

**Comment by dgutov** [comment]
> ...yet the majority of those lines are marked in a way that looks like errors to me.

Errors are red, warnings are the orange underline.

> Is there such an option already?

Yep. `js2-strict-missing-semi-warning`.

**Comment by mentalisttraceur** [comment]
@dgutov Thank you! My apologies for confusing the errors/warnings: the theme I was using was turning both of them red, so I didn't realize they'd normally be different colors.

**Comment by dgutov** [comment]
No problem. You should report that to the theme author.
