### ISSUE TITLE
Better indentation with chaining

### ISSUE THREAD

**Issue by jrd261** [mooz/js2-mode#239]
Chaining indentation is working is this case:
```
baz = foo
  .bar();
```

But not in cases with added complexity.
```
var baz = foo
        .bar();
```

**Comment by dgutov** [comment]
Which one looks better:

```js
var baz = foo
        .bar().tee(),
    qux = fee()
        .fo().fum();
```

or

```js
var baz = foo
  .bar().tee(),
    qux = fee()
  .fo().fum();
```

?

**Comment by jrd261** [comment]
The former is easier to read, neither follow a consistent pattern. Logically, I would have expected this:

```
var baz = foo
  .bar().tee(),
qux = fee()
  .fo().fum();

```
but I agree that if one wants to instantiate and assign many variables, pretty > logical. I consider multi variable declarations an anti-pattern but that is a bit subjective. This closing brace after the first statement below is trying to tell me that the next guy is getting magically indented.

```
var foo = function () {
  // Statements                                                                                              

},
    bar = function () {
      // Statements                                   
    };

```

On a related note, with fat arrows and promises about to become all the rage I've noticed that the single statement implicit returns create some indentation issue because of the lack of curly brace helping to define the block. I suspect we'll see a lot  more of this in the next year or two. You end up with chains like this:

```

Promise.resolve().then(() => Promise.resolve()
                                      .then(() => Promise.resolve()))
  .then(() => Promise.resolve());

```

**Comment by dgutov** [comment]
> Logically, I would have expected this:

`(setq js2-pretty-multiline-declarations nil)`, and you'll have it.

> This closing brace after the first statement below is trying to tell me that the next guy is getting magically indented.

You can `(setq js2-pretty-multiline-declarations 'dynamic)`, and both values will be indented the same.

> the single statement implicit returns create some indentation issue because of the lack of curly brace

It's not ideal, but not too terrible either. Anyway, if someone's interested in improving this, they're welcome to start with a patch for Emacs's `js.el`.

**Comment by jrd261** [comment]
Thanks Dmitry.
