### ISSUE TITLE
Faces for js2-mode only.

### ISSUE THREAD

**Issue by ReneFroger** [mooz/js2-mode#241]
Thanks for sharing this awesome package! However, I have a question:

### Situation:
I have different syntax coloring for [javascript in Web-mode](https://github.com/fxbois/web-mode/issues/487). 
When I enable JS2 on a javascript-file, I noticed he gets the syntax coloring of my default colors for functions, strings, variables, etc. 

### Desired behaviour:
I would like to have a different syntax faces for JS2 mode, which looks greenish. Like this: 
![schermafdruk 2015-06-06 01 13 43](https://cloud.githubusercontent.com/assets/5211845/8016859/8fc3c510-0be9-11e5-880d-e31098c23008.png)

Left is JS2-mode, right is web-mode with the correct colors for Javascript. 

When I looked into the source code of JS2-mode, I couldn't find specific syntax faces for JS2-mode only. The colors that I now get in JS2-mode, are actually reserved for another languages. 

I couldn't find the faces. So I'm wondering, if JS2-mode knows own faces, which are not default for all languages?

**Comment by dgutov** [comment]
It has some special faces where there are no generic ones we can use, but not for keywords or function names.

Do you want to use a different color for keywords, only in js2-mode? Why?

**Comment by ReneFroger** [comment]
Do you have a list of the special faces? And how could I 'tell' to use the special faces, instead the generic ones? 

Yes, I would like to have different (greenish) colors for in js2-mode. I switch around buffers a lot, switching from HTMlL, CSS, PHP, JS. The different syntax color enables me to identifiy fast in which file I am.

**Comment by dgutov** [comment]
> Do you have a list of the special faces?

Search for `defface` in `js2-mode.el`. But no, there's no way to use them in other cases.

> I switch around buffers a lot, switching from HTMlL, CSS, PHP, JS. The different syntax color enables me to identifiy fast in which file I am.

That seems an odd request. Do you know of another major mode that has a separate list of faces like that?

**Comment by ReneFroger** [comment]
Yes, [web-mode](https://github.com/fxbois/web-mode) for example.

**Comment by dgutov** [comment]
> How could I 'tell' js2-mode to use them, instead the generic faces?

You're not supposed to.

> Yes, web-mode for example.

Any example of programming language major mode? web-mode is one of a kind, so to speak.

**Comment by ReneFroger** [comment]
I'm just wondering how I could set up faces only for js2-mode. So I don't understand why you consider another modes to be important for js2-mode?

If you insist on more examples of major modes, next to web-mode, [Android mode for example](https://github.com/remvee/android-mode) or even the [default GNU package Auctex](https://www.gnu.org/software/auctex/), [RPM mode](https://www.gnu.org/software/auctex/) and so on. 

Any way to let use js2-mode to use their faces, instead the generic ones?

**Comment by dgutov** [comment]
> So I don't understand why you consider another modes to be important for js2-mode?

Because the most simple way to make it work, is to add a bunch of new faces to js2-mode that inherit from the default faces, and make it use them. But I don't like this feature proposal, so an example would show whether it's going to be at all popular with other users.

> Android minor mode for example, default GNU major mode Auctex, RPM major mode and so on

Not all links work (or lead to Elisp code), but none of these seem to provide a replacement for `font-lock-function-name` face, just a bunch of faces where they didn't find any suitable faces in the default set.

Anyway, here's a solution which it seems you'll be able to apply all by yourself, in js2-mode-hook:
http://emacs.stackexchange.com/questions/7281/how-to-modify-face-for-a-specific-buffer

Let me know if you have any problems with it.

**Comment by ReneFroger** [comment]
@dgutov thanks for your alternative solution. I looked into your link, and indeed, it could be a workaround! Thanks for looking into my issue!
