### ISSUE TITLE
spread in object literal results in error

### ISSUE THREAD

**Issue by gaydenko** [mooz/js2-mode#248]
Hi!
```js
const obj = {};

const obj2 = {
    ...obj,
  plus: 'plus'
};
```
For such spread operator I get `invalid property id` error on `...obj` (followed with other derived errors). Is it possible to workaround the issue?

**Comment by dgutov** [comment]
There's an attempt to implement support for this in #245, but it seems to have stalled.

**Comment by gaydenko** [comment]
Thanks for the clarification. Must I keep the issue opened? Or - is PR sufficient?

**Comment by dgutov** [comment]
Yes, let's keep it open.

**Comment by nikki93** [comment]
hey any updates on object spread operator? it's pretty useful in programming with react libraries!

**Comment by dgreensp** [comment]
What should the AST look like for `var obj = {a:1, b:2, ...more, ...foo(1, 2, 3)}`?  It seems clear that `...foo(1,2,3)` should become an `object-prop` node whose `right` (not `left`) is `foo(1,2,3)`, with the `left` being some sentinel value that won't trip up any existing code that iterates over `object` nodes too much.  What should that value be?  Something based on the `TRIPLEDOT` token?

**Comment by dgreensp** [comment]
Hmm, or maybe `...foo(1,2,3)` doesn't have to become an `object-prop` after all.  I was assuming that all `elems` of an `object-node` should be `object-prop` nodes, but it looks like e.g. methods are already a completely different struct, and it works just fine.  So maybe a `unary-node`.

**Comment by dgutov** [comment]
> it looks like e.g. methods are already a completely different struct, and it works just fine

`js2-method-node` inherits from `js2-infix-node`, though.

**Comment by dgreensp** [comment]
I signed with FSF.

I haven't had a chance to revise my PR, but I am on board with using an `infix` node for less risk of breakage.  When I come back to it, I'll figure out how to make an `infix` node and what `:left` and `:type` should be.

**Comment by jeffbski** [comment]
+1

**Comment by kamilwaheed** [comment]
+1

Really looking forward to this getting addressed.

**Comment by damonmcminn** [comment]
+1

**Comment by azer** [comment]
+1

**Comment by miguel-guedes** [comment]
+1

**Comment by edheil** [comment]
+1

**Comment by cauchycai** [comment]
+1

**Comment by dgutov** [comment]
This should work now. Thanks to @dgreensp and the testers.
