### ISSUE TITLE
Fontifying broken as of melpa version 20150721.358

### ISSUE THREAD

**Issue by aisipos** [mooz/js2-mode#249]
After updating to js2-mode 20150721.358 from melpa, fontifying is not working correctly for me in js2-mode. I'm running Emacs 24.5

The behavior I see is:
* on loading a file, the buffer is fontified correctly.
* as I edit the file, new changes / additions are not fontified.
* If I rerun the command js2-mode manually, the entire buffer is then fontified correctly. But again, as I make subsequent new additions, these are not fontified.

I have js2-mode (as well as tern) enabled in my init.el as follows:

```
(use-package js2-mode                   ; Javascript editing
             :ensure t
             :mode "\\.js\\'"
	     :interpreter ("node" . js2-mode)
	     :config
             (progn
               (setq js2-use-font-lock-faces t
                     mode-name "JS2")
               (setq-default js2-bounce-indent-p nil
                             js-indent-level 2
                             js2-basic-indent 2
                             js2-basic-offset 2
                             js2-auto-indent-p t
                             js2-cleanup-whitespace t
                             js2-enter-indents-newline t
                             js2-global-externs "jQuery $"
                             js2-indent-on-enter-key t
                             js2-mode-indent-ignore-first-tab t
                             js2-global-externs '("module" "require" "buster"
                                                  "sinon" "assert" "refute"
                                                  "setTimeout" "clearTimeout"
                                                  "setInterval" "clearInterval"
                                                  "location" "__dirname"
                                                  "console" "JSON" "angular"))

	       (add-hook 'js-mode-hook 'js2-minor-mode)
               (js2-imenu-extras-setup)
	       (add-hook 'js2-mode-hook #'js2-highlight-unused-variables-mode)))

(use-package tern
  :ensure t
  :defer t
  :config
   (progn
     (add-hook 'js2-mode-hook (lambda () (tern-mode t)))))

(use-package company-tern
  :ensure t
  :defer t)

```

Since I'm not seeing any other similar reports about this fontifying problem, perhaps it is something peculiar to my setup. Is there any way I can help debugging the problem?

**Comment by dgutov** [comment]
Try removing this line (and restarting):

```el
(add-hook 'js-mode-hook 'js2-minor-mode)
```

If that still doesn't help, please post an example file where I can reproduce it.

If the code in question is proprietary, try to "bisect" the contents: 

- Remove some code. Does the bug still reproduce? Continue removing.

- It doesn't reproduce anymore? Undo the last change, try removing something else.

When it's down to several lines, you can replace the important bits that are still left with generic words and post it here.

**Comment by aisipos** [comment]
Removing 
```
(add-hook 'js-mode-hook 'js2-minor-mode)
```
Fixed the issue for me.

I suppose the removal of that line isn't a big deal for me, since I use js2-mode for editing js. But is there a reason why that line is causing trouble, and why it happened only in the most recent version?

**Comment by dgutov** [comment]
Great!

`js2-mode` derives from `js-mode` now, so you had `js2-mode` and `js2-minor-mode` enabled at the same time. I wasn't able to reproduce the problem with default configuration and that hook, but it's not hard to imagine them conflicting.

Guess `js2-minor-mode` should be disabled automatically if the current major mode is `js2-mode`.
