### ISSUE TITLE
ELDoc support

### ISSUE THREAD

**Issue by jacksonrayhamilton** [mooz/js2-mode#250]
Could ELDoc support be added to js2-mode? That is:

- With point over a function call, the function's arguments and documentation would be displayed.
- With point over a variable, the variable's documentation would be displayed.

Some ideas:

For simple function calls and variable references, we could:

1. Look up the scope chain for the variable's initialization / assignment. If found:
  1. For functions, extract the parameter list from the node.
  1. Go to that position, check the line immediately above it for a comment block (by default, a JSDoc-style comment `/** */`, but possibly it could be configured to accept multiple consecutive single-line comments also). Extract the first line of that comment block to use as the ELDoc docstring.
     1. Unlike ELDoc for Emacs Lisp, we could show the docstring for functions too; could be useful. We could auto-hide it if there isn't enough space or make it optional for functions.
     1. We could also parse the JSDoc parameters to figure out if any parameters are [optional][] or [repeatable][].

[optional]: http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values
[repeatable]: http://usejsdoc.org/tags-param.html#multiple-types-and-repeatable-parameters

We could obtain documentation for built-in objects and their methods from MDN.

If we also wanted to provide documentation for third-party libraries (e.g. the methods of `$`, `_` or `Backbone` objects), we could also use data from a project like [devdocs][]. Though that might be a lot of work for just this feature. (Might be worthwhile if we wanted to also do a `describe-function` or `describe-variable` implementation for JavaScript, which would be pretty awesome too.)

[devdocs]: https://github.com/Thibaut/devdocs/

For determining the documentation of userland methods, it's trickier, because we don't necessarily know what type of object we're talking about. We could use JSDoc parameter types as hints; e.g. for the documentation `@param {Array}` we could infer the definition of `slice`, `forEach` etc for that object. If the caller is a global variable and has the name of a built-in object like `Array`, `Date` etc we could infer the documentation of its static methods from the MDN database.

Also, function and variable definitions could be defined in separate files. We could do asynchronous parsing of entire projects to collect definitions, but that might be... difficult. And still tricky because we don't necessarily know how methods are being defined. They could be placed on prototypes, or attached to objects dynamically. I don't think many people define all their functions and variables globally like Emacs Lisp programmers do, so we can't just peruse top-level definitions.

After writing this all up I'm starting to realize this could be really complicated. I'm wondering if even a subset of this is feasible. Thanks for reading.

**Comment by dgutov** [comment]
It might be feasible for global methods, or methods on singleton objects. Basically, the same cases that #159 handles.

So, this feature could build on that one.

**Comment by jacksonrayhamilton** [comment]
Great. What's the status on #159?

**Comment by dgutov** [comment]
I haven't had a chance to check out its latest changes yet. Why don't you try it out?

**Comment by osv** [comment]
ternjs can show some jsdoc.

**Comment by jacksonrayhamilton** [comment]
Indeed, tern seems to do (or at least aspires to do) most of the things I've suggested in the OP. Since it runs as a server, tern could probably do a better job of it too.

**Comment by jacksonrayhamilton** [comment]
Closing since I'm pretty sure this is best left to tern.
