### ISSUE TITLE
Lisp nesting exceeds `max-lisp-eval-depth'. js2-mode-20150726.1330

### ISSUE THREAD

**Issue by hung-phan** [mooz/js2-mode#252]
I run into this error after update to the latest js2-mode. I did follow some guides in the issue and google code by increasing max-lisp and recompiling it from source. However, nothing seems to work for me. Any idea on this?

**Comment by dgutov** [comment]
Maybe try `emacs -Q --batch -f batch-byte-compile path/to/js2-mode.el`.

**Comment by hung-phan** [comment]
Thanks @dgutov, that does the trick.
