### ISSUE TITLE
Imenu call cause error: Symbol's function definition is void: js2-re-search-forward on Emacs 25

### ISSUE THREAD

**Issue by geksilla** [mooz/js2-mode#253]
Hi, hit this issue with emacs 25.0.50.1. 

```
js2-imenu-record-declarations: Symbol's function definition is void: js2-re-search-forward
```

I see that js2-old-indent is [excluded here](https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L93) but imenu doesn't work without this file. Thanks.

**Comment by dgutov** [comment]
Sorry, and thanks for the report. This should fix it.

**Comment by geksilla** [comment]
@dgutov thanks!
