### ISSUE TITLE
Strange indentation after commenting region

### ISSUE THREAD

**Issue by jacksonrayhamilton** [mooz/js2-mode#254]
Take the following code:

```js
a.concat({
})
```

If I select the whole object literal, and run `comment-dwim` on the region, the resulting indentation is this:

```js
a.concat(// {
// }
        )
```

However, after running `indent-for-tab-command` on the last line, the indentation becomes this:

```js
a.concat(// {
// }
)
```

I expect the indentation to be like the 3rd example after commenting-out the region, rather than like the 2nd.

To reproduce:

```bash
emacs --version # GNU Emacs 24.5.1
emacs -Q \
  -L path/to/js2-mode-20150813.1733/ \
  -l js2-mode \
  foo.js \
  --eval '(progn (js2-mode) (insert "a.concat({\n})") (goto-char 10) (set-mark-command nil) (goto-char 13) (comment-dwim nil))'
```

**Comment by dgutov** [comment]
> comment-dwim is an interactive compiled Lisp function in ‘newcomment.el’.

:)

It's the same in `js-mode`, for example.

**Comment by jacksonrayhamilton** [comment]
I'm not sure what you're saying. By `comment-dwim` I was referring to the command bound to `M-;` by default.

**Comment by jacksonrayhamilton** [comment]
Oh, so you're saying that it's not just a problem with this mode, it's a problem with `comment-dwim`, and that function is the one which should be fixed?

**Comment by dgutov** [comment]
Right. Sorry for being unclear.

So, unless there's something I'm missing, it's a problem to be fixed in Emacs, not in this major mode.
