### ISSUE TITLE
JSDoc @property highlighting

### ISSUE THREAD

**Issue by simenheg** [mooz/js2-mode#255]
The JSDoc `@property` tag accepts a name after the optional type, just like the `@param` tag. Currently the name is highlighted with `font-lock-doc-face`, causing it to blend into the rest of the description. It seems like the `@property` name should be highlighted with the `js2-jsdoc-value` face, just like it is in the case of `@param`.

See http://usejsdoc.org/tags-property.html for a usage example.

(The same goes for `@prop`, which is an alias for `@property`.)

**Comment by dgutov** [comment]
Thanks for the report, it should work now.

**Comment by simenheg** [comment]
That seemed to work great! Thanks, Dmitry.
