### ISSUE TITLE
Flag to disable `js2-no-semi-insertion`

### ISSUE THREAD

**Issue by volrath** [mooz/js2-mode#256]
Hi, I did a quick search over the issues and didn't find anything related to this, but I apologize in advanced if that's not the case.

I want to disable the automatic semicolons insert from js2-mode. I'm thinking it'll be something like adding a defcustom `js2-disable-auto-semi-insertion` default to `nil` and changing the lines:

https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L8358

to...

```lisp
(unless (or (memq first-tt js2-no-semi-insertion)
                (js2-disable-auto-semi-insertion)
                (js2-labeled-stmt-node-p pn))
```

I'm absolutely new to this project so I'm not really sure if this is all it takes, but if it is, I can submit the PR.

Thanks!

**Comment by dgutov** [comment]
Why?

It doesn't insert semicolons into the buffer. Just virtually, into the generated AST.

**Comment by volrath** [comment]
You can completely disregard this. I'm using magnars' emacs.d and his js2 setup is the one doing the auto inserting in the buffer. Thanks anyway.
