### ISSUE TITLE
This little snippet in js2-mode freezes my system

### ISSUE THREAD

**Issue by vbichkovsky** [mooz/js2-mode#259]
<code>
let [

test('empty graph', () => {
    let extracted = extract_primitives([], []);
    expect(extracted.isolated).to.eql([]);
});
</code>

**Comment by vbichkovsky** [comment]
This situation happens frequently when you type in some de-structuring assignment such as
<code>
let [a,b] = [[1,2], [3,4]];
</code>

**Comment by dgutov** [comment]
Thanks for the report, I'm looking into it. Meanwhile, you can `M-x electric-pair-mode` to input parens and brackets in pairs automatically.
