### ISSUE TITLE
Parsing bug when returning something on the next line

### ISSUE THREAD

**Issue by strugee** [mooz/js2-mode#261]
The following is parsed as valid JS:

```js
function test () {
	return { 'something': true };
};
```

But the following is not:

```js
function test () {
	return
	{ 'something': true };
};
```

The `return` line is marked as "missing ; after statement", and the object literal is marked as "Code has no side effects". FWIW the spec states that if a semicolon is not present, and the next line _can_ be interpreted as a continuation of the current line, then it _will_ be interpreted as a continuation. Essentially.

Why you'd want to do this is beyond me. I only found it because I copypasta'd an object literal while reducing something to a testcase.

**Comment by dgutov** [comment]
> FWIW the spec states that if a semicolon is not present, and the next line can be interpreted as a continuation of the current line

`return` is some kind of exception, IIRC.

Have you tried running the second example? Pasting it in Firefox gives me exactly the same syntax error as `js2-mode` displays.

**Comment by strugee** [comment]
> Have you tried running the second example? Pasting it in Firefox gives me exactly the same syntax error as js2-mode displays.

I know at some point I tested it in Node, but I can't reproduce right now. Seems like the REPL keeps waiting for something. I get an exception in Firefox, though.

**Comment by strugee** [comment]
Yeah, I can't reproduce. Weird.

**Comment by glasser** [comment]
This is actually a pretty classic example of where JS' automatic semicolon insertion (that's the phrase to search for) bites people. Here's one good explanation: http://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi

That is definitely parsed as "return undefined, then a statement whose evaluation is pointless"

**Comment by strugee** [comment]
Ah, yeah. According to my JavaScript Pocket Reference:

> More formally, JavaScript intertprets a line break as a semicolon if it appears after the `return`, `break`, or `continue` keywords, or before the `++` or `--` operators, or if the next nonspace character cannot be interpreted as a continuation of the current statement.

This is clearly not a bug.
