### ISSUE TITLE
100% CPU usage under specific circumstances

### ISSUE THREAD

**Issue by jamesbehr** [mooz/js2-mode#262]
This is weird, but it's happening even when I start with `emacs -q` and manually load js2-mode.
When typing the `class` keyword before a very specific array structure, Emacs shoots up to 100% usage.

*Steps to reproduce:*

1. Open a buffer with `js2-mode` on
2. Type the following code:

````javascript
// Type class here

A.A(A.A([
    ['string', A.A],
    ['string', A.A],
    ['string', A.A],
    ['string', A.A],
    ['string', A.A],
    ['string', A.A],
    ['string', A.A],
]))

````

3. On a new line underneath the comment, type "class " and it will freeze

Anything of this form where there is lots of property access in a nested array seems to cause this.

I am on Emacs 24.3.1 and a js2-mode labelled version "20150713"

If anyone could help me with this, that would be great.

**Comment by dgutov** [comment]
Hi!

It seems I've already fixed that. Do you install `js2-mode` from MELPA or GNU ELPA? If the former, you just need to upgrade.

**Comment by jamesbehr** [comment]
Thanks for the help, I've installed the latest version from ELPA and it's working now.
