### ISSUE TITLE
"Property 'x' already defined" for getters and setters and 'use strict'

### ISSUE THREAD

**Issue by tprk77** [mooz/js2-mode#264]
It seems that getters and setters with the same name are being confused for the same property. The error message is only shown in strict mode.

For example, given the following code in a `js2-mode` buffer:

```javascript
'use strict';

class X {
  get x() {  }
  set x(val) {  }
}
```

The `x` in `set x(val) { }` will be highlighted red, and it will show the message:

`Property 'x' already defined in this object literal.`

**Comment by dgutov** [comment]
Thanks for the report.

@jacksonrayhamilton Could you check it out?

**Comment by jacksonrayhamilton** [comment]
Sure, I'll take a look soon.

**Comment by tprk77** [comment]
Awesome, thanks guys!
