### ISSUE TITLE
React & ES6 Support

### ISSUE THREAD

**Issue by azer** [mooz/js2-mode#267]
Is there any road map to add support for React and ES6? I see some issues and pull requests about ES6 but I can't view any ES6 file properly.

**Comment by dgutov** [comment]
Many ES6 features work, some don't. Not all browsers implement the full extent of ES6 either (I think none of them does).

There are a few issues about missing ES6 features open (like #205 and #248). If you see any problems we don't know about, please open issues with specific examples.

React is not a JavaScript feature.

**Comment by azer** [comment]
I've changed the title from "React" to JSX.

**Comment by dgutov** [comment]
JSX support has been discussed in #140.

**Comment by istinspring** [comment]
spread operator is definitely useful, and there is bunch of use cases when you just need to use it.

<Component {...boundActionCreators} {...this.props} />
