### ISSUE TITLE
Another indentation for JSON properties

### ISSUE THREAD

**Issue by ReneFroger** [mooz/js2-mode#269]
For example, we have the following JSON in js2-mode: 

    var mary = {
        firstName: "Mary",
        lastName: "Johnson",
        phoneNumber: "(650) 888-8888",
        email: "mary.johnson@example.com"
    };

The JS2-mode indents everything inside the object (after `{`) to be right aligned.
I would like to make a proposal to align automatically the `:`, like this: 

    var mary = {
        firstName   : "Mary",
        lastName    : "Johnson",
        phoneNumber : "(650) 888-8888",
        email       : "mary.johnson@example.com"
    };

Would that be possible?

**Comment by dgutov** [comment]
That's not indentation, though. You'd be better off using the `align` package.

See http://emacs.stackexchange.com/questions/2644/understanding-of-emacs-align-regexp, for example.

**Comment by ReneFroger** [comment]
@dgutov thanks for maintaining this package, it's really appreciated! And yes, I'm aware of that align functionality, I even use it extensively in my coding sessions. 

Sorry for any confusion, I couldn't find any better word than indentation. But I'm wondering if it could be default aligned, when I indent the whole buffer in js2-mode?

**Comment by dgutov** [comment]
I don't think so.

But you can write a separate minor mode that would add commands like `indent-and-align-line` and `indent-and-align-region`, and remap the existing bindings to thme.

**Comment by ReneFroger** [comment]
I have not enough experience with Elisp to create such minor modes and it seems the commands `indent-and-align-line` and `indent-and-align-region` doesn't exists yet. So I think I'm not the right person to create such Lisp code. I would like to learn the basiscs of Lisp first. 

But thanks for the suggestion. Your help for js2-mode is really appreciated.

**Comment by dgutov** [comment]
No problem!
