### ISSUE TITLE
const in for loops

### ISSUE THREAD

**Issue by aliem** [mooz/js2-mode#270]
Since `const` and `let` variables defined inside `for` loops are re-defined for each iteration in the block scope it should be allowed.

```
// `i` is re-defined (not modified) on each loop step.
for (let i in [1,2,3]) {  /*error `i` is never modified, use `const` instead.*/
    console.log(i);
}
```
from [eslint docs](http://eslint.org/docs/rules/prefer-const.html).

Currently there are a few errors thrown:

- `const` is a *syntax error*
- `i in` is a *missing ; after for-loop initializer*
- `[1,2,3]) {` is a *missing ) after for-loop control*

To be honest I haven't looked at the sources. I'll take a look now.

**Comment by dgutov** [comment]
Are you saying

```js
for (const i in [1,2,3]) {
    console.log(i);
}
```

is valid JavaScript? Which environment does it run in?

**Comment by aliem** [comment]
It runs on current stable node.js and V8, it's not working on stable firefox.

**Comment by dgutov** [comment]
> not working on stable firefox

Not in Development Edition either.

> Since the spec states that a const is destroyed after a block is executed it makes that code valid

Could you quote the spec, or link to an article, or something?
