### ISSUE TITLE
How to show mocha test names in imenu list.

### ISSUE THREAD

**Issue by zilongshanren** [mooz/js2-mode#274]
Suppose we have the following test:
```
describe("Tags", function() {
   describe("#parse()", function() {
       it("should parse long formed tags", function() {
        var args = ["--depth=4", "--hello=world"];
        var results = tags.parse(args);
        expect(results).to.have.a.property("depth", 4);
        expect(results).to.have.a.property("hello", "world");
      });
  });
});
```
I want to get imenu list like this:
```
describe / Tags
describe / #parse
it / should parse long formed tags
```
Any help would be appreciated, thanks.

**Comment by zilongshanren** [comment]
@redguardtoo  could you please help me? thanks.

**Comment by dgutov** [comment]
The appropriate IMenu settings should probably be applied by a corresponding minor mode, like `rspec-mode` does for Ruby/RSpec.

https://github.com/rejeep/mocha.el doesn't to that, though. (yet?)

**Comment by zilongshanren** [comment]
@dgutov  
Thanks, I will test it.

But is there any easy way to config `js2-imenu-extension-styles` to get this done?

**Comment by dgutov** [comment]
> js2-imenu-extension-styles

No such variable.

Just change `imenu-create-index-function` back to the default in `js2-mode-hook` and set `imenu-generic-expression` as appropriate for Mocha.

**Comment by zilongshanren** [comment]
@dgutov
How to change `imenu-create-index-function` back to the default ? 
Sorry, I'm a noob for js2-mode.

**Comment by zilongshanren** [comment]
@dgutov  
Is it `(setq imenu-create-index-function imenu-default-create-index-function)`?

**Comment by dgutov** [comment]
Pretty much.

**Comment by zilongshanren** [comment]
@dgutov  
Finally I got it to work, but this method will break the existing imenu feature..

**Comment by zilongshanren** [comment]
@dgutov 

Here is my settings:

```
(defun js2-imenu-make-index ()
(save-excursion
  ;; (setq imenu-generic-expression '((nil "describe\\(\"\\(.+\\)\"" 1)))
  (imenu--generic-function '((nil "\\s-*\\(describe\\|it\\|before\\|after\\)\(\"\\(.+\\)\",.*" 2)
                             ))))

 (add-hook 'js2-mode-hook
        (lambda ()
          (setq imenu-create-index-function 'js2-imenu-make-index)))
```

Does it mean I should add many imenu regex here to parse function for myself?

thanks.

**Comment by dgutov** [comment]
> Finally I got it to work, but this method will break the existing imenu feature..

Then only do that in test files. Right?

**Comment by zilongshanren** [comment]
By adding 

```
                                 ("Function" "function[ \t]+\\([a-zA-Z0-9_$.]+\\)[ \t]*(" 1)
                                 ("Function" "^[ \t]*\\([a-zA-Z0-9_$.]+\\)[ \t]*=[ \t]*function[ \t]*(" 1)

```

My problem was solved. Thanks for your help.

**Comment by zilongshanren** [comment]
@dgutov 
yes, only in the test file.

**Comment by blaenk** [comment]
I came up with a way to merge both the mocha definitions as well as the imenu index that js2-mode creates. I'm not sure if there's any problem with going about it this way, so I've love to hear from @dgutov if there's a problem here I'm overlooking. Perhaps, is the way I'm doing it increase the performance cost considerably?

Basically I wrap the function that js2 uses to construct the imenu index, capture its result, and concatenate to it the mocha expressions. The patterns seem a bit messy but I'm not sure if there's a better way.

@zilongshanren I added support for when you change `it(...)` to `it.only(...)` or `it.skip(...)`. Previously those tests wouldn't show up in the imenu. I also added support for the rest of the keywords.

``` elisp
(add-hook 'js2-mode-hook #'js2-imenu-extras-mode)

(defun my-js2-imenu-index-function ()
  (let* ((js2-imenu-index (js2-mode-create-imenu-index))
         (mocha-index
          (imenu--generic-function
           '(("After" "^\\s-*after\\(\.skip\\|\.only\\)?\\s-*([\"']\\(.+\\)[\"']\\s-*,.*" 2)
             ("AfterEach" "^\\s-*afterEach\\(\.skip\\|\.only\\)?\\s-*([\"']\\(.+\\)[\"']\\s-*,.*" 2)
             ("It" "^\\s-*it\\(\.skip\\|\.only\\)?\\s-*([\"']\\(.+\\)[\"']\\s-*,.*" 2)
             ("Context" "^\\s-*context\\(\.skip\\|\.only\\)?\\s-*([\"']\\(.+\\)[\"']\\s-*,.*" 2)
             ("BeforeEach" "^\\s-*beforeEach\\(\.skip\\|\.only\\)?\\s-*([\"']\\(.+\\)[\"']\\s-*,.*" 2)
             ("Before" "^\\s-*before\\(\.skip\\|\.only\\)?\\s-*([\"']\\(.+\\)[\"']\\s-*,.*" 2)
             ("Describe" "^\\s-*describe\\(\.skip\\|\.only\\)?\\s-*([\"']\\(.+\\)[\"']\\s-*,.*" 2)))))
    (-concat js2-imenu-index mocha-index)))

(defun my-js2-imenu-extras-hook ()
  (setq-local imenu-create-index-function #'my-js2-imenu-index-function))

(add-hook 'js2-imenu-extras-mode-hook #'my-js2-imenu-extras-hook)
```

See https://github.com/blaenk/dots/commit/7ff80e4

**Comment by dgutov** [comment]
@blaenk Yep, that should work okay.

**Comment by blaenk** [comment]
Oh yeah it works great, I was just wondering if perhaps I was going about it the wrong way or something.

Thanks!
