### ISSUE TITLE
add setImmediate and clearImmediate to js2-node-externs

### ISSUE THREAD

**Issue by jeffbski** [mooz/js2-mode#286]
add setImmediate and clearImmediate globals to js2-node-externs

These have been in Node.js for quite some time.

See them listed here: https://nodejs.org/api/timers.html  (I'm not sure why they are not listed in the globals page for node, but I guess because they are related to timers more closely). They are exposed as global functions.

**Comment by dgutov** [comment]
No problem.

**Comment by jeffbski** [comment]
Excellent, Thanks!
