### ISSUE TITLE
Anyway to default to trailing commas?

### ISSUE THREAD

**Issue by yanivtal** [mooz/js2-mode#298]
AirBnB's style guide for ES6 insists on trailing commas for object and array literals.
Ex
```
const obj = {
  key1: val1,
  key2: val2,
}
```
Is there any way to make that the default?

**Comment by dgutov** [comment]
What do you mean by "default"?

`js2-mode` doesn't type code for you.

**Comment by yanivtal** [comment]
Sorry I'm new to Emacs/Vim. When you do ```SPC m r e o``` to convert a single line object literal to multiline, what controls what the multiline variant looks like?

**Comment by dgutov** [comment]
Are you using Spacemacs?

Here's their support chat: https://gitter.im/syl20bnr/spacemacs

**Comment by yanivtal** [comment]
K wasn't sure who's domain that was. Thanks!
