### ISSUE TITLE
:: breaks syntax highlighting

### ISSUE THREAD

**Issue by jupl** [mooz/js2-mode#299]
I was playing around with some code that is Stage 0 compatible and noticed that at times when I have code that has `::` syntax highlighting breaks (colors do not change or at times it appears as just plaintext) and this error shows up.

```
Error running timer `js2-mode-idle-reparse': (error "js2-name-node-name a non-js2-name-node")
```

Some sample code that causes the break:

```js
const x = {}
x::y()
function y() {}
```

Sample code that doesn't cause breaking:

```js
const y = {
  x() {}
}
const f = ::x.y
f()
```

Given that it is experimental and at Stage 0 I understand if this is something that won't be fixed but I was wondering since for the time being I am using another editor that doesn't choke on syntax highlighting (Atom, Sublime Text, and Vim don't seem to have trouble with this code) and ideally would like to stay on Emacs. I don't care if `::` is highlighted or not.

**Comment by dgutov** [comment]
> I was playing around with some code that is Stage 0 compatible

I don't think that means anything, unless you name the specific ES7 proposal. But anyway, yes, we generally don't support Stage 0 proposals.

> I am using another editor that doesn't choke on syntax highlighting (Atom, Sublime Text, and Vim don't seem to have trouble with this code) and ideally would like to stay on Emacs.

You don't have to use `js2-mode`. If you're fine with the functionality provided by the editors mentioned above, why not try the "plain" `js-mode`? It's built-in since Emacs 23.2.

**Comment by jupl** [comment]
I'm currently using Spacemacs which has configurations set up with `js2-mode` for JS.

**Comment by dgutov** [comment]
> configurations set up with js2-mode for JS.

I'm sure that can be changed.
