### ISSUE TITLE
js2-line-break doesn't work for single-line comments

### ISSUE THREAD

**Issue by blaenk** [mooz/js2-mode#302]
When I'm typing a single-line comment and I run `M-x js2-line-break` or press `M-j` (which is bound to it), it does enter to the next line, but it doesn't make that next line a comment, like I expect from `M-j` in other language modes. Is this expected behavior, or am I supposed to configure something?

For what it's worth, I'm writing es6, but js2-mode is on and it otherwise seems to work very well. I'm just typing a regular single line `//` comment, nothing fancy, not even in a jsx file or anything.

**Comment by dgutov** [comment]
It's expected behavior, yes, but we might as well consider it a bug, since it differs from other major modes.

**Comment by dgutov** [comment]
We've actually tried to be more clever here, and only extended the "commented" block if the following line also starts with `//` already.

I've took that part out now, because inserting a new line without commenting it is easy (`C-j` or `RET`).

**Comment by blaenk** [comment]
You are awesome, it works. Thanks a bunch!
