### ISSUE TITLE
imenu and es6 class methods

### ISSUE THREAD

**Issue by blaenk** [mooz/js2-mode#303]
I'm not sure what the state of imenu is in this mode (or if there is another preferred similar tool?). It seems to work pretty well even in es6 when I assign arrow functions to const variables, but I've noticed that it doesn't show any es6 class methods. Am I doing something wrong? Or we just don't have that functionality yet?

**Comment by dgutov** [comment]
Thanks for the report. It should work now, please test.

**Comment by blaenk** [comment]
Confirmed working! Thanks so much, I truly appreciate your attention and speed!
