### ISSUE TITLE
js2-parse-import Wrong type argument

### ISSUE THREAD

**Issue by cyocum** [mooz/js2-mode#305]
When attempting to use j2-mode I get the following error in the *Messages* buffer:

js2-parse-import: Wrong type argument: arrayp, ((("msg.syntax" nil) 8 1)).

I am using js2-mode version 20160109.148 installed from elpa.

**Comment by dgutov** [comment]
Hello!

Please provide a sample of JS code that triggers this error.

**Comment by cyocum** [comment]
This is embarrassing but I cannot seem to replicate this problem.  I will keep an eye out to see if it happens again and get a code snippet for it.
