### ISSUE TITLE
Code is valid in eslint but not valid in js2-mode

### ISSUE THREAD

**Issue by RusAlex** [mooz/js2-mode#309]
Please take a look what Im doing wrong. Im not yet so comfortable with emacs and elisp to inspect the issue deeper. 

```javascript
import React, { Component } from 'react';

class Foo extends Component
{

  onChangeSelect = () => {
  };

  render() {

    return (
    );
  }

}
```

code is valid in elisp but not valid in js2-mode with next error:
```emacs
Binding initializer not in destructuring assignment
```

**Comment by XeCycle** [comment]
`member = initializer` is ES7, not yet supported now.  https://github.com/mooz/js2-mode/pull/280#issuecomment-152515693

**Comment by RusAlex** [comment]
Is
