### ISSUE TITLE
JSX Indentation is flat

### ISSUE THREAD

**Issue by azer** [mooz/js2-mode#310]
Is it just me, or indentation is just flat or everyone ? For example;

```js
class Yo extends Component {
  render () {
    <div>
    <ul>
    <li>
    Hello
    </li>
    </ul>
     <div>
  }
}
```

Do I have a bad config, or j2-mode doesn't support indentation for JSX yet ?

**Comment by azer** [comment]
Closing this, the whole time I wasn't aware of `js2-jsx-mode`. Why don't you document it somewhere users can notice ?

**Comment by dgutov** [comment]
@azer It's in NEWS *and* in the header commentary. Where were you looking?

**Comment by azer** [comment]
@dgutov I was looking at the readme, isn't things should be documented in readme ?

**Comment by dgutov** [comment]
Depends on the project, I suppose. Our usage instructions and "new stuff" are in different files.

**Comment by azer** [comment]
how about mentioning usage instructions on JSX ?
