### ISSUE TITLE
Supporting "..." syntax

### ISSUE THREAD

**Issue by azer** [mooz/js2-mode#312]
Hi,

Does js2-mode support "..." syntax ? Is there a flag for enabling it ?

Info: https://github.com/lukehoban/es6features#default--rest--spread

**Comment by dgutov** [comment]
It does. Why do you have to ask? Can't you just try it?

**Comment by azer** [comment]
@dgutov I did try and got syntax, then opened this issue.

![](https://cldup.com/0aotZqyT3T.png)

**Comment by dgutov** [comment]
You didn't try any of the examples at your URL, did you?

**Comment by dgutov** [comment]
The code at the screenshot is not ES6. See #248.

**Comment by azer** [comment]
@dgutov sorry for pasting wrong link

**Comment by istinspring** [comment]
<Carousel {...this.props.propertyDetails.data} />

it's widely used in reactJS w/o any alternative.
