### ISSUE TITLE
Required feature `js` was not provided

### ISSUE THREAD

**Issue by AnuragRamdasan** [mooz/js2-mode#316]
Trying to get emacs to work right on osx el capitan.

I tried installing both 24.5 and 25.1 on osx but trying to get js2 working causes trouble giving the above error.

I understand that js is supposed to be a built-in in emacs and it seems to be built-in to my version too.
<img width="749" alt="screen shot 2016-02-28 at 1 14 58 am" src="https://cloud.githubusercontent.com/assets/1795026/13374935/70d248ec-ddb8-11e5-8670-293979417279.png">

The error is on this line https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L96 and I can reproduce it very well. Is this an issue with emacs maybe? Also is there any known workaround?

**Comment by dgutov** [comment]
You probably have a broken `js.el` lying around somewhere.

**Comment by AnuragRamdasan** [comment]
It is weird actually. The js.el from the js.el.gz in the emacs installation does provide js in the source.
I put it next to my init.el and did a load-file and it worked.

I still need to figure out how to get it work without me adding the js.el file but definitely not an issue with js2-mode.
