### ISSUE TITLE
Lisp nesting exceeds `max-lisp-eval-depth'

### ISSUE THREAD

**Issue by tpanum** [mooz/js2-mode#318]
I installed the recent version (`20160305.452`) on Emacs 24.5.1.

When I try to enable js2-mode I receive the following error: Lisp nesting exceeds `max-lisp-eval-depth'

I've tried to recompile `js2-mode` as suggested in other issues, and the issue still occur. I've tried increasing my `max-lisp-eval-depth`, and my emacs end up crashing.

**Comment by dgutov** [comment]
Have you tried reinstalling it?

**Comment by tpanum** [comment]
I tried that many times, but no luck :-(

**Comment by tpanum** [comment]
I apparently had a hook that loaded js2-mode (despite not being installed), that fucked up the posterior installation of js2-mode.
