### ISSUE TITLE
ES6 bind operator breaks syntax highlighting in spacemac's react-mode

### ISSUE THREAD

**Issue by stockninja** [mooz/js2-mode#320]
I just started using Emacs (Spacemacs) for first time a few days ago so I apologize if I'm reporting this bug to the wrong party, or if it doesn't contain enough information to be useful!

My syntax highlighting breaks in Spacemac's react-mode (https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bframeworks/react) when I use the ES6 bind operator (https://babeljs.io/blog/2015/05/14/function-bind). 

https://files.gitter.im/syl20bnr/spacemacs/5gxH/blob
https://files.gitter.im/syl20bnr/spacemacs/qUWQ/blob

I brought this up on the Spacemacs' Gitter channel and they suggested that I report this bug to js2-mode. The highlighting is still incorrect if there is only one colon on the third line of the screenshots above.

My dotspacemacs/user-config:
```
    vi-tilde-fringe-mode nil
    neo-theme "nerd"
    flycheck-checkers '(javascript-eslint)
    flycheck-eslintrc "~/code/karmic/.eslintrc"
    flycheck-javascript-eslint-executable "~/code/karmic/node_modules/.bin/eslint"
    flycheck-disabled-checkers (append flycheck-disabled-checkers '(javascript-jshint))
    dotspacemacs-fullnscreen-at-startup t)
```

My emacs version: GNU Emacs 24.5.1 (x86_64-apple-darwin15.3.0, Carbon Version 157 AppKit 1404.34)

Hope this help!

**Comment by dgutov** [comment]
Bind operator is not ES6, and it doesn't look like it'll make it to ES7 either: https://github.com/zenparsing/es-function-bind/issues/24#issuecomment-141102543

**Comment by dgutov** [comment]
Even the page at your second URL says it's highly experimental. So we don't support it, and I wouldn't review patches that add it until it's really on the agenda of an upcoming JS version.
