### ISSUE TITLE
How to auto insert "*" in the block comments when we press enter?

### ISSUE THREAD

**Issue by zhengdao** [mooz/js2-mode#321]

**Comment by XeCycle** [comment]
I would suppose M-j to do that, but currently it seems to insert "/*".

**Comment by dgutov** [comment]
> I would suppose M-j to do that, but currently it seems to insert "/*".

Works as expected here. You seem to describe the problem in `js-mode`.

Otherwise:

* What's the `M-j` bound to? (Try `C-h k`).
* What are the buffer contents that trigger this problem?

**Comment by XeCycle** [comment]
@dgutov sorry my bad, had a line `(define-key js2-mode-map (kbd "M-j") nil)` in my config.  Yes the default binding does that fine.

**Comment by dgutov** [comment]
Great!

@zhengdao Please use that. You can also bind `RET` to `js2-line-break`.

**Comment by zhengdao** [comment]
Perfect! Thanks everyone.
