### ISSUE TITLE
unexpected indentation --arrays and negative numbers

### ISSUE THREAD

**Issue by iambumblehead** [mooz/js2-mode#322]
```javascript
// expected indentation
var expectedarr = [
  1, 2, 3,
  4, 5, 6
];

// unexpected indentation at `-4`
var unexpectedarr = [
  1, 2, 3,
    -4, 5, 6
];
```

**Comment by iambumblehead** [comment]
this affects people working with matrix code [as seen here](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Creating_3D_objects_using_WebGL)

**Comment by dgutov** [comment]
Thanks for the report. Should be fixed now here and in `js-mode`.
