### ISSUE TITLE
jsx syntax highlighting: what's right move?

### ISSUE THREAD

**Issue by Trevoke** [mooz/js2-mode#330]
Js2-jsx-mode supports jsx files, which is fantastic. What is the right move to handle syntax highlighting?

PHP, for instance, recommends a multi-mode major mode such as web-mode for its files. Is that going in the right direction? multi-mode with something like js2-mode and jsx-mode ?

**Comment by dgutov** [comment]
Using a multi-major-mod solution seems like an overkill.

See the last comments in https://github.com/mooz/js2-mode/issues/140.

**Comment by Trevoke** [comment]
I see, thanks. This is currently beyond my elisp skills/grokking, but it might be a good reason to boost them... :)
