### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by bolivier** [mooz/js2-mode#331]
I often find myself editing js files that have the global declaration at the top with the format `/* global ...` with a space before global.  Currently js2-mode doesn't recognize this and considers the variables in the global declaration to be undefined.  

The standards I read use `/*global ...`, but it doesn't seem harmful to me to support both variations.

**Comment by dgutov** [comment]
IIRC JSHint doesn't support that format (see e.g. #122). Which tool do?

**Comment by bolivier** [comment]
The [eslint docs](http://eslint.org/docs/user-guide/configuring#specifying-globals) use `/* global ` like that.

**Comment by dgutov** [comment]
Fixed now.
