### ISSUE TITLE
ES6 "three dots" marked as a syntax error

### ISSUE THREAD

**Issue by Trevoke** [mooz/js2-mode#334]
```js
...foo
```

This is marked as a "syntax error". It is valid ES6, isn't it? Why is it marked as a syntax error?

**Comment by dgutov** [comment]
> It is valid ES6, isn't it?

Why would you think that? Anyway, please search the issue tracker.

**Comment by Trevoke** [comment]
I would think that because it's called the `spread operator` according to Mozilla: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference  

It's also used various times in ecma-262 document for 6.0 : http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-arrayaccumulation

**Comment by dgutov** [comment]
In ES6, it's not valid outside of function arguments and array literals.
