### ISSUE TITLE
Having both file name suffix associations with .js & .jsx always use js2-jsx-mode as default

### ISSUE THREAD

**Issue by yamafaktory** [mooz/js2-mode#337]
Hi,

I am really happy with the **js2-jsx-mode** but having the following Emacs settings leads to the fact that all files (`.js` or .`jsx`) are always associated to `js2-jsx-mode` instead of being dispatched as expected:

```elisp
(add-to-list 'auto-mode-alist '("\\.js\\'"   . js2-mode))
(add-to-list 'auto-mode-alist '("\\.jsx?\\'" . js2-jsx-mode))
```

**Comment by dgutov** [comment]
If you don't want this, remove the question mark.

**Comment by yamafaktory** [comment]
I've also tried it before but it leads to same behavior.

**Comment by yamafaktory** [comment]
The thing is that I am also using https://github.com/ankurdave/color-identifiers-mode/blob/master/color-identifiers-mode.el#L187 which should be working fine with .jsx files but the colors are missing. That's why I want .js files to be associated to **js2-mode** not **js2-jsx-mode**.

**Comment by dgutov** [comment]
> I've also tried it before

Have you tried restarting Emacs after that change?

**Comment by yamafaktory** [comment]
Ok, I was using `eval-buffer` but restarting did it, thanks (I thought I've already tried to restart before...)!

**Comment by dgutov** [comment]
Cool.
