### ISSUE TITLE
(n00b) Turn off message for trailing commas

### ISSUE THREAD

**Issue by gigavinyl** [mooz/js2-mode#338]
How do I turn off the message for trailing commas (`Trailing comma is not supported in some browsers`)?

**Comment by dgutov** [comment]
You customize `js2-strict-trailing-comma-warning`.

**Comment by jappeace** [comment]
Since this shows up as a google result now I'll record it properly for noobs like me. Add this line to your emacs config:

    (setq-default js2-strict-trailing-comma-warning nil)

**Comment by adius** [comment]
This should disabled per default!

**Comment by dgutov** [comment]
OK, the default is now changed.
