### ISSUE TITLE
Set Indent Width

### ISSUE THREAD

**Issue by gigavinyl** [mooz/js2-mode#339]
For some reason, I cannot for the life of me figure out how to set the indent width of this package to 2 spaces. The part of my `~/.spacemacs` config pertaining to tab widths is:
```emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2)
  (setq indent-line-function 'insert-tab)
  (setq-default js2-tab-width 2)
  (setq indent-line-function 'insert-tab)
  (setq-default js2-basic-offset 2)
```
and the package aggressive-indent-mode still insists upon indenting the line 2 tab's widths (in spaces).
UPDATE: I'm not *entirely* sure that the package that is improperly interacting with js2-mode is aggressive-indent-mode, but it makes the most sense...

**Comment by dgutov** [comment]
What if you remove everything but the first and the last line, and try again?

**Comment by gigavinyl** [comment]
@dgutov Ahhhh that worked thanks. :) For more system-wide config though, I added one line to your suggestion:
```emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq-default js2-basic-offset 2)
```
