### ISSUE TITLE
Syntax error for `yield*` in generator functions defined via new es6 method syntax

### ISSUE THREAD

**Issue by dpathakj** [mooz/js2-mode#340]
In the most recent js2-mode version available in melpa (`js2-mode-20160528.1706`), `yield*` is reported as a syntax error when it occurs within functions defined by the new es6 [method shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#Shorthand_generator_methods).

E.g.
```javascript
var o = {
    *gen() {
        yield* other_generator(); // syntax error on asterisk
    }
};
```

I've verified that this happens even with emacs -Q, just loading up js2-mode. I'm running emacs 24.5.1.

Here's a more comprehensive (though probably not exhaustive) look at what works and what doesn't.

```javascript
'use strict';

// this function is parsed fine
function* standalone_generator() {
    yield 1;
    yield 2;
}

// this works too; note that it uses yield*
function* standalone_generator_2() {
    yield* standalone_generator();
}

var o = {
    gen: function* () {
        yield* standalone_generator_2(); // this is parsed correctly
    },

    *gen2() {
        yield* standalone_generator_2(); // syntax error at asterisk
    }
};

// demonstrate that gen1 and gen2 are both valid
for (let i of o.gen()) {
    console.log(i); // prints 1 and 2
}

for (let i of o.gen2()) {
    console.log(i); // prints 1 and 2
}
```

**Comment by dgutov** [comment]
Thanks for the report, it should work now.
