### ISSUE TITLE
 Exponentiation operator

### ISSUE THREAD

**Issue by rahiel** [mooz/js2-mode#344]
The exponentiation operator will be in [ECMAscript 2017](https://tc39.github.io/ecma262/#sec-exp-operator), it is in [Firefox Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1243858) and it can already be used now with the [Babel transpiler](https://babeljs.io/docs/plugins/transform-exponentiation-operator/), from those docs:

```javascript
// x ** y

let squared = 2 ** 2;
// same as: 2 * 2

let cubed = 2 ** 3;
// same as: 2 * 2 * 2

// x **= y

let a = 2;
a **= 2;
// same as: a = a * a;

let b = 3;
b **= 3;
// same as: b = b * b * b;
```
js2-mode currently gives a `Parsing error`.

**Comment by dgutov** [comment]
This part looks like a pain:

> In JavaScript, it is impossible to write an ambiguous exponentiation expression, i.e. you cannot put a unary operator (+/-/~/!/delete/void/typeof) immediately before the base number.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Exponentiation_

Do you know if that's just because exponentiation is still at the proposal stage?

**Comment by rahiel** [comment]
It is a pain, but I think that's intended. The proposal is already at stage 4: [finished](https://github.com/tc39/proposals/blob/master/finished-proposals.md). In Chromium nightly build I get:
```javascript
2 ** 2
4

-2 ** 2
VM97:1 Uncaught SyntaxError: Unexpected token **

(-2) ** 2
4
```
In current Firefox nightly: `-2 ** 2` returns `4`, [that firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1243858) is about also raising a syntax error for `-2 ** 2`.

**Comment by dgutov** [comment]
All right, I've hacked up a solution, please try it out.

Hopefully, someone else will come along later and implement the handling of precedence properly.

**Comment by dgutov** [comment]
Here's something to that potential person to consider:

if `ExponentiationExpression` can be `UpdateExpression[?Yield]**ExponentiationExpression[?Yield]`, and `UpdateExpression` can be `++UnaryExpression[?Yield]`, does that mean that `++ -2 ** 3` is allowed?

**Comment by rahiel** [comment]
> All right, I've hacked up a solution, please try it out.

Thanks. It now does not give an error  for `var a = 2 ** 3`, but it does give an `missing ; before statement` error for:
```javascript
var c = 2 * 3 ** 4;
```

**Comment by dgutov** [comment]
@rahiel Thanks, it should work now.

**Comment by rahiel** [comment]
Thanks @dgutov, everything is working fine now :smile:.
