### ISSUE TITLE
Failing test on Emacs 25/Mac OS

### ISSUE THREAD

**Issue by dunn** [mooz/js2-mode#346]
Mac OS 10.11.5,
```
🌲  emacs --version
GNU Emacs 25.0.95.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
Running `make test` fails on `js2-parse-export-bindings`: https://gist.github.com/dunn/e40704b01d0e5ddb2b998d797314f386

Let me know if there's any other information you need!

**Comment by dgutov** [comment]
> Variable binding depth exceeds max-specpdl-size

That looks weird. Try deleting the `*.elc` files/recompiling/reinstalling.

**Comment by dunn** [comment]
Running `make clean` first doesn't help; is that what you meant?

**Comment by dgutov** [comment]
I guess.

What's your value of `max-specpdl-size`?

**Comment by dunn** [comment]
1300

**Comment by dgutov** [comment]
Same here. Hmm, I don't have any further ideas at the moment.

Maybe update your Emacs snapshot and try again.

**Comment by dunn** [comment]
Tried the latest from the `emacs-25` branch with the same result :/

Thanks for the quick reply though!

**Comment by dgutov** [comment]
What if you run the tests inside an interactive Emacs session? To do that, you visit `test/parser.el`, `M-x eval-buffer` and `M-x ert`.

**Comment by dunn** [comment]
Same thing.

**Comment by dgutov** [comment]
What if you raise `max-specpdl-size` to `1301`? Or higher?

**Comment by dunn** [comment]
Bizarrely, the tests pass when run with `-Q` rather than `-q --no-site-file`.
```diff
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 7777a67..b181ed8 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@
 EMACS = emacs

 # Compile with noninteractive and relatively clean environment.
-BATCHFLAGS = -batch -q --no-site-file
+BATCHFLAGS = -batch -Q

 SRCS = js2-mode.el js2-imenu-extras.el
```
I thought they were equivalent?

**Comment by dgutov** [comment]
Apparently not:

```
--quick, -Q                 equivalent to:
                              -q --no-site-file --no-site-lisp --no-splash
                              --no-x-resources
```

You might want to take a look at what files you have in `site-lisp`.

**Comment by dunn** [comment]
Well, I probably have an older version of js2-mode; maybe they interfere with each other?

**Comment by dgutov** [comment]
That's entirely possible.

**Comment by dunn** [comment]
Should I go ahead and submit a PR to make that change to the Makefile?

**Comment by dgutov** [comment]
Sure.
