### ISSUE TITLE
newline-and-indent is slow when cursor is at certain point

### ISSUE THREAD

**Issue by zilongshanren** [mooz/js2-mode#350]
```js
var obj = {
    attr1 : function() {
        
    },|(the cursor is here)
    attr2 : function() {
        
    }
};

```

When I call `RET` key, the command `newline-and-indent` will execute for a long time, I use `profiler-start` to profile this behavior and I found that `js2-parse-primary-expr` takes a lot time to execute which will cause laggy.

How could I disable the `js2-parse-primary-expr` execution when I press RET key here? Thanks.

Update: if I delete the comma before the cursor, and then the RET key will run smooth... weird

![image](https://cloud.githubusercontent.com/assets/785541/16579504/91e7f17e-42d2-11e6-8914-bfc0324bdf77.png)

**Comment by zilongshanren** [comment]
It seems that js2-mode will re-parse the whole js buffer when the `newline-and-indent` command is issued... I'm trying to write a customize indent function to get ride of this  behavior.

**Comment by dgutov** [comment]
Take a look at #56.

**Comment by zilongshanren** [comment]
@dgutov  thanks, it works.
