### ISSUE TITLE
Doc string quoting patch for Emacs 25 and later

### ISSUE THREAD

**Issue by eggert** [mooz/js2-mode#352]
Following up to [a recent comment on Emacs-devel](http://lists.gnu.org/archive/html/emacs-devel/2016-07/msg00297.html) please see the patch below. (I tried to attach it but GitHub won't let me.)

```
From 0d2a9d4cd65c7d6d72a9e6a3928340b3e29fedcb Mon Sep 17 00:00:00 2001
From: Paul Eggert <eggert@cs.ucla.edu>
Date: Thu, 7 Jul 2016 15:28:10 +0200
Subject: [PATCH] js2-jsx-mode: port docstring to Emacs 25 and later

---
 js2-mode.el |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/js2-mode.el b/js2-mode.el
index 5769f2f..7866a0a 100644
--- a/js2-mode.el
+++ b/js2-mode.el
@@ -11620,7 +11620,7 @@ variables (`sgml-basic-offset' et al) locally, like so:
 
   (defun set-jsx-indentation ()
     (setq-local sgml-basic-offset js2-basic-offset))
-  (add-hook 'js2-jsx-mode-hook #'set-jsx-indentation)"
+  (add-hook \\='js2-jsx-mode-hook #\\='set-jsx-indentation)"
   (set (make-local-variable 'indent-line-function) #'js2-jsx-indent-line))
 
 (defun js2-mode-exit ()
-- 
1.7.9.5

```

**Comment by dgutov** [comment]
Hi Paul,

Could you make it into a pull request?

Alternatively, feel free to commit this change to the ELPA repository, and I'll get it merged sometime.

**Comment by eggert** [comment]
Sorry, I don't know offhand how to turn it into a pull request on GitHub, nor do I have access to the ELPA repository that I know of. (My excuse is that I have a verrry slooow laptop, almost as slow as RMS's, and GitHub's JavaScript code is almost more than it can handle; also, my Internet connection is a bit spotty right now.) You should be able to cut and paste the patch into a file F.txt, and then type `git am F.txt`.

**Comment by kaushalmodi** [comment]
Here's the PR: https://github.com/mooz/js2-mode/pull/353

**Comment by dgutov** [comment]
@eggert 

Everybody who has access to Emacs's repository has access to ELPA, it's here: http://git.savannah.gnu.org/cgit/emacs/elpa.git

Also see its mention here: https://savannah.gnu.org/git/?group=emacs

Anyway, Kaushal's PR should suffice.
