### ISSUE TITLE
option to ignore keyword width in variable declaration

### ISSUE THREAD

**Issue by andreineculau** [mooz/js2-mode#354]
as per https://github.com/mooz/js2-mode/blob/0cda39255827f283e7578cd469ae42daad9556a2/tests/indent.el#L80

```
const foo = 5,
_____ bar = 5;
```

but it seems impossible to just stick to the indentation level, and disregard the length of the keyword e.g. with 2 spaces

```
const foo = 5,
_ bar = 5;
```

**Comment by dgutov** [comment]
Please file this feature request against `js-mode` in Emacs. We've switched to using its indentation code.
