### ISSUE TITLE
Emacs 25/Macintosh double click to select word fails

### ISSUE THREAD

**Issue by hwinkler** [mooz/js2-mode#356]
Steps to reproduce:

1. Enter js2-mode on a javascript file. 
2. Double click any word (token) in the text

Expected: Word highlights and becomes selected
Actual: On second click, word briefly highlights, but immediately unhighlights and remains unselected.

tested on
js2-mode 20160623(gnu)  and 20160707.723(melpa)
OSX 10.11.6 

I've tried both the regular Emacs bulld for Mac, as well as Aquamacs:

Emacs (for Mac) 25.1 (9.0):
GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2016-07-24

Aquamacs 3.3dev
GNU Emacs 25.0.95.1 (x86_64-apple-darwin14.1.0, NS appkit-1344.72 Version 10.10.2 (Build 14C109))
 of 2016-07-25 on 7f3516c356c4defa49f90f39c2019b40ab496206

**Comment by hwinkler** [comment]
Just noting that this behavior begins with emacs 25. Earlier versions e.g. Aquamacs 3.2 based on Emacs 24, work properly.

**Comment by jlsutherland** [comment]
+1

**Comment by hwinkler** [comment]
Workaround: double-click word; leave mouse button pressed down on second click. While continuing to press, move mouse one or more pixels -- enough to leave the single word highlighted without extending the selection. Then release mouse. The word remains highlighted and is selected.

**Comment by ngn999** [comment]
+1
