### ISSUE TITLE
es7 class properties

### ISSUE THREAD

**Issue by dagda1** [mooz/js2-mode#359]
I am getting syntax highlighting errors for code that uses es7 class properties:

```
import React, { Component, PropTypes } from 'react';

export default class RContainer extends Component {
  static propTypes = {
    height: PropTypes.nubmber,
    width: PropTypes.number
  };
};
```

It looks like this in emacs

![es](https://cloud.githubusercontent.com/assets/118328/17461399/0eaff96c-5c83-11e6-9769-c0cbbcf72081.png)

I can see the following message in `*messages*`

> Binding initializer not in destructuring assignment

I can see this [error](https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L1742) in the js2-mode source.

Can this be recognised as a valid construct?

The code passes eslint

**Comment by XeCycle** [comment]
okay that line blames to me :)
back [then](https://github.com/mooz/js2-mode/pull/280) we decided not to add ES7 features.  if we want the reverse now, I'm happy to help.

**Comment by dgutov** [comment]
>  if we want the reverse now, I'm happy to help

Apparently it's stage 2 now. I wouldn't mind adding support for it.

**Comment by CrackedP0t** [comment]
Babel stage 2 has it and it's a very useful feature, so I think it should be in js2-mode.

**Comment by fxfactorial** [comment]
Would this also fix the syntax errors highlighting on plain public fields? ie: 

```javascript
class Foo {
   login = e => {

  }
// Also keep in mind this ability:

  bar = async e => {

  }
};
```

**Comment by formido** [comment]
I get the warning on the following:

``` javascript
class App extends React.Component {
  state = {
    loading: true,
    user: null,

    // Model
    employees: [],
  }
```
> Binding initializer not in destructuring assignment

Is that still the expected behavior? I just upgraded to the latest package on MELPA.

**Comment by dgutov** [comment]
All of the examples here seem to have been fixed by now.
