### ISSUE TITLE
incompatibility with hs-minor-mode 

### ISSUE THREAD

**Issue by vidyu** [mooz/js2-mode#361]
Hi! Does anybody have a problem with _hs-minor-mode_ . When I try to use *hs-hide-level* inside js __class__ my emacs hangs up. I have no such problem when i use the 20150909 version.

**Comment by dgutov** [comment]
I can see it, thanks for the report.

**Comment by vidyu** [comment]
You're welcome :)

**Comment by dgutov** [comment]
Please try the new version.

**Comment by vidyu** [comment]
Seems to work as expected. Super!
