### ISSUE TITLE
Invalid "yield expression must be parenthesized." warning

### ISSUE THREAD

**Issue by bellbind** [mooz/js2-mode#362]
In ECMA262, `yield` expression is one of assignment expressions.
- http://www.ecma-international.org/ecma-262/6.0/#sec-assignment-operators

Parenthesizing `yield` is required only at primary expression positions.

For example:

``` js
// wrapped paren is not required: but warned "yield expression must be parenthesized."
funcCall(yield v);
return yield v;

// wrapped paren is required ("syntax error" displayed)
a = 10 + (yield v); 
typeof (yield v);

// wrapped paren is not required (no warning)
a += yield v;
```

**Comment by XeCycle** [comment]
Relative lines are said to come from very early days, when yield expression was probably some implementation extension defined differently.  IMO it should be safe to simply drop this check as of now.

**Comment by dgutov** [comment]
@XeCycle What's a relative line?

You're probably right about dropping the check in `js2-parse-argument-list`, but that only seems to help with the first example. The second one still gives "syntax error".

**Comment by dgutov** [comment]
Seems fixed by that PR from 2017.
