### ISSUE TITLE
Error when installing from ELPA/MELPA

### ISSUE THREAD

**Issue by hydandata** [mooz/js2-mode#364]
Debugger entered--Lisp error: (error "js2-mode.el:0:0: error: scan-error: (Unbalanced parentheses 245847 502886)")

Emacs Mac Port 25 RC1 on OS X

**Comment by dgutov** [comment]
> from ELPA/MELPA

Where from, exactly? Which version are you trying to install?

The current master looks fine here.

**Comment by hydandata** [comment]
Must be something in my configuration messing with it. Just tried again with emacs -q and only MELPA setup and I am not getting the error.
