### ISSUE TITLE
Unterminated regex literals are not marked as strings

### ISSUE THREAD

**Issue by davidshepherd7** [mooz/js2-mode#368]
In js2-mode if I write

    let x = /foo|

(with `|` representing point) and run `syntax-ppss` then it tells me that point is not inside a string. This is inconsistent with `js-mode`'s regex literals and with the usual emacs handling of unterminated string literals.

Is this the intended behavior?

It's causing me problems [here](https://github.com/davidshepherd7/electric-operator/issues/45).

**Comment by dgutov** [comment]
It's working as intended, but indeed, we'll be better served by behaving more like `js-mode`.

**Comment by dgutov** [comment]
Please test.

**Comment by davidshepherd7** [comment]
It works when I test it manually, but not inside my automated tests which is odd.

 I'm probably loading something wrongly so I'll dig into it when I get a chance.

Thanks for the quick response :+1:

**Comment by davidshepherd7** [comment]
If you're interested: the problem with my tests was that I didn't wait for the parser to run again (I hadn't realised it didn't run continuously).

Thanks again.

**Comment by dgutov** [comment]
Thanks, I thought it might be something like that.

No need to wait, you can call `js2-reparse` directly.
