### ISSUE TITLE
Much lag for large files (>4000 lines)

### ISSUE THREAD

**Issue by molgrum** [mooz/js2-mode#369]
As the title says, tested on Windows 10. It is very tedious to work because every character I type has 1-2 second delay to it. If more info is needed I can do profiling.

**Comment by srt19170** [comment]
Ditto.

**Comment by dgutov** [comment]
Please try:

```el
(setq blink-matching-paren nil)
```

**Comment by srt19170** [comment]
That seems to have fixed the problem for me (or at least so far!)  Thanks!

**Comment by dgutov** [comment]
Just how large are the files we are talking about?

**Comment by srt19170** [comment]
The one I ran the profile on is 6000 lines.  I can provide it to you (offline) for testing if that would help.

**Comment by dgutov** [comment]
Before we do that, have you tried reproducing the problem starting with `emacs -Q`?

The scenario would look something like this:

```
emacs -Q -L ~/.emacs.d/elpa/js2-mode-???/
(require 'js2-mode)
find-file ....
M-x js2-mode
(your steps here)
```

**Comment by dgutov** [comment]
All right, please send me the file. My email is at the top of `js2-mode.el`.

**Comment by dgutov** [comment]
Thanks, I see it there. Seeing as the reproduction scenario involves typing characters from `electric-indent-chars`, `electric-indent-mode` (on by default) is involved.

Ultimately, it's a bug in `js--multi-line-declaration-indentation` caused by a faulty translation from `js2-mode` indentation code. You can apply this patch to your Emacs:

```diff
diff --git a/lisp/progmodes/js.el b/lisp/progmodes/js.el
index 6d995a0..0ba7aac 100644
--- a/lisp/progmodes/js.el
+++ b/lisp/progmodes/js.el
@@ -1851,7 +1851,8 @@ js--multi-line-declaration-indentation
   "Helper function for `js--proper-indentation'.
 Return the proper indentation of the current line if it belongs to a declaration
 statement spanning multiple lines; otherwise, return nil."
-  (let (at-opening-bracket)
+  (let (forward-sexp-function ; use Lisp version even in js2-mode
+        at-opening-bracket)
     (save-excursion
       (back-to-indentation)
       (when (not (looking-at js--declaration-keyword-re))
```

And I'll try to get it into the upcoming Emacs release (25.2).

**Comment by srt19170** [comment]
I'm not sure how I'm "supposed" to patch Emacs, but putting a fixed version of the function into my .emacs file seemed to work, because the hangup is now gone.

Thanks a bunch, Dmitri!  Really appreciate the effort!

**Comment by dgutov** [comment]
> I'm not sure how I'm "supposed" to patch Emacs

You apply the patch the sources, and rebuild. 😛 If Emacs was built by your distribution, it's harder, of course.

> putting a fixed version of the function into my .emacs file seemed to work

That works as well. And yet another option is to define an around-advice for this function, with a let-binding for the aforementioned variable.

You're welcome!

**Comment by dgutov** [comment]
> get it into the upcoming Emacs release (25.2)

And done.
