### ISSUE TITLE
Highlighting Template Strings

### ISSUE THREAD

**Issue by azer** [mooz/js2-mode#370]
Is there any plan to support highlighting HTML inside ES6 Template Strings? They are quite often used for HTML templates;

```js
function foo () {
  return html`<h1>hello world</h1>`
}
```

**Comment by dgutov** [comment]
This example works fine here.

**Comment by azer** [comment]
@dgutov sorry for being not clear enough. I meant to ask about highlighting HTML inside template strings.

**Comment by dgutov** [comment]
Ah, sorry. I don't think we will support it in `js2-mode` directly.

You might have some luck configuring it with e.g. [mmm-mode](https://github.com/purcell/mmm-mode), though.
