### ISSUE TITLE
Indentation bug

### ISSUE THREAD

**Issue by AttilaVM** [mooz/js2-mode#372]
I met a case when js2-mode makes wrong auto indentation, I wrote a self contained example:

```
let foo = [{

},
           {

           }];
```

It does the indentation right if I put the beginning bracket of the first object of the foo list into a new line:

```
let foo = [
    {

    },
    {

    }];
```

It is not big deal. I also use the second style (more readable), however when someone uses the first style it can be troublesome.

by the way js2-mode helps me lot in programming, thank you.

**Comment by dgutov** [comment]
Thanks for the report. Alas, this is an unfortunate collision of several pieces of indentation logic, all of them usually working well in other contexts. I don't know how to fix this best, or where such a fix would go.

Patch welcome (though it'll need to be against `js.el` in Emacs).

**Comment by AttilaVM** [comment]
Thank you. I guess the problem resides in _js--proper-indentation_ in js.el. Unfortunately I do not know Emacs Lisp in detph. However I'll try to come up with something.

**Comment by dgutov** [comment]
> the problem resides in js--proper-indentation

Yes, but it's the entry point for the whole indentation logic.
