### ISSUE TITLE
Newlines in global declaration

### ISSUE THREAD

**Issue by JulianKniephoff** [mooz/js2-mode#373]
Given the following code:

```javascript
foo.bar = 42;
```

Here, `foo` is correctly highlighted as undeclared variable. This is "fixed" for example by introducing a `global` declaration:

```javascript
/*global foo*/
foo.bar = 42;
```

However, what does not work for example is this:

```javascript
/*global
	foo
*/
foo.bar = 42;
```

Even though this style of `global`-comment is explicitly stated in the example example for that syntax in the [JSLint documentation](http://www.jslint.com/help.html).

Note that linebreaks in other parts of the declaration are fine, i.e. the following works:

```javascript
/*global foo,
	baz
*/
foo.bar = 42;
baz.qux = 23;
```

**Comment by dgutov** [comment]
Thanks for the report.
