### ISSUE TITLE
Regexp literals with the equals character confusing js2-mode

### ISSUE THREAD

**Issue by kzar** [mooz/js2-mode#376]
Hello, firstly thanks for this I use it every day and it's a joy to use. Anyway I've noticed a bug this afternoon with regexp literals. Take this example:

```
if (true) {
  let example = /=/;
}
```

js2-mode considers that the closing `}` does not match the opening `{` one.

If I change the regexp to be something else, for example `/a/` it works again.

**Comment by dgutov** [comment]
Thanks for the report.

**Comment by kzar** [comment]
Awesome, can confirm it's working correctly for me now. Thanks again :+1:
