### ISSUE TITLE
determine whether previous node is comment node

### ISSUE THREAD

**Issue by futurist** [mooz/js2-mode#383]
When have a normal node, e.g. an array element node, want to find whether there's some comment node before this element, I've tried but none of them worked, as below:
1. **js2-comment-node-p (pos)**

It accept **pos**, but only have the array element's pos.
1. **js2-node-find-child-before (pos, parent)**

Want to find the array element's previous node, but

> ﻿PARENT is any node supported by ‘js2-node-child-list’.

so the search failed for a `comment node`

Any solution for this in js2-mode? Thanks!

**Comment by dgutov** [comment]
Is the input value to the desired function a node, or a buffer position?

**Comment by futurist** [comment]
```lisp
(defun test-comment()
  (let ((node (js2-node-parent (js2-node-at-point)))
        (pos (point)))
    (js2-node-short-name (js2-node-find-child-before pos node))))
```

```js
var a = [
  1,
  //sdf
  2|,
  3
]
```

put your point onto **2**, and eval `(test-comment)`, the result always `js2-number-node`

**Comment by futurist** [comment]
**Another problem**

When tested with below code, emacs will die every time:

```lisp
(defun test-comment()
  (let ((node (js2-node-parent (js2-node-at-point)))
        (pos (point)))
    (js2-node-abs-pos (js2-node-find-child-before pos node))))
```

```js
/*
  Copyright @ Michael Yang
  License MIT
*/

// phantomjs module
var fs = require('fs')
var sys = require('system')
var helper = require('./helpers/helper.js')
var page = require('webpage').create()

var DEBUG = sys.env['DEBUG']
var debug = function (arg) {
  var args = [].slice.call(arguments)
  if (DEBUG) console.log.apply(console, args)
}

var a= [
  {
    a:1
    ,
    b:2
  }
  ,
  [
    2
    ,
    3
  ],
  //sdf
  4,
  5
]

var b=[
  1,
  //sdf
  2,   //<<============point position under 2
  3
]
```

**Comment by dgutov** [comment]
Hi!

Looking into it, the actual problem (in the example 1) is that comments are not part of the AST. Or rather, there is a list of comments attached to the AST root (which you can access with `js2-ast-root-comments`), but the comment node is not one of the children of the array node. To find the closes comment node, you can take that list and do a linear search on it. See `js2-comment-at-point` as one example.

Next, you could use the proposed `test-comment` function and find the closest non-comment node, to check whether the comment node is closer.

**Comment by dgutov** [comment]
> When tested with below code, emacs will die every time:

I see no crash on GNU/Linux either. An Emacs crash almost always means a bug in Emacs (or in the macOS port in this case, probably). You should report it. Since it's reproducible, it's even better, and you should be able to provide the necessary information without too much trouble.

**Comment by futurist** [comment]
Thanks for the info, I should loop through `js2-ast-root-comments` to find whether it's between 2 array elements.

But just wondering why all comments pushed into root? Is it convinient to make the AST as source order? e.g. embed it into some node lists, and let user test if it's comment node or not?

**Comment by dgutov** [comment]
This came from Rhino: http://manual.iderzheng.com/rhino/org/mozilla/javascript/ast/Comment.html

I can't find the exact justification, but it's probably to avoid surprises. For many nodes, the consumers expect to see only one of a few node types among their children. Further, comments may reside in places where no child nodes are expected (so there's no particular place to add them to).

**Comment by futurist** [comment]
I found below commit helpful when deal with the situation, which populate all comments between start and end point.

https://github.com/futurist/js2-mode/commit/7a5832285249788a80ed19ce4e20fb6c5723623c

Is it sensible to merge into `js2-mode`? If it's ok, I'll going to make a PR.

**Comment by dgutov** [comment]
Unfortunately, this patch is twice the limit for code contributions without assignment (so called "trivial" ones). Are you willing to sign the papers?

**Comment by futurist** [comment]
@dgutov Yes, I'm. How?

**Comment by dgutov** [comment]
Here are the instructions: http://orgmode.org/cgit.cgi/org-mode.git/plain/request-assign-future.txt

(The first answer should indeed be "Emacs").

**Comment by felipeochoa** [comment]
Would there be any harm in using `js2-scanned-comments` instead of `(js2-ast-root-comments ast)`? I do this check in `rjsx` relatively often and would love to just use the js2 builtin, but it's during parsing so the latter is not yet available.

**Comment by dgutov** [comment]
Maybe the function should take a list of comments as an argument.

**Comment by futurist** [comment]
Please check below commit:

https://github.com/futurist/js2-mode/commit/238e07ffde496659a6e39e4e8ef88bdd1c236b85

**Comment by dgutov** [comment]
@futurist It doesn't look like you've addressed the first two of my comments.

Aside from that, there's not much point in doing the "optional argument" thing. Let the consumer always pass the list of comments.

**Comment by futurist** [comment]
@dgutov Oh, sorry, previous link is not showing root diff, please see below:

https://github.com/mooz/js2-mode/compare/master...futurist:master

**Comment by dgutov** [comment]
@futurist Thanks. Looks good to me now.

**Comment by futurist** [comment]
@dgutov I've been signed the papers

![2016-12-29 06 45 17](https://cloud.githubusercontent.com/assets/159167/21533174/d8e6efc6-cd92-11e6-9039-19f49c702d91.png)
