### ISSUE TITLE
yield parsing issues in an object literal.

### ISSUE THREAD

**Issue by jordonbiondo** [mooz/js2-mode#388]
I am receiving syntax errors when using `yield` output as a value in an object literal.

The code is perfectly valid, but I'm getting an `undefined variable or function` error.

Code:
```
const thing = function* () {
    return {
        productCount: yield Product.count(),
        collectionCount: yield Collection.count(),
        userCount: yield User.count(),
        orderCount: yield Order.count()
    };
};
```

Screenshot for reference:

<img width="424" alt="screen shot 2016-11-04 at 10 57 38 am" src="https://cloud.githubusercontent.com/assets/1441728/20010337/13ec2eaa-a27e-11e6-86cb-fc44bbed1cdb.png">

I did see if the issue was resolved in master or if it resolved itself with the #366  changes but it did not, maybe @XeCycle will have a good understanding about how to resolve the issue.

**Comment by XeCycle** [comment]
Looks awfully like [a bug in esprima](https://github.com/jquery/esprima/issues/1262) I fixed earlier.  Looking at `js2-parse-return-or-yield`, seems we need a separate `js2-parse-yield` somehow, since they are quite different now.

**Comment by dgutov** [comment]
@XeCycle Seems so. Or maybe we just need to move the `js2-parse-expr` (with appropriate variation) inside the branches of the following `cond`.

Will you give it a try?
