### ISSUE TITLE
Can't change "font-lock-constant-face" foreground color

### ISSUE THREAD

**Issue by oles** [mooz/js2-mode#391]
Hello :)

Recently jumped from web-mode to js2-mode for better indentation with chained promises, and I stumbled upon an oddity. I tried to customize the faces, so that js2-mode looked just like the way web-mode did for me.

Everything went smoothly until I tried to change the orange `font-lock-constant-face`.

As usual, I moved my cursor over the text which face I wanted to change (in this case the "false" in `return false`), and typed `describe face`. As you'd expect, the current face is the default selection, which it appeared to be. I hit enter, and this greeted me:

![screenshot from 2016-11-24 14-12-28](https://cloud.githubusercontent.com/assets/7634050/20599895/0328a020-b251-11e6-9e59-7aff0b2f1ce7.png)
 
Supposedly the "false" in `return false` is the light-blue-ish color I want it to be, except that it is not... It is orange.

I thought it was just js2-mode doing something weird, so I tried to troubleshoot it by various means.
I've tried to change the theme and major modes willy nilly, but it always works as expected when not in js2-mode.

My last resorts had me trying out various `set face` for `js2-mode-hook`, trying to change all the orange faces I could find in `customize-face` "all faces", and lastly trying to search for `font-lock-constant-face` in js2-mode.el if there was anything obvious. 

It lead me nowhere, and gave me nothing to go on with. Thus I'm hoping some of you lovely folks have some input or suggestions for me, as I'm stumped.

**Comment by dgutov** [comment]
Hi!

> I've tried to change the theme and major modes willy nilly

Have you tried using the default theme, for instance?

> but it always works as expected when not in js2-mode.

It works well here with js2-mode (sorry I can't make a screenshot currently). And `font-lock-constant-face` is the face to customize.

If you move point to `false` and press `C-u C-x =`, what does the resulting buffer say at the end?

**Comment by oles** [comment]
> Have you tried using the default theme, for instance?
Tried that as well, but no dice.

Tried the nuclear method quick, and it seems like `(load-theme 'atom-one-dark t)` is the reason that this happens, even though the theme is not enabled.

Closing for now, as it seems like `js2-mode` is not to blame.

I'll post my solution here if I figure it out :)

**Comment by oles** [comment]
Indeed, atom-one-dark-theme is to blame for this. Hope I this didn't bother you too much.

The solution was to add `(setq atom-one-dark-theme-force-faces-for-mode nil)` to .emacs - as found inside atom-dark-one-theme.el:

```
(defvar atom-one-dark-theme-force-faces-for-mode t
  "If t, atom-one-dark-theme will use Face Remapping to alter the theme faces for
the current buffer based on its mode in an attempt to mimick the Atom One Dark
Theme from Atom.io as best as possible.
The reason this is required is because some modes (html-mode, jyaml-mode, ...)
do not provide the necessary faces to do theming without conflicting with other
modes.
Current modes, and their faces, impacted by this variable:
* js2-mode: font-lock-constant-face, font-lock-doc-face, font-lock-variable-name-face
")

;; Many modes in Emacs do not define their own faces and instead use standard Emacs faces when it comes to theming.
;; That being said, to have a real "Atom One Dark Theme" for Emacs, we need to work around this so that these themes look
;; as much like "Atom One Dark Theme" as possible.  This means using per-buffer faces via "Face Remapping":
;;
;;   http://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Remapping.html
;;
;; Of course, this might be confusing to some when in one mode they see keywords highlighted in one face and in another
;; mode they see a different face.  That being said, you can set the `atom-one-dark-theme-force-faces-for-mode` variable to
;; `nil` to disable this feature.

```

**Comment by dgutov** [comment]
Thanks for letting us know. :)
