### ISSUE TITLE
Error when parsing destructuring

### ISSUE THREAD

**Issue by davazp** [mooz/js2-mode#393]
If I visit a file with the file

```javascript
function f (x,y) {
  let [u,v] = [x,y];
}
```

js2-mode throws the following error:
```
Error running timer ‘js2-mode-idle-reparse’: (wrong-type-argument js2-name-node [cl-struct-js2-array-node 65 0 5 nil [cl-struct-js2-var-init-node 152 4 13 nil [cl-struct-js2-var-decl-node 121 0 17 nil [cl-struct-js2-expr-stmt-node 133 4 18 nil [cl-struct-js2-block-node 128 17 24 nil [cl-struct-js2-function-node 108 1 41 nil [cl-struct-js2-ast-root 135 1 42 nil nil (#6) ((f . [cl-struct-js2-symbol 108 "f" #6])) nil nil nil nil nil 0 nil nil 0 "js2-bug.js" nil nil nil nil] nil ((v . [cl-struct-js2-symbol 152 "v" [cl-struct-js2-name-node 39 3 1 nil #1 "v" nil]]) (u . [cl-struct-js2-symbol 152 "u" [cl-struct-js2-name-node 39 1 1 nil #1 "u" nil]]) (y . [cl-struct-js2-symbol 86 "y" [cl-struct-js2-name-node 39 14 1 nil #6 "y" nil]]) (x . [cl-struct-js2-symbol 86 "x" [cl-struct-js2-name-node 39 12 1 nil #6 "x" nil]])) [cl-struct-js2-ast-root 135 1 42 nil nil (#6) ((f . [cl-struct-js2-symbol 108 "f" #6])) nil nil nil nil nil 0 nil nil 0 "js2-bug.js" nil nil nil nil] nil nil nil nil 0 nil nil 0 FUNCTION FUNCTION_STATEMENT [cl-struct-js2-name-node 39 9 1 nil #6 "f" nil] ([cl-struct-js2-name-node 39 12 1 nil #6 "x" nil] [cl-struct-js2-name-node 39 14 1 nil #6 "y" nil]) nil #5 11 15 nil nil nil nil nil] (#4)] #3] (#2) 152] #1 [cl-struct-js2-array-node 65 8 5 nil #2 ([cl-struct-js2-name-node 39 1 1 nil #3 "x" nil] [cl-struct-js2-name-node 39 3 1 nil #3 "y" nil])]] ([cl-struct-js2-name-node 39 1 1 nil #1 "u" nil] [cl-struct-js2-name-node 39 3 1 nil #1 "v" nil])])
```

For larger files it also makes Emacs very very slow.

I am using `js2-mode` "1.8.5" and GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.31) of 2016-10-06.

**Comment by dgutov** [comment]
Works fine in the current master.

If you `M-x describe-package RET js2-mode RET`, what value is printed beside the "Version" header?

**Comment by davazp** [comment]
`Version: 20161117.1621`

I narrowed down the issue a bit. It seems to be in the `js2-highlight-unused-variables-mode` actually. If I include this part of my configuration, then it will fail:

```emacs-lisp
(add-hook 'js2-mode-hook 'js2-highlight-unused-variables-mode)
```

**Comment by dgutov** [comment]
Now I see it, thanks.

@lelit Could you look into that?

**Comment by lelit** [comment]
I will try to understand the issue.

**Comment by lelit** [comment]
The culprit seems to be `js2--add-or-update-symbol` that assumes the assignment target is always a symbol.

The following quick&dirty patch apparently fixes the problem, but I'd like a) do more tests and b) have some feedback on whether the strategy is good enough (I mean, is the new `js2--add-or-update-symbol-or-array` the right way?)

```
diff --git a/js2-mode.el b/js2-mode.el
index 12a5c6a..b30fff3 100644
--- a/js2-mode.el
+++ b/js2-mode.el
@@ -7136,6 +7136,12 @@ in the cdr of the entry.
             (setq used nil))
           (puthash sym (cons inition (if used (list symbol))) vars))))))
 
+(defun js2--add-or-update-symbol-or-array (symbol inition used vars)
+  (if (js2-array-node-p symbol)
+      (cl-loop for v in (js2-array-node-elems symbol)
+              do (js2--add-or-update-symbol v inition used vars))
+    (js2--add-or-update-symbol symbol inition used vars)))
+
 (defun js2--classify-variables ()
   "Collect and classify variables declared or used within js2-mode-ast.
 Traverse the whole ast tree returning a summary of the variables
@@ -7168,19 +7174,19 @@ are ignored."
                                     (mapcar #'js2-var-init-node-target
                                             (js2-var-decl-node-kids
                                              (js2-for-in-node-iterator grandparent)))))))
-                 (js2--add-or-update-symbol target inited nil vars)))))
+                 (js2--add-or-update-symbol-or-array target inited nil vars)))))
 
           ((js2-assign-node-p node)
            ;; take note about assignments
            (let ((left (js2-assign-node-left node)))
              (when (js2-name-node-p left)
-               (js2--add-or-update-symbol left t nil vars))))
+               (js2--add-or-update-symbol-or-array left t nil vars))))
 
           ((js2-prop-get-node-p node)
            ;; handle x.y.z nodes, considering only x
            (let ((left (js2-prop-get-node-left node)))
              (when (js2-name-node-p left)
-               (js2--add-or-update-symbol left nil t vars))))
+               (js2--add-or-update-symbol-or-array left nil t vars))))
 
           ((js2-name-node-p node)
            ;; take note about used variables
@@ -7210,7 +7216,7 @@ are ignored."
                        (when grandparent
                          (setq used (js2-return-node-p grandparent)))))
 
-                   (js2--add-or-update-symbol node inited used vars))))))))
+                   (js2--add-or-update-symbol-or-array node inited used vars))))))))
        t))
     vars))
 
diff --git a/tests/parser.el b/tests/parser.el
index f6345e1..355c2df 100644
--- a/tests/parser.el
+++ b/tests/parser.el
@@ -1218,3 +1218,7 @@ the test."
 (js2-deftest-classify-variables named-wrapper-function
   "function foo() { var a; (function bar() { a=42; })(); return a; }"
   '("foo@10:U" "a@22:I" 62 "bar@35:I" 35))
+
+(js2-deftest-classify-variables destructure
+  "function foo(x,y) { let [u,v] = [x,y]; }"
+  '("foo@10:U" "x@14:P" 34 "y@16:P" 36 "u@26:I" 26 "v@28:I" 28))
```

I won't be able to dig further until upcoming weekend though, sorry.

**Comment by lelit** [comment]
Also, are there other variations of the "destructure" syntax I should handle? Can they be nested?
... always something new to learn! ;-)

**Comment by dgutov** [comment]
There's also object destructuring: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring

They *can* be nested (arbitrarily, I think). Example from Firefox's console:

 ```js
var {p: [, foo], q: bar} = {p: [1, 2, 3], q: 4};
=> undefined
foo
=> 2
bar
=> 4
```

**Comment by lelit** [comment]
Ok, thank you Dmitry! Will learn about them and try to rectify the new function.

**Comment by lelit** [comment]
@dgutov, can you please look at my attempt and give me some feedback? Would that be enough in your opinion?

**Comment by dgutov** [comment]
@lelit I think it's only missing the "abbreviated object destructuring" case, example:

```js
let {a, b} = {a: 1, b: 2}
=> undefined
a
=> 1
b
=> 2
```

**Comment by lelit** [comment]
Uhm, I've followed the `SHORTHAND` flag that AFAIU tracks that case.

Accordingly to the documentation:

> If the property is abbreviated, the node's `SHORTHAND' property is non-nil and both fields have the same value.

the code should already able to deal with it, and a quick test seems to confirm: what am I missing?

**Comment by dgutov** [comment]
Ah, you're right, thanks. I didn't test the code itself.

Here's another example:

```js
let {a, b, c = 3} = {a: 1, b: 2}
=> undefined
c
=> 3
```

For this case, `js2-define-destruct-symbols` uses `js2-infix-node-left` (as well as a `js2-infix-node-type` check). The new function will probably need to do that too.

**Comment by lelit** [comment]
Thank you!

 I pushed [another commit](https://github.com/lelit/js2-mode/commit/3725fcfe3fef6a5d9776dcb399f949f79de9d3a2) on my issue393 branch that handles also the case above: as stated in the commit log, I'd like to know your opinion about a possible refactor of `js2-define-destruct-symbols` on top of the new `js2--collect-target-name-nodes`.

**Comment by dgutov** [comment]
A refactor sounds good, thanks.

**Comment by lelit** [comment]
Dmitry, I pushed some more commits on my (issue393 branch)[https://github.com/lelit/js2-mode/tree/issue393] that handle all the reported cases.

I refactored the `js2-define-destruct-symbols` on top of the (_renamed_) `js2--collect-declared-symbols`.

I then completely rewrote the main function, `js2--classify-variables`, streamlining it to simplify the logic. 

Can you please review the changes and give me some feedback? Is it good enough for a PR?

**Comment by dgutov** [comment]
> on top of the (renamed) js2--collect-declared-symbols

I think the previous name might have been a bit better. See this example. Here's declaration happens before destructuring, but the name nodes are "targets" here as well.

```js
var a, b;
=> undefined
[a, b] = [1, 2]
=> Array [ 1, 2 ]
a
=> 1
b
=> 2
```

> Is it good enough for a PR?

I'm sure it's close. Could you please open a PR first, and then I'll review? That is their purpose, after all.

**Comment by lelit** [comment]
Sure, I will rename it: what about `js2--collect-target-symbols`?

**Comment by dgutov** [comment]
Yeah, ok.

**Comment by dgutov** [comment]
@davazp Please try out the newly merged changes.

**Comment by davazp** [comment]
@dgutov It works nicely for me, although I am not using complicated destructuring. I'll pay attention to more complex cases.

Thanks for the fix. That was a great job and thread.
