### ISSUE TITLE
Block-scoping in switch statements

### ISSUE THREAD

**Issue by felipeochoa** [mooz/js2-mode#396]
In the same vein as #306, declarations within a `switch` statement appear to be hoisted up to the enclosing block:

```js
let a = 1;
switch(a) {
case 1:
  let a = 2;  // Improperly labeled a re-declaration
default:
  console.log(a);
}
console.log(a);
```

Not sure I fully grok[ the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-switch-statement-runtime-semantics-evaluation), but I think it's saying `switch` statements create their own scopes. Running this example in a modern browser will print out 2 then 1, and will not complain. Also [this MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) suggests that it is in fact a separate block.

**Comment by dgutov** [comment]
You're most likely right.

Does this do the trick?

**Comment by felipeochoa** [comment]
Perfect, thanks!
