### ISSUE TITLE
Please allow global variable list to begin with "/*<space>" along with "/*" (no space)

### ISSUE THREAD

**Issue by dod38fr** [mooz/js2-mode#402]
Hello

With [standardjs](http://standardjs.com/), the comment that contain the global list of variables must begin with `/*<space>`.

On the other hand `js2-mode` only parse this list if there is no space after `/*`.

Could you update `js-mode` to allow a space to be compatible with standardjs ?

All the best

**Comment by dgutov** [comment]
This should already work. Are you installing from MELPA?

**Comment by dod38fr** [comment]
No, I'm using Debian package elpa-js2-mode 0~20150909-2 .

**Comment by dgutov** [comment]
That sounds very old. :) Do you have any good reasons not to install from ELPA directly?

The current stable version is `20160623`. And give me a little time, I'll push out a new one, with this fix included.

**Comment by dod38fr** [comment]
As a Debian developer, I prefer to use packaged versions, if only to detect when such versions are old and nudge my fellow debian developer to publish a new package. :wink: 

Otherwise, I also sometime use elpa, but then I don't really know which emacs package version I'm using when both elpa and debian package are installed.

In this case, I also have js-mode 20160409 installed in `~/.emacs.d/elpa`, so I may have been wrong in my previous message.

Thanks for your quick reply

All the best

**Comment by dgutov** [comment]
All right, I've tagged and pushed a new version.

> nudge my fellow debian developer to publish a new package

Please go ahead. ;)

**Comment by dod38fr** [comment]
[done](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851599) and [uploaded](https://tracker.debian.org/news/833119)...

Debian at its best :+1:
