### ISSUE TITLE
Dangling or trailing commas in parameter list

### ISSUE THREAD

**Issue by joepistritto** [mooz/js2-mode#403]
ES6 proposal allows a dangling comma in function parameter list. Is there a way to get js2 to be less strict about warnings on this as currently it parses as a syntax error:

```js

function foo(a,
             b,
             c,
             )
```

**Comment by ttmarek** [comment]
This proposal is in stage 4, which means its been approved and will be a part of the official ES2017 spec. https://github.com/tc39/proposal-trailing-function-commas

@mooz is this a quick fix? If not, I can offer up some time to make a PR.

**Comment by felipeochoa** [comment]
@ttmarek I think this is a quick fix. The place to modify is [`js2-parse-function-params`](https://github.com/mooz/js2-mode/blob/d3b31ba/js2-mode.el#L8255-L8313). It's basically a `do parse-param while have-comma` loop. I think a quick fix would be to change the final check on line 8313 to:

```elisp
(and (js2-match-token js2-COMMA) 
     (or (< js2-language-version XXX) 
         (not (= js2-RP (js2-peek-token)))))
```

@mooz How are language versions mapped onto es6/es7?

**Comment by dgutov** [comment]
@felipeochoa See the first (red) column in https://en.wikipedia.org/wiki/JavaScript#Version_history.

But basically, ES6 and anything newer is the version 200. :)

**Comment by felipeochoa** [comment]
Hmmm. I see. So Mozilla abandoned their versioning system... Does it
make sense to distinguish between ES6 and ES7 (and future versions to
come?). Perhaps we could jump from 200 to 700 (for ES7) and then keep
ESX matched to X00. Are there already other ES7 features in js2?

**Comment by dgutov** [comment]
> Perhaps we could jump from 200 to 700 (for ES7) and then keep ESX matched to X00.

Sounds good.

> Are there already other ES7 features in js2?

There are. Async/await and class public fields come to mind.

**Comment by felipeochoa** [comment]
Ok. If I can find some time this weekend or next week I'll put together a PR to clean up the versioning. In the meantime, @ttmarek if you want to tackle this issue, just put it on version 200
