### ISSUE TITLE
decorators anyone? 

### ISSUE THREAD

**Issue by fxfactorial** [mooz/js2-mode#406]
Love this mode but apparently decorators are not well supported, using it with Mobx

<img width="472" alt="screen shot 2017-03-12 at 10 28 03 am" src="https://cloud.githubusercontent.com/assets/3036816/23834142/9b3b9888-070e-11e7-878b-ee534c27bd24.png">

**Comment by dgutov** [comment]
It's only Stage 2 so far: https://github.com/tc39/proposal-decorators

**Comment by fxfactorial** [comment]
Yes, and Angular and mobx use it. Both have large followings, so I think it is safe to say that it will be approved. 

Also, do you mean to imply only stage-3 >= are supported?

**Comment by dgutov** [comment]
Stage 2 might be fine. But someone still need to write the code to support this.

**Comment by XeCycle** [comment]
I took a brief look at this; the use of `@` seems to conflict with E4X.  I tried to get the specs for E4X, which is [ECMA-357](http://www.ecma-international.org/publications/standards/Ecma-357.htm), but the PDF link inside actually points to ECMA-375, describes a DVD case, lol.

**Comment by abhishiv** [comment]
Please Please remove E4X. I can bet 99.99% js dev have no clue what E4X is/was.

**Comment by dgutov** [comment]
> IIRC we said removing E4X may be acceptable, is it?

At this point, yes.

**Comment by cowboyd** [comment]
Is there anybody working on this? I'd be happy to pair program on it since decorators are only going to get more important as time progresses.

**Comment by altschuler** [comment]
I'd also be happy to help out on this if someone could give some pointers :)

**Comment by trebor** [comment]
is anyone still working on this? without decorators i'm pretty solidly jammed up. :\

**Comment by cowboyd** [comment]
Hey @trebor. I think the consensus is that until decorators move beyond stage 2 that nobody is going to futz with it.

You can use  [tide-mode](https://github.com/ananthakumaran/tide) for vanilla JS and it might very well understand decorators.

If I had to guess, I'd say the future for JavaScript and every other language is with [LSP](https://microsoft.github.io/language-server-protocol/)  and an emacs implementation like [emacs-lsp](https://github.com/emacs-lsp/lsp-mode) or [eglot](https://github.com/joaotavora/eglot)

Tide uses the typescript language server under the covers, and I'd expect to see this approach only become more prevalent for everything.

**Comment by trebor** [comment]
@cowboyd thanks!
