### ISSUE TITLE
imenu calculated prop problem

### ISSUE THREAD

**Issue by felipeochoa** [mooz/js2-mode#408]
I don't know if this is a bug, but I just ran into something like this:

```js
const a = 'a';
const b = {
    [a]: {
        x: y => y
    }
};
```

The above results in an imenu alist which looks like: 

```lisp
(("b" .
  ((nil
    (("x" . 47))))))
```

I think the `nil` is a product of `imenu` not understanding the computed prop, but there seems to be an extra list in there. I'm not familiar enough with imenu to know if this is an alternate (or old) format, but the docs say that "A nested sub-alist element looks like (INDEX-NAME . SUB-ALIST)". I would have expected the alist to be something like:

```lisp
(("b" .
  (("[a]" .           ; Note period here
    (("x" . 47))))))
```

**Comment by dgutov** [comment]
Thanks for the report, I've pushed a simple patch to deal with the error.

If you'd like to see something else instead of `[computed]` there, patch welcome. ;)

**Comment by felipeochoa** [comment]
Amazing, thanks for the quick response! `[computed]` works for me :)
