### ISSUE TITLE
JSX quotation bug

### ISSUE THREAD

**Issue by Ailrun** [mooz/js2-mode#409]
When I use `'` in the JSX tags like

``` JSX
function Bug() {
    return <div>C'est Montréal</div>;
}
```

syntax highlighting and indenting, .... are broken.

Is is possible solving this issue?

**Comment by dgutov** [comment]
I see the problem with indentation, but not with syntax highlighting.

**Comment by Ailrun** [comment]
@dgutov
Maybe highlighting is just to do with other plugin.
Anyway, could you fix these indentation issue?
