### ISSUE TITLE
Embedded JSX in parens breaks indentation

### ISSUE THREAD

**Issue by benzitohhh** [mooz/js2-mode#411]
Hi there,

in js2-jsx-mode (and also rjsx-mode)...

when embedded JSX is wrapped in parens, the indentation breaks.

Some examples:

```jsx
// All indents ok
let a = (
  <div>
    {condition && <Component/>}
    {condition && <Component/>}
    <div/>
  </div>
)

// Last line is wrongly indented
let b = (
  <div>
    {condition && (<Component/>)}
    <div/>
    </div>
)

// Penultimate line is wrongly indented
let c = (
  <div>
    {condition && (<Component/>)}
  {condition && "something"}
  </div>
)

// Penultimate line is wrongly indented
let d = (
  <div>
    {(<Component/>)}
  {condition && "something"}
  </div>
)
```

It seems like when previous line has embedded JSX in parens,
"indentation-type" is interpretted as "nil" (should be "nth")
i.e. see `js-jsx-indent-line` and `js--jsx-indented-element-p` (in `js.el`)

I get this behaviour in both Emacs 25.1 and also Emacs 25.1-2

Obviously one workaround would be to not use parens. But unfortunately I need to use parens to make certain rjsx functinality work (i.e. see https://github.com/felipeochoa/rjsx-mode/issues/27#issuecomment-272650705  and https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24896#20)

Anyways any ideas would be really appreciated - thanks!

**Comment by wd** [comment]
It seems I got the same issue:

```
            <View >
                <GANavBar goBack={()=>this.test} />
                    <View >test</View>
            </View>
```

Line 3 shouldn't indent. If I delete the '()=>', the indent works ok.

**Comment by wyuenho** [comment]
@benzitohhh @wd Can you try this [branch](https://github.com/felipeochoa/rjsx-mode/pull/75) out and see if it's fixed?

**Comment by benzitohhh** [comment]
Hey @wyuenho thanks for looking at this.

I checked out the branch, but it seems to give exactly the results as before with my test set (top of this issue).

But I don't know much about installing packages, so maybe I am doing something stupid?
i.e. I uninstalled rjsx, and then used `(load "/pathTo/rjsx-mode.el")` to load your code.

**Comment by wyuenho** [comment]
0. `M-x package-delete`
1. `Delete package: rjsx-mode`
2. `M-x package-install-file`
3. Package file name: /path/to/rjsx-mode.el
4. Visit your JSX file and M-x rjsx-mode

You should see the JSX indented correctly.

**Comment by benzitohhh** [comment]
@wyuenho Sorry my bad, was looking at the wrong branch.

Indentation works great. Thanks so much!

**Comment by mjin955** [comment]
@wyuenho Hi I looked at the pull request but I can't see to checkout indent-after-jsx-expr
I am only seeing master branch.

**Comment by wyuenho** [comment]
Look at my fork

**Comment by mjin955** [comment]
@wyuenho 
of course, sorry about that. I tried out your branch but I think I misunderstood the issue you resolved. Do you have any idea how to fix the one I am having below?
Expected:
```
    <select
        id="month"
        onChange={this.handleMonthChange}>
        <option>Month</option>
        <option>1</option>
    </select>
```
actual:
```
     <select
id="month"
onChange={this.handleMonthChange}>
    <option>Month</option>
    <option>1</option>
    </select>
````

**Comment by wyuenho** [comment]
https://www.reddit.com/r/emacs/comments/8li7zn/how_do_you_all_fix_your_rjsx_indenting_issues/dzhdl2b/

**Comment by mjin955** [comment]
Hey man, sorry but I think we misunderstood each other. I have am already using your branch of rjsx-mode. However, your branch doesn't fix the issue I mentioned

> Expected:
> ```
>     <select
>         id="month"
>         onChange={this.handleMonthChange}>
>         <option>Month</option>
>         <option>1</option>
>     </select>
> ```
> actual:
> ```     <select
> id="month"
> onChange={this.handleMonthChange}>
>     <option>Month</option>
>     <option>1</option>
>     </select>
> ```
Do you have any idea to why I am getting this indentation issue?

**Comment by wyuenho** [comment]
Ah, try setting both `js2-basic-offset` `sgml-basic-offset` to 2, the attribute portion is indented by SGML mode, if you don't set the offset, it won't line up.
