### ISSUE TITLE
Support for Async Iterators/Generators syntax

### ISSUE THREAD

**Issue by michaelsbradleyjr** [mooz/js2-mode#412]
Async Iterators/Generators are at Stage 3: https://github.com/tc39/proposal-async-iteration

Great stuff, really!  js2-mode complains about `for-await-of`, and also async generators when given as methods on a class.

**Comment by brn** [comment]
+1

**Comment by bellbind** [comment]
+1

"Aync generator" function/method and "for-await-of" loop are now in released ECMAScript-2018.

- https://www.ecma-international.org/ecma-262/9.0/index.html#sec-async-generator-function-definitions
- https://www.ecma-international.org/ecma-262/9.0/index.html#sec-for-in-and-for-of-statements
