### ISSUE TITLE
Make variables as safe-local-variable

### ISSUE THREAD

**Issue by notetiene** [mooz/js2-mode#416]
I saw that there's a function (`js2-mark-safe-local`) to make variable as locally safe. However, I see no call to that function.

I think it could be nice to add some variable as safe.
Is there a reason why it's not used?

**Comment by dgutov** [comment]
Thank you for the reminder. It's been unused since 4c02462944a24085ba4843be29637265423b9fe5 where it's been replaced by `defcustom` `:safe` keyword.
