### ISSUE TITLE
CEDET Support

### ISSUE THREAD

**Issue by lewisloofis** [mooz/js2-mode#417]
Hello,
Does js2-mode has a plan to integrate support to CEDET (Semantic bovinator etc.)? Or is it possible to link js2 mode imenu to CEDET

It would be nice to have code browsing support for modern programming language in emacs without installing additional package (like Tern), something I think emacs probably lacking. From what I know, CEDET only support older javascript spec definition.

**Comment by dgutov** [comment]
No plans, and it doesn't sound trivial. Basically, js2-mode would have to support completion itself, and then *that* logic could be hooked into CEDET. Not sure how much benefit that would bring.

Also see https://github.com/mooz/js2-mode/issues/26.

**Comment by lewisloofis** [comment]
i see, actually the thing that i'm really looking for is the code browsing feature. When I look at js2-mode code it looks like it supports imenu, but does it support ES6 features like arrow functions, const variable etc? I keep using imenu command and the result is always nil. I will give you some code example

`
const app = new Express()
const port = process.env.PORT || 3000
const env = process.env.NODE_ENV || 'production'

const serverSSL = {
  key: fs.readFileSync('./certs/nginx.key'),
  cert: fs.readFileSync('./certs/nginx.crt')
}

mongoose.connect('mongodb://mongodb/testdb')

app.use(Express.static('public'))
app.use(bodyParser.urlencoded({extended: false}))
app.use(bodyParser.json())
app.use(logger('dev'))

app.use('/api', api)
app.use('/admin', admin)
app.use('/', frontend)

const http2server = http2.createServer(serverSSL, app).listen(port, err => {
  if (err) return console.error(err)
  console.info(`Server is running on port:${port} [${env}]`)
})
`

**Comment by dgutov** [comment]
Imenu index in js2-mode (and most other modes, to my knowledge) does not tag variable declarations.

And as for `http2server`, there's no way to know that `http2.createServer` returns a function. So it's treated as a plain variable as well.

**Comment by dgutov** [comment]
You can try using `js2-imenu-extras-mode` and adding a custom parser via `js2-imenu-extension-styles`.
