### ISSUE TITLE
js2-mode hangs upon initial semicolon, drops error report and is fine

### ISSUE THREAD

**Issue by codabrink** [mooz/js2-mode#419]
When opening an existing file and adding a missing semicolon to a linted line in js2-mode, my emacs will freeze for about 15-20 seconds before something times out and this error message drops. 

![error-mesage](http://i.dakota.io/3qfjh2.png)

After the error message drops, everything continues as normal in the file. I can't make sense of the error message though. Sorry about the ambiguity.

Here is my [Emacs config](https://pastebin.com/FZAG8hAu) if that helps at all.

**Comment by dgutov** [comment]
Emacs config doesn't help. Example code would help.

**Comment by sodacode** [comment]
I'm working on code that I can't share at the moment.. I'll report back if it occurs on code that I can share.
