### ISSUE TITLE
ES6 Object destructuring wrong syntax highlighting

### ISSUE THREAD

**Issue by fxfactorial** [mooz/js2-mode#420]
Given this: 

```javascript
const {foo: missing = 10} = {};
```
I get this incorrect warning

<img width="273" alt="screen shot 2017-04-27 at 10 56 31 pm" src="https://cloud.githubusercontent.com/assets/3036816/25517503/93247ede-2ba4-11e7-942f-214cffe87eb2.png">

**Comment by dgutov** [comment]
Should be fixed now, please test.

**Comment by fxfactorial** [comment]
@dgutov yep works! Thanks @lelit
