### ISSUE TITLE
await incorrectly described as having no side effects

### ISSUE THREAD

**Issue by felipeochoa** [mooz/js2-mode#429]
Sometimes it's convenient or necessary to create promises before awaiting them, which results in code like the following:

```js
async function example() {
  const p1 = queryDB();
  const p2 = anotherDBQuery();
  await p1;
  await p2;
}
```

Currently the two awaits are flagged as having no side-effects, which is incorrect.

**Comment by dgutov** [comment]
Indeed. Patch welcome.
