### ISSUE TITLE
Single quote (') breaks the syntax in JSX -mode

### ISSUE THREAD

**Issue by azer** [mooz/js2-mode#431]
I'm experiencing a problem with the single quote character (') in the js2-jsx-mode. Here is an example;

```js
<Hi>Let's go!</Hi>
```

js2-jsx-mode ([version 2017-01-16](https://stable.melpa.org/#/js2-mode)) shows it as following;

![](https://cldup.com/OzfD4tDim7.png)

**Comment by latpaw** [comment]
rjsx-mode works well with jsx

**Comment by azer** [comment]
@latpaw yeah, except that it depends on a version of js2-mode which is not published to stable channels.

**Comment by dgutov** [comment]
Good point, I'll do that.

**Comment by dgutov** [comment]
@azer Actually, why do you say that? `rjsx-mode.el` declares dependency on `20160623`, which is even one version older than the latest one at GNU ELPA.

**Comment by dgutov** [comment]
@azer ping?

**Comment by azer** [comment]
@dgutov I'm also confused. I got `rjsx-mode` working right by reinstalling everything from unstable channels, but probably it doesn't matter for this project. If jsx support is dropped due to rjsx, I think we can close this issue.
