### ISSUE TITLE
Async arrow functions without parenthesis 

### ISSUE THREAD

**Issue by mostafah** [mooz/js2-mode#433]
These work well:

    async () => …
    async (a) => …

But this one does not, even though it is valid JS:

    async a => …

It gives “Undeclared variable or function 'async'” for `async`, and “missing : after property id” for `=>`. If I use a `{` after the arrow for starting a function body, that character is highlighted with this error: “invalid property id”.

I have Emacs version 25.2.1, js2-mode version 20170624.1249, and am using rjsx-mode version 20170710.711.

Please let me know if I need to provide more information.

**Comment by dgutov** [comment]
Thanks.

What version of JS is it valid in?

**Comment by mostafah** [comment]
Since the introduction of arrow functions in ES6, parenthesis have been optional when there’s only one parameter. It is mentioned in the first example [in this MDN doc](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions). It is also recommended in AirBnB’s JS style guide [to drop parenthesis when there is only one parameter](https://github.com/airbnb/javascript#arrows--one-arg-parens). And async / await documentations only talk about adding `async` to current function definitions. They never talk about new syntax restrictions for async functions. Also, that code works with Babel and Node version 8.0.

That is why I said this is valid in JS.

But to give a better answer to your question I took a quick look at the specs. I’m not sure I’m reading those syntax definition specs correctly, but I guess they are confirming that this has always been valid:

Arrow functions are [defined here](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-arrow-function-definitions). `ArrowParameters` has two options: one is a single `BindingIdentifier` with no parenthesis and the other is `CoverParenthesizedExpressionAndArrowParameterList` which is a list of parameters with parenthesis (defined elsewhere in the document).

Async arrow functions are [defined here](https://tc39.github.io/ecmascript-asyncawait/#async-arrows). They also have two definitions that both are valid. The first one has `AsyncArrowBindingIdentifier` which is a single identifier without parenthesis for the parameter. The second one (`CoverCallExpressionAndAsyncArrowHead`) is the more elaborate one with the parenthesis.

I’m sure you can have a better understanding of those syntax definitions than me.

**Comment by dgutov** [comment]
Thank you for the expansive answer, this was clearly a bug in our code.

> And async / await documentations only talk about adding async to current function definitions. They never talk about new syntax restrictions for async functions.

This was the key point.

Should be fixed now.

**Comment by mostafah** [comment]
Yes. I updated to version 20170716.1313 and it is working now. Thanks for the quick fix.
