### ISSUE TITLE
import-clause children not visited in order

### ISSUE THREAD

**Issue by felipeochoa** [mooz/js2-mode#439]
If you have an import statement with both a default import and named imports, `js2-visit-import-clause` visits children in the wrong order. Based on the parsing rules in `js2-mode` (and  [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)), the default import should always come first.

The impact of this bug is that `js2-node-at-point` does not pick up on the `js2-name-node` in these cases. For example:

```js
import defaultImport, { a, b, c} from 'xyz';
```

If you put point in `defaultImport` and `M-x eval-expression (js2-node-short-name (js2-node-at-point))`, you get `"js2-import-clause-node"`

**Comment by dgutov** [comment]
Yeah, I think reverting the order in `js2-visit-import-clause` makes sense.

Care to make a PR?

**Comment by felipeochoa** [comment]
Was already in process :)

**Comment by dgutov** [comment]
Thanks!

Next time, you can just put the problem description into the PR comment. Especially if it's as simple as this one.

**Comment by felipeochoa** [comment]
Will do!
