### ISSUE TITLE
export default now makes variables mean undeclared

### ISSUE THREAD

**Issue by fxfactorial** [mooz/js2-mode#441]
<img width="544" alt="screen shot 2017-08-07 at 3 15 07 pm" src="https://user-images.githubusercontent.com/3036816/29047976-387e4a94-7b83-11e7-9ca1-9de036ac99f6.png">

and warning says animations is undeclared variable, remove the export default and it is fine.

**Comment by dgutov** [comment]
All right. Sorry about the mess, but the best I can do now is a half-assed fix.

**Comment by dgutov** [comment]
Should work now.
