### ISSUE TITLE
&& operatorn can't be used for conditional renders in jsx

### ISSUE THREAD

**Issue by carlosyslas** [mooz/js2-mode#445]
The `&&` operator can't be used for conditional renders in `jsx`.
Try this code:
```javascript
const TestComponent = ({ showInnerContent }) => (
    <div>
      {showInnerContent && <InnerContentcomponent/>}
    </div>
);
```
It's displayed as:

![_scratch_](https://user-images.githubusercontent.com/658944/29460206-5dcda1e4-8427-11e7-8f4c-772ff56b958b.png)

**Comment by dgutov** [comment]
Try https://github.com/felipeochoa/rjsx-mode

**Comment by carlosyslas** [comment]
Thanks @dgutov, https://github.com/felipeochoa/rjsx-mode works! Although I don't know if it's a good idea to have 2 modes that aim to do the same thing. Do you guys have talked about working together?

**Comment by carlosyslas** [comment]
Awesome! So I think at some point you are going to support the same kind of modern features. I'll close this issue.
