### ISSUE TITLE
cannot to jump to definition in another file

### ISSUE THREAD

**Issue by lawrsp** [mooz/js2-mode#449]
A.js
```
export const test = (x) => {
    console.log(x)
    return 100 * x
}
```

B.js:

```
import {test} from './A.js'

const x = test()

```

in the file B.js , cannot use M-. to jump to file A.js , only jump to the "import" line

did I miss some config ?

**Comment by osv** [comment]
Try ternjs. Sometimes ternjs also fail to jump..

**Comment by lawrsp** [comment]
too old,  use tide now
