### ISSUE TITLE
Killing some lines causes Emacs to freeze

### ISSUE THREAD

**Issue by hlolli** [mooz/js2-mode#455]
This blame should taken with a grain of salt, other factors could be at play here.

As a very simple reproduceable example on emacs 26.0.50 on js2-mode from ELPA
```
(defconst js2-version "1.8.5"
  "Version of JavaScript supported.")
```

Then any attempt to kill the last line of this file cause Emacs to freeze
```
const csound = require('csound-api');
const Csound = csound.Create();
csound.SetOption(Csound, '--output=dac');
csound.CompileOrc(Csound, `
  0dbfs = 1
  ksmps = 1

  instr 1
    asig poscil 80, 0.2
    asig2 poscil 162, 0.2
    aenv expon 1, 0.2, 0.01
    outc (asig2+asig)*aenv
  endin
`);
// Kill this line below
csound.InputMessage(Csound, `i 1 0 10`);
```

If this is not reproduceable, I will dig trough my minor modes and see if they are causing trouble here, most of my minor modes are minor modes with other major modes and dont cause trouble besides in .js files.

**Comment by dgutov** [comment]
Can't repro.

> I will dig trough my minor modes and see if they are causing trouble here

Please go ahead. You can start with `emacs -Q -L ~/.emacs.d/elpa/js2-mode-... -l js2-mode`, to make sure the bare configuration works fine.

**Comment by hlolli** [comment]
Ah I should have tried that before opening this ticket,
```
emacs -Q -L ~/.emacs.d/elpa/js2-mode-20170930.820/ -l js2-mode
```
enabling js2-mode and killing that line causes no crash.

thanks for the reply

**Comment by hlolli** [comment]
FWIW, I'm useing paredit-everywhere, and this comes from the function `paredit-kill` which bound to `C-k` on my keyboard. But I'm guessing it's rare for lispers to be writing javascript :)
