### ISSUE TITLE
Support es2017 (es8) trailing commas in function parameter lists and calls

### ISSUE THREAD

**Issue by danielbush** [mooz/js2-mode#457]
Highlighting breaks if we have trailing commas in function parameter lists.
I think it's breaking the parser that js2-mode is using - but I'm not familiar with the internals for js2-mode.

Happy to try to help if there's some way to get this working - but could do with some pointers.

**Comment by dgutov** [comment]
I think we've merged this to master 9 days ago.

**Comment by DoMiNeLa10** [comment]
There hasn't been any release with this (significant) fix yet.

**Comment by dgutov** [comment]
Fair complaint. I've pushed a new release now.
