### ISSUE TITLE
cannot enable js2-mode 

### ISSUE THREAD

**Issue by eggcaker** [mooz/js2-mode#458]
after install js2-mode with ```package-install``` cannot enable js2-mode with error mesage : 

```
Eager macro-expansion failure: (error "Don’t know how to make a localized variable an alias") [2 times]
if: Don’t know how to make a localized variable an alias

```

**Comment by dgutov** [comment]
Have you tried restarting, reinstalling, etc?

**Comment by eggcaker** [comment]
yes, I tried  reinstall and restart emacs, same

**Comment by dgutov** [comment]
Which archive are you installing from?

**Comment by eggcaker** [comment]
from elpa, but i use spaemacs with javascript layer, maybe it's not relly js2-mode issue but spameacs, i'll test clear install js2-mode.

**Comment by eush77** [comment]
Hi!

I had the same problem after permanently accepting the value of
`js2-basic-offset` from the `.dir-locals.el` file before entering `js2-mode`
once.

I solved it by removing this line from my custom file:

    '(safe-local-variable-values (quote ((js2-basic-offset . 2))))

and replacing

    (nil . ((js2-basic-offset . 2)))

with

    (js2-mode . ((js2-basic-offset . 2)))

in the `.dir-locals.el` file.

Hope that helps.

**Comment by eggcaker** [comment]
after clear all the ident offset setup its working now still don't know why, but it  works , yo
