### ISSUE TITLE
Issue with `js2-jsx-mode` indentation for self closing components with JS blocks for props

### ISSUE THREAD

**Issue by domtronn** [mooz/js2-mode#459]
Hi there, I have some JSX in the following form

```jsx
export default ({ stars }) => (
  <div className='overlay__container'>
    <div className='overlay__header overlay--text'>
      Congratulations!
    </div>
    <div className='overlay__reward'>
      <Icon {...createIconProps(stars > 0)} size='large' />
        <div className='overlay__reward__bottom'>
          <Icon {...createIconProps(stars > 1)} size='small' />
            <Icon {...createIconProps(stars > 2)} size='small' />
        </div>
    </div>
    <div className='overlay__description overlay--text'>
      You've created <large>1</large> reminder
    </div>
  </div>
)
```

And the indentation is off for the `Icon` components when calling `js2-jsx-indent-line`... Doing a bit of experimentation, I found that removing the JavaScript block _or_ closing the component tag explicity, _i.e.

```jsx
<Icon size='large' />
<Icon {...createIconProps(stars > 1)} size='large'></Icon>
```

Works correctly for the indentation. However, I don't want to explicitly close the components when I don't have to... I guess during parsing it's recognising the self closing tag as an open XML tag for some reason when it contains `{}`?

**Comment by jozefpetro** [comment]
Same problem here but it's happening only when using class-based component
<img width="592" alt="screen shot 2017-12-19 at 16 14 46" src="https://user-images.githubusercontent.com/15748491/34163709-c3bc3fea-e4d7-11e7-8db1-870a98ca6d42.png">

**Comment by dgutov** [comment]
@jozefpetro I can't reproduce your problem. It likely depends on the surrounding code that's not in your screenshot.

Either way, `js2-jsx-mode` uses `js-jsx-indent-line` for indentation, so this report should go to the Emacs core.
