### ISSUE TITLE
Provide different faces for keys in json and variable lookup

### ISSUE THREAD

**Issue by Fuco1** [mooz/js2-mode#460]
Right now in both 

```js
{foo: "bar"}
```

and

```js
object.foo
```

the key `foo` will get `js2-object-property` face.  I would like to have it in the first case but not in the second (the dot notation).

Can we introduce a new face and let it inherit from the old one so that nobody's config breaks but we have more flexibility?

If you point me in the right direction I'm happy to make the patch myself.

**Comment by dgutov** [comment]
Speaking of pointers, this was added in https://github.com/mooz/js2-mode/commit/2e7fdb3a1de4641fa22ec7b4d96f4d75e8307341

**Comment by Fuco1** [comment]
@dgutov Thanks, that seems to be the place to look at.  I'll look into this.
