### ISSUE TITLE
Indentation bugs when multi-line call has regex as argument

### ISSUE THREAD

**Issue by n3dst4** [mooz/js2-mode#463]
Sorry to log yet another indentation bug, but I'm not sure how to even begin addressing this.

The following represents a call to a function `bar` with two arguments, a string and a regex literal:

```js
bar(
  "string arg1",
  /regex arg2/
)
```

Under js2-mode the third line get indented one indent too many:

```js
bar(
  "string arg1",
    /regex arg2/
)
```

Making it appear to be nested inside the first argument in some way.

It's even worse if the regex contains the characters `"const"` - in this case the line gets indented 8 columns to the right every time, so it marches off the screen eventually:

```js
bar(
  "string arg1",
                                                          /const/
)
```

Emacs version: GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12
js2-mode: 20171014.1229

**Comment by dgutov** [comment]
Thanks for the report. I have now fixed this in the Emacs 26 development branch.

**Comment by n3dst4** [comment]
Thanks, @dgutov

**Comment by n3dst4** [comment]
Just copied the fixed version into my emacs installation (not sure if that's the best way to do it) and it works great.

**Comment by dgutov** [comment]
> not sure if that's the best way to do it

Either that of wait until Emacs 26 :)
