### ISSUE TITLE
js2-mode switch indent not working

### ISSUE THREAD

**Issue by chenpoyang** [mooz/js2-mode#470]
For examle, how could i get this:
<pre>
switch(num)
{
    case 1:
        document.write("1");
        break;
    case 3:
        document.write("3");
        break;
}
</pre>

instead of default:
<pre>
switch(num)
{
    case 1:
    document.write("1");
    break;
    case 3:
    document.write("3");
    break;
}
</pre>

here is my js2-mode indent config code:
<pre>
(defun js2-mode-indent-init()
  (c-set-offset 'case-label '+)
  (setq indent-tabs-mode t)
  (setq js-indent-level 4)
  (setq js2-switch-indent-offset 4)
  (setq js2-basic-offset 4)
  (setq js2-indent-switch-body t))

(add-hook 'js2-mode-hook 'js2-mode-indent-init)
</pre>

by the way, i am using emacs 25.3

**Comment by vxcamiloxv** [comment]
Same error here

**Comment by vxcamiloxv** [comment]
`js-switch-indent-offset` fixed my problem

**Comment by axelson** [comment]
Specifically `js-switch-indent-offset` takes the number of spaces to indent, so to match the config above you'd add `(setq js-switch-indent-offset 4)` (or substitute `2` if you indent by two spaces).

**Comment by dgutov** [comment]
Thanks everybody.
