### ISSUE TITLE
Identation issue ({

### ISSUE THREAD

**Issue by dmitry-saritasa** [mooz/js2-mode#472]
```
(custom-set-variables  
 '(js2-basic-offset 2)
 '(js2-bounce-indent-p t))
```

![image](https://user-images.githubusercontent.com/1747653/33185080-21f62f56-d035-11e7-8f78-fd51eee566dc.png)

it's 2 chars offset, however, I would expect it to be 4 as there is a curly brace on the 1st line

If I move curly brace on the next line everything is fine

![image](https://user-images.githubusercontent.com/1747653/33185127-67c3d240-d035-11e7-9947-06debd1267a3.png)

**Comment by dgutov** [comment]
Looks right to me. You have the choice of indentation this way.
