### ISSUE TITLE
Please tell me how to ignore syntax error.

### ISSUE THREAD

**Issue by nrikiji** [mooz/js2-mode#481]
```
var hoge = function() {
  var fuga = function {
  }
}
```
<img width="188" alt="2018-02-07 14 45 19" src="https://user-images.githubusercontent.com/4780752/35900494-98bb7a08-0c15-11e8-9de2-e9719e2b9ae0.png">

I want to ignore the warning when there is no trailing semicolon.

**Comment by mpontus** [comment]
You can disable this warning by setting `js2-strict-missing-semi-warning` option to nil.

**Comment by nrikiji** [comment]
thanks!
