### ISSUE TITLE
Comment highlighting isn't always updated after un/commenting

### ISSUE THREAD

**Issue by angrybacon** [mooz/js2-mode#483]
Noticed this using RJSX mode and saw the behavior was also present with JS2 mode.

Steps to reproduce:

1. Mark a region
1. `comment-dwim`

Comments are not highlighted until point is moved.

----

Edit: can't reproduce using `emacs -q`:

```elisp
(setq package-load-list '((js2-mode t) (rjsx-mode t)))
(package-initialize)
```

Will try and pin-point the problem.

----

Edit: seems to come from `aggressive-indent-mode`. However I still do see a slight delay after hitting <kbd>M-;</kbd>. Can that delay be reduced?

I'll investigate regarding `aggressive-indent-mode`.

**Comment by angrybacon** [comment]
```elisp
(use-package aggressive-indent
  :hook (js-mode . aggressive-indent-mode)
  :config (add-to-list 'aggressive-indent-protected-commands 'comment-dwim))
```

As I mentionned, this still leaves a slight delay, can you reproduce it?

**Comment by dgutov** [comment]
Try changing `js2-idle-timer-delay`, maybe.

**Comment by angrybacon** [comment]
That's was it thanks. Even with `aggressive-indent-mode` the longer delay is gone, unsure what was causing it in the first place.
