### ISSUE TITLE
Syntax error for "computed keys" in object literal

### ISSUE THREAD

**Issue by harto** [mooz/js2-mode#484]
I noticed that ES6 "computed keys" don't appear to be parsed correctly:
<img width="612" alt="screen shot 2018-02-22 at 1 46 05 pm" src="https://user-images.githubusercontent.com/103448/36565953-f2b4c826-17d6-11e8-80e9-6ba844b6fa4e.png">

**Comment by dgutov** [comment]
What version do you have installed?

**Comment by harto** [comment]
Wait, that's what it says in `js2-mode.el`, but according to `package-list-packages` it's actually `20170804.335`.

**Comment by harto** [comment]
I apologise. It seems this is a problem with `flow-js2-mode`. I didn't realise I had that enabled.
