### ISSUE TITLE
js2-external-variable face broken?

### ISSUE THREAD

**Issue by Yikes2000** [mooz/js2-mode#485]
I declared a few global external variables to highlight in code:

```
(setq-default js2-global-externs '("Foo" "ABC"))

(custom-set-faces
 '(js2-external-variable ((t (:underline t :weight bold))))
 ...
)

(custom-set-variables
 '(js2-highlight-external-variables t)
 ...
)
```

It stopped working after I upgraded to the latest js2-mode a couple of months ago.

Thanks,
Andy

**Comment by dgutov** [comment]
How exactly is it not working?

Keep in mind, that face is for undeclared external variables, not for the ones you have in e.g. `js2-global-externs`.

**Comment by Yikes2000** [comment]
Apologies.  My memory must be faulty.  I will attempt to implement js2-global-externs-face when I get a block of free time.

Thanks,
Andy
