### ISSUE TITLE
empty menus

### ISSUE THREAD

**Issue by tsulej** [mooz/js2-mode#499]
I'm getting empty menus after running js2-mode on Emacs 26.1.

Configuration for JS part goes like that:

```
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-to-list 'interpreter-mode-alist '("node" . js2-mode))

(add-hook 'js2-mode-hook 'js2-imenu-extras-mode)

(add-hook 'js2-mode-hook
          (lambda ()
            (local-set-key (kbd "C-x C-e") 'js-send-last-sexp)
            (local-set-key (kbd "C-M-x") 'js-send-last-sexp-and-go)
            (local-set-key (kbd "C-c b") 'js-send-buffer)
            (local-set-key (kbd "C-c C-b") 'js-send-buffer-and-go)
            (local-set-key (kbd "C-c l") 'js-load-file-and-go)))

(require 'js-comint)
```

![image](https://user-images.githubusercontent.com/1256957/41964179-ab508044-79f9-11e8-81ab-c3b9ecc7953c.png)
![image](https://user-images.githubusercontent.com/1256957/41964222-c283a2d2-79f9-11e8-9083-3191309c954f.png)
![image](https://user-images.githubusercontent.com/1256957/41964254-cfb29594-79f9-11e8-98bf-fa988ced0040.png)

Whole emacs.d (without JS part yet) is here:
https://github.com/tsulej/.emacs.d 

any ideas?

**Comment by tsulej** [comment]
The same I have when I run `emacs -Q` and manually add hooks. Menu is empty.

**Comment by dgutov** [comment]
Please report that to Emacs. `M-x report-emacs-bug`.
