### ISSUE TITLE
error in js2-jump-to-definition when using object property:value shorthand

### ISSUE THREAD

**Issue by thorrr** [mooz/js2-mode#502]
The following jump to definition fails with `js2-jump-to-definition: Wrong type argument: arrayp, nil`:

```javascript
function start(n) {
    return n+1;
}

module.exports = {start};
// put cursor here  ^
```

The expected action is to nav to the "f" in `function`.

This is fixed in #501

**Comment by dgutov** [comment]
The fix is merged.
