### ISSUE TITLE
Error: Lisp nesting exceeds ‘max-lisp-eval-depth’

### ISSUE THREAD

**Issue by dcguim** [mooz/js2-mode#503]
I am trying to install js2-mode through elpa in Emacs 25.1 but I get the following error:
In js2-treeify:
**js2-mode.el:7296:19:Error: Lisp nesting exceeds ‘max-lisp-eval-depth’**

I already tryied uninstalling and installing it again as well as byte recompiling as suggested in:
https://github.com/mooz/js2-mode/issues/252

The error seems to be triggered in the following part of the code:
```lisp
(defsubst js2-treeify (lst)
  "Convert (a b c d) to (a ((b ((c d)))))"
  (if (null (cddr lst))  ; list length <= 2
       lst
       (list (car lst) (list (js2-treeify (cdr lst))))))
```
I found a bit funny the way it checked if **lst** had length <= 2
Shouldn\`t  this do the trick?
```lisp
(defsubst js2-treeify (lst)
  "Convert (a b c d) to (a ((b ((c d)))))"
  (if (< (list-length lst) 3) 
       lst
       (list (car lst) (list (js2-treeify (cdr lst))))))
```
This suggestion won\`t work if the **lst** was created as `(list 1 2 3)` but only `'(1 2 3)`
It works if I simply install by https://code.google.com/archive/p/js2-mode/
But apparently I need to install through elpa to satisfy the 6th requirement of https://github.com/swank-js/swank-js

**Comment by dgutov** [comment]
> Shouldn`t this do the trick?

It will obviously be slower if the list is long.

**Comment by dcguim** [comment]
Yes, it would be O(n) instead of constant complexity. 
I was just trying to play a little bit with the code that apparently is causing the problem.

**Comment by dcguim** [comment]
I was indeed working with the latest version of js2-mode. 
But I was able to compile without errors by upgrading my Emacs from 25 to 26 and SBCL to 1.4.9.
