### ISSUE TITLE
Emacs hangs when I type two subsequent colons

### ISSUE THREAD

**Issue by paulmedynski** [mooz/js2-mode#504]
I'm a C++ developer working in JS for a bit, and my muscle memory often types things like:

`MyClass::SomeEnun::Value`

instead of:

`MyClass.SomeEnum.Value`

This causes Emacs to lock up, and I have to kill it, edit the recovery file to remove the colons, and then recover my work.

I don't have any logs or diagnostics.  I can collect them if someone walks me through it.

**Comment by DoMiNeLa10** [comment]
Just out of curiosity, have you tried typing `C-g` a couple of times when this happens? I assume it's a problem with `js2-mode`, so it shouldn't be causing problems so severe Emacs can't recover out of them.

**Comment by paulmedynski** [comment]
You're correct that hitting `C-g` (4 times) will bring Emacs back to life.  When it is hung, it eats 100% CPU.  strace doesn't show any tight loop of system calls.

**Comment by dgutov** [comment]
Does this still happen?

**Comment by dgutov** [comment]
Does this still happen?

**Comment by ArneBab** [comment]
I cannot reproduce it.

**Comment by dgutov** [comment]
Let's call this fixed, without any recent reports to the contrary.
