### ISSUE TITLE
Spacemacs: 'master' branch 0.200.13: Emacs freezes when switching themes with 'helm-themes' while editing under 'js2-mode'

### ISSUE THREAD

**Issue by dennismayr** [mooz/js2-mode#508]
Emacs freezes when switching themes via helm-themes typing `M-m T s` and choosing any theme.
It's not possible to `C-g` out of it, can't check any backtrace since there was no information to recover in the first place after toggle-debug-on-quit.

I did some debugging that included:
- Removing `.emacs.d` and `.spacemacs`, and reinstalling Spacemacs from scratch
- Re-adding my personalized options to `.spacemacs` one line at a time, saving, restarting, opening files, switching themes.

I found out that **only** while editing a particular javascript/nodejs file, [server.js](https://github.com/dennismayr/codeburst_WeatherApp/blob/develop/server.js), Emacs freezes while switching themes with `M-m T n` or selecting any other with `M-m T s`.

Having 20+ other files did not freeze Emacs; formats vary from *Markdown* and plain text, to *java*, *javascript*, *php* and *html* files.

Edit:
While having this [server.js](https://github.com/dennismayr/codeburst_WeatherApp/blob/develop/server.js) file open, I switched to any other mode, like `web-mode`, then switched themes with `M-m T s` or `M-m T n`, and Emacs didn't freeze. Switched modes back to `js2-mode`, switched themes, and Emacs froze.

Perhaps there's a conflict between `js2-mode` and some *javascript* / *nodejs* syntax.

**Comment by dennismayr** [comment]
I just tried setting *Js2 Dynamic Idle Timer Adjust* to `0.3` (`'(js2-dynamic-idle-timer-adjust 0.3)` in the dotfile), and the problem disappeared.

Why did this happen? It's beyond me.

**Comment by dgutov** [comment]
> Re-adding my personalized options to .spacemacs

Can you reproduce that without Spacemacs? Also, I don't see your Emacs version mentioned.

**Comment by dennismayr** [comment]
Oh boy, I missed that!

I'm running Emacs 26.1.

I'll try it on plain Emacs on a virtual machine during the weekend, from versions 24 to 26.

**Comment by dennismayr** [comment]
`js2-mode` hasn't given me problems under plain Emacs, so I'll report the bug to the Spacemacs maintainers; there are other issues in Spacemacs that impair the `js2-mode` experience (autocompletion and syntax highlighting).

The problem doesn't seem to be popping up anymore, so I'm closing the issue.
