### ISSUE TITLE
js2-imenu-extras-mode bad hook

### ISSUE THREAD

**Issue by vxcamiloxv** [mooz/js2-mode#511]
[js2-imenu-extras-setup](https://github.com/mooz/js2-mode/blob/master/js2-imenu-extras.el#L118) append a wrong hook `t` as a function and the results in error on imenu, looks like related to https://github.com/mooz/js2-mode/issues/499

- The error: 
```lisp
run-hooks: Symbol’s function definition is void: t
```
- The `js2-build-imenu-callbacks` content
```lisp
(t js2-imenu-record-declarations js2-imenu-walk-ast)
```

- The temporal solution:
```lisp
(setq js2-build-imenu-callbacks '(js2-imenu-record-declarations js2-imenu-walk-ast))
```
### Enviroment info
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, Version 3.22.30) of 2018-07-05

**Comment by dgutov** [comment]
> (t js2-imenu-record-declarations js2-imenu-walk-ast)

It's normal to have a `t` inside the local value of a hook variable.

Where does your error come from?

**Comment by vxcamiloxv** [comment]
The error is when I call `imenu`, but the error is in `(setq js 2-build-imenu-callbacks t)`, with nil the error disappear

**Comment by dgutov** [comment]
Yup.
