### ISSUE TITLE
Emacs freezes on pressing enter or ; at the end of given example

### ISSUE THREAD

**Issue by typedefstructer** [mooz/js2-mode#513]
```
let b = {
  a : `
  //1
  `
}
```
GNU Emacs 26.1

Steps to reproduce, 

1. copy the given example into emacs *scratch*
2. set to js2-mode
3. try pressing enter or ; after the closing curly braces.

Then emacs freezes

**Comment by DoMiNeLa10** [comment]
While it does hang, simply pressing `C-g` aborts properly and lets you resume  your work.

**Comment by typedefstructer** [comment]
yeah C-g, still its annoying, But sometimes C-g doesn't work. Its sort of random, any idea how to debug this?
Installed VS Code because of this bug.

**Comment by dgutov** [comment]
Curiously, it's not about parsing but about indentation, which is currently handled by `js-mode`.

As a workaround, you can disable `electric-indent-mode`. Trying to automatically indent the line with `;` (e.g. with TAB) will still lead to an infloop, though.

**Comment by dgutov** [comment]
Here's the fix in master: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b01a4295c2f9bb58858880e4e28b05cc8396791c

It will go in Emacs 27. Not sure about the upcoming point release, though.

**Comment by typedefstructer** [comment]
awesome. Thanks.

**Comment by dgutov** [comment]
And now it will be in 26.2 as well.

**Comment by typedefstructer** [comment]
closing the issue...
