### ISSUE TITLE
unused variable or function

### ISSUE THREAD

**Issue by knobo** [mooz/js2-mode#515]
3 problems here.

1. only `var0` is not used, but there is not warning for that.
2. `Variable ’var1’ referenced but never initialized` But it fact it is destructed
3. `Unused variable or function ’var2’` even tough it is used 2 times.

![js2-warning](https://user-images.githubusercontent.com/89921/53808416-725bd580-3f52-11e9-996a-359bd632dd32.png)

**Comment by lelit** [comment]
I see, thank you for the report: will try to fix the issue as soon as time permits.

**Comment by knobo** [comment]
And on line 82, var4 should have a warning about not beeing initialized.

**Comment by lelit** [comment]
@dgutov, about `var4`: trying out the code in NodeJS, it errors out with `ReferenceError: var4 is not defined`, but that's not catched by `js2-highlight-undeclared-vars()`. Is that a bug by its own?

NodeJS raises a ReferenceError for both `x` and `z` in the following code (executing the functions, I mean):

```js
function foo(a) {
    const x = {a, x};
}

function bar() {
    const y = z;
    const z = 1;
}
```
Should `js2-highlight-undeclared-vars()` consider the position of the declaration?

**Comment by DoMiNeLa10** [comment]
@lelit considering that declaring a `const` without an initial value throws an error, it should be marked as an error.

**Comment by dgutov** [comment]
@lelit. I think so. Unless there's evidence that NodeJS behaves against the spec, which is unlikely.

**Comment by lelit** [comment]
The above changes seems to cure one half of the reported problem.

I wasn't so lucky trying to solve the other half, the undefined reference in the `const` assignment. First I checked with both Firefox and Chrome, and they raise an error executing the simple functions above. Then I tried to tweak `js2-get-defining-scope` to handle also `js2-CONST` assignment, something like:
```patch
diff --git a/js2-mode.el b/js2-mode.el
index 567d629..0c2e881 100644
--- a/js2-mode.el
+++ b/js2-mode.el
@@ -2314,7 +2314,7 @@ Returns nil if there is no enclosing scope node."
 Returns `js2-scope' in which NAME is defined, or nil if not found.
 
 If POINT is non-nil, and if the found declaration type is
-`js2-LET', also check that the declaration node is before POINT."
+`js2-LET' or `js2-CONST', also check that the declaration node is before POINT."
   (let ((sym (if (symbolp name)
                  name
                (intern name)))
@@ -2325,7 +2325,7 @@ If POINT is non-nil, and if the found declaration type is
            (let ((entry (cdr (assq sym (js2-scope-symbol-table scope)))))
              (and entry
                   (or (not point)
-                      (not (eq js2-LET (js2-symbol-decl-type entry)))
+                      (not (memq (js2-symbol-decl-type entry) (list js2-LET js2-CONST)))
                       (>= point
                           (js2-node-abs-pos (js2-symbol-ast-node entry))))))
            (and (eq sym 'arguments)
```

but that has not the expected outcome... Will try harder, but maybe you can point me in the right direction :-)

**Comment by lelit** [comment]
Please let me know if you prefer splitting that into a separate issue, opening a PR with these changes alone, or if instead it would be better to wait for a fix to the `const` thingie.

**Comment by knobo** [comment]
I'll open a seperate issue for the missing var4 warning/error.

**Comment by lelit** [comment]
If you can test my branch and tell if it effectively cures your case, it would be great!

**Comment by knobo** [comment]
Yes, I have tested it a bit now. And it looks like it works.
But how do I override elpa dependencies to load your git version instead of elpa version?

**Comment by lelit** [comment]
Sorry, can't help there. But usually Dmitry is very responsive in releasing bug-fixes :-)

**Comment by knobo** [comment]
I consider myself done testing now :)

**Comment by lelit** [comment]
Thanks a lot!

**Comment by knobo** [comment]
Thank you for fixing the bugs :)

**Comment by dgutov** [comment]
Merged, thanks for the report.
