### ISSUE TITLE
Variable 'ClassName' referenced but never initialized

### ISSUE THREAD

**Issue by knobo** [mooz/js2-mode#518]
Variable ’SomeComponent’ referenced but never initialized

``` js
import React from 'react';
import PropTypes from 'prop-types';

class SomeComponent extends React.Component {

  render() {
    return <div></div>;
  }  
}

SomeComponent.propTypes = {
  
};

export default SomeComponent;
```

**Comment by knobo** [comment]
I think this warning should be removed.

![somecomponent](https://user-images.githubusercontent.com/89921/53958152-90efd700-40e0-11e9-82fa-d6f3eee12e76.png)

**Comment by dgutov** [comment]
/Cc @lelit :man_shrugging:

Not sure if this was originally in scope, but please take care of this, if you could.

**Comment by dgutov** [comment]
Fixed, thanks!

**Comment by knobo** [comment]
Thanks
