### ISSUE TITLE
[low priority] Autocompletion using 'tern' doesn't autocomplete 'console.log'

### ISSUE THREAD

**Issue by dennismayr** [mooz/js2-mode#521]
Spacemacs user here, very low priority issue.

I'm using `tern` as backend for `js2-mode`, and it works great for everything **except** for autocompleting `console.log`.

Whenever I type `cons`, instead of completing `console.log`, it offers:

* `const`
* `continue`

Anything but `console`. It guesses _anything else_ correctly.
I know it's a pretty stupid issue, I'm just having to type `console` a lot lately.

My dotfile includes the following `js2-mode` custom configurations:
```
'(js2-highlight-level 3)
'(js2-include-node-externs t)
'(js2-strict-missing-semi-warning nil)
```

Is there a catch in the mode configuration? :)
Not sure is a `js2-mode` issue or a Spacemacs layer thing.

OS: elementaryOS Juno / Ubuntu 18.04
Emacs: 26.1
`js2-mode-20190307.1649`

**Comment by dgutov** [comment]
This is a question for `tern`, not `js2-mode`. And you're probably using `tern` as a backend for `company`.
