### ISSUE TITLE
freezes when hook with eglot

### ISSUE THREAD

**Issue by nree** [mooz/js2-mode#522]
Seeing `Open /Users/...............jsx [2 times]` in messages buffer whenever I have auto hook and using  26.2-rc1 compiled from src https://github.com/railwaycat/homebrew-emacsmacport

Only happens for GUI, doesn't seem to happen for cli (on cli emacs, I never see Open ... [2 times] even though same emacs setup).

Noticed it with hook & eglot.

- Having no hook = normal.
- Having fake function to hook (no-op) , opens twice but no noticeable issues as user.
- Having rjsx-mode or company-mode hook it, opens twice but no noticeable issues as user.
- Having eglot hook = opens twice & emac freezes for 15-20 seconds.

Doesn't matter if .js or .jsx. Doesn't appear to happen on 26.1-2 pre-compiled binary via https://emacsformacosx.com .

I _think_ it has to do with the file being opened twice, but again the __freeze interaction only happens with eglot__

My emacs setup is pretty barebones, here's a relevant snippet:
```elisp
(require 'use-package)

(use-package js2-mode :ensure t)
;; react support, .jsx
;;(use-package rjsx-mode :ensure t)

(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
;;(add-hook 'js2-mode-hook 'company-mode)
(add-hook 'js2-mode-hook 'eglot-ensure)
```

**Comment by nree** [comment]
Just tested with rust-mode and hook with eglot is OK, still see Open ... [2 times]
At this point I don't know how relevant that is anymore since every other situation it doesn't matter. It could be an issue with the emacs port, or emacs version I'm using. 

_But it doesn't affect anything else_ except eglot & js2-mode and the real issue is the 15-20 second freeze.

**Comment by dgutov** [comment]
Do you see the same double invocation with other major modes?

I couldn't reproduce, with the current master, or the version that's going to become Emacs 26.2 (so it's very close to 26.1 you have). Could be a `use-pckage` problem, I guess.

Here's the example I've tested:

```emacs
(defvar counter 0)

(defun foo ()
  (setq counter (1+ counter))
  (message "called %i" counter))

(add-hook 'js2-mode-hook 'foo)
```

And I only see the courter incresed by 1 for each opened file.

**Comment by nree** [comment]
Thanks for testing... 
The 2 times messages appear for _any file_ not just javascript, earlier I thought it only happened to JS files. But doesn't affect other files though.
For example I mentioned rust-mode + eglot is fine even though I see [2 times] for it too.

Tried a few more things, went completely barebones:
```elisp
;; init.el
(require 'package)
(setq package-archives '(("org"   . "http://orgmode.org/elpa/")
                         ("gnu"   . "http://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(package-install 'js2-mode)
(package-install 'eglot)

(require 'js2-mode)
(require 'eglot)

(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-hook 'js2-mode-hook 'eglot-ensure)
```
## Emac builds
- https://emacsformacosx.com/ | is fine.
#### https://github.com/railwaycat/homebrew-emacsmacport
- emacs-26.2-rc1-mac-7.5  (compiled from src) | freezes
- emacs-26.1-mac-7.2 (used the pre-compiled binary) | freezes

emacs-26.1-mac-7.2 being a build I never tested previously. So it's the port I believe... not emacs version.


##### *Messages* 
```
‘js2-mode’ is already installed
‘eglot’ is already installed
Saving file /Users/h/.emacs.d/init.el...
Wrote /Users/h/.emacs.d/init.el [2 times]
For information about GNU Emacs and the GNU system, type C-h C-a. [2 times]
[eglot] Connected! Server `EGLOT (******/js2-mode)' now managing `js2-mode' buffers in project `*******'.
```
Doesn't show I opened a .js file, sometimes it does, sometimes it doesn't I'm not sure why.

I'm not sure where to raise the issue because it's a combination of the railwaycat port + js2-mode hook + eglot that freezes emacs. 

Btw, manually doing `eglot` works fine.

railwaycat's port is pretty popular for Mac users, so I wonder if someone else can try to reproduce?

**Comment by dgutov** [comment]
So... emacsformacosx works fine? No double-loading problem? Or just no freeze?

> railwaycat's port is pretty popular for Mac users, so I wonder if someone else can try to reproduce?

In the previous message I gave some example code everybody can try.

I don't own a Mac myself (nor do I intend to), so it's not something I could actually help fix.

**Comment by nree** [comment]
> So... emacsformacosx works fine? No double-loading problem? Or just no freeze?

Definitely no freeze, but can't remember about the double loading, I want to say no there too.


> In the previous message I gave some example code everybody can try.
```
Open /Users/h/xxxxxx.js [2 times]
called 1
[eglot] Connected! Server `EGLOT (xxxxxxx/js2-mode)' now managing `js2-mode' buffers in project `xxxxxxx'.
```
The thing is I'm not sure if the double loading is related to the freeze anymore, since everything else gets double loaded too (.rs, .el) and they don't freeze. And also I have company & rjsx-mode hook into js2-mode and they don't freeze either.

I've now tried out lsp-mode over eglot. No freeze there either...

I'm going to close and re-open back on eglot project. I think that's the only piece that seems like it has issue.

**Comment by dgutov** [comment]
> called 1

I'm not seeing my hook function called twice, though.
