### ISSUE TITLE
Performance of js2-parse

### ISSUE THREAD

**Issue by wol81** [mooz/js2-mode#524]
My question is: What is your impression about the performance of (js2-parse)?

I implemented code analysis on top of js2-mode, in order to achieve better support for completion, navigation, and such in the context of our projects (quite a bit specialized, based on our way to use Dojo in our projects).

For some js file with about 2000 lines of code (I can't simply publish it as it's proprietary code), I experienced bad performance of js2-parse.  I then compared:
- running time around 0.4s with the js2-mode version of 16th January 2017
- running time around 1s with the current js2-mode version

(the js2-mode.el was byte-compiled in both cases, both with the emacs version (24.5.1) I currently use)

So, parsing time for that file increased significantly over the last two years.

As I haven't really time to dive into that parsing code myself, I have the following questions:
1. Do you have an explanation for that?  Are there known changes, that were necessary for the sake of correctness, but caused a known performance penality?
2. What is your opinion about the overall performance of js2-parse?  Could it become faster with some amount of work, or is your impression that it's as fast as it can be based on Lisp?

For me, this means that for now I will stay with the 2017 version, as already 0.4s is quite much in terms of user experience.

**Comment by DoMiNeLa10** [comment]
What about a newer version of Emacs? There might be some backwards compatibility code that isn't as fast as how it's implemented in newer versions of Emacs, as well as improvements to the byte code compiler.

**Comment by dgutov** [comment]
Have you tried it in Emacs 25? It will require a recompilation to see the speed-up.

Or, in Emacs 24.4 or newer, you can `(setq byte-compile--use-old-handlers)` in your init script, and then reinstall the package to trigger the recompilation.

Of the recent changes, the one that is likely to have caused such a slowdown is the transition to `lexical binding: t`. But the new condition-case handling introduced in Emacs 24.4 (and made default in 25.1) should recover most of the difference, if not all.

**Comment by wol81** [comment]
You are right, on emacs 26.2, the current js2-mode version is just slightly slower than the 2017 js2-mode version (something like a 0.4s vs. 0.45s difference). 

Thanks for that hint, and the reason why I use that old emacs version is simple: Debian Stable.

**Comment by dgutov** [comment]
:man_shrugging: You can try the other solution I suggested, then.

**Comment by dgutov** [comment]
BTW, https://repology.org/project/emacs/versions says Debian Stable includes 25.1 already.

**Comment by wol81** [comment]
Ah, thank you again, I didn't notice (or forgot) that the emacs versions are arranged in separate packages, i.e. I had to install the package emacs25 instead of just updating...
