### ISSUE TITLE
Cannot defer loading using `use-package`

### ISSUE THREAD

**Issue by TLATER** [mooz/js2-mode#525]
Hi, I'm trying to bring down my emacs startup time a bit, and I'm hitting a bit of a road block on js2-mode.

When using `use-package` like this to load js2-mode:

```lisp
(use-package js2-mode
  :mode "\\.js\\'"
  :init
  (setq js2-basic-offset 4)
  (setq-default js2-additional-externs
                '("$" "define" "require")))
```

I'd expect it to set the variables during startup, and then load and
enable js2-mode when I open a javascript file (I should probably hook
this to js-mode instead, but that is somewhat irrelevant).

When loading is deferred like this, however, I run into this error:

```
Debugger entered--Lisp error: (void-function c-populate-syntax-table)
  <unreadable byte code>
  (defvar js2-mode-syntax-table (byte-code "\300 \301\001!\210\302\303\304\003#\210\211\207" [make-syntax-table c-populate-syntax-table modify-syntax-entry 96 "\""] 5) ("/home/tlater/.emacs.d/elpa/js2-mode-20190307.1649/js2-mode.elc" . 58268))
  autoload-do-load((autoload "js2-mode" "Major mode for editing JavaScript code.\n\n(fn)" t nil) js2-mode)
  command-execute(js2-mode record)
  helm-M-x(nil #("js2-mode" 0 8 (match-part "js2-mode")))
  funcall-interactively(helm-M-x nil #("js2-mode" 0 8 (match-part "js2-mode")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

Inspecting the source a bit further I get to this declaration:

```lisp
(defvar js2-mode-syntax-table
  (let ((table (make-syntax-table)))
    (c-populate-syntax-table table)
    (modify-syntax-entry ?` "\"" table)
    table)
  "Syntax table used in `js2-mode' buffers.")
```

Now, clearly, for some reason emacs objects to the use of the
`c-populate-syntax-table` function here post-init. I don't know much
about writing major modes, or about how `use-package` handles deferred
loading, but there's something fishy here.

Any idea what might cause this or how I might circumvent the issue?

**Comment by dgutov** [comment]
This should hopefully be fixed in `js-mode` now (upstream), I seem to recall some similar problem.
