### ISSUE TITLE
indent arrow function using concise body syntax

### ISSUE THREAD

**Issue by knobo** [mooz/js2-mode#526]
js2-mode does this:
``` js
const something = () =>
      a_verry_long_function_name_that_I_would_like_to_have_on_a_new_line();

const foo = {
  bar: (arg) =>
  something(arg)
};
```
I'd like the arrow functions to be indented like this:
``` js
const something = () =>
  a_verry_long_function_name_that_I_would_like_to_have_on_a_new_line();

const foo = {
  bar: (arg) =>
    something(arg)
};
```

**Comment by knobo** [comment]
With curly braces is ok, without looks strange.

``` js
const foo = () => {
  const this_is_right = "yes";
};

const bar = (not_right) =>
      not_right;

```

**Comment by knobo** [comment]
This bug is related to this js-mode bug, reported 8 years ago.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=9151

**Comment by dgutov** [comment]
FWIW, I just closed that bug report because the example contains invalid syntax now (it was valid in Mozilla's JS in the past).

You can file a new report, but it's fairly difficult to implement, so unless you want to write a patch yourself, it might similarly languish for a while.

**Comment by knobo** [comment]
I don't understand all the advanced emacs lisp stuff, so I'll just go with a qick and dirty fix that I'll try out for a while.

``` lisp

(defun my-arrow-indent ()
  (save-excursion
    (beginning-of-line)
    (if (looking-back "=>\n")
	(let ((indents (save-excursion
			 (previous-line)
			 (beginning-of-line)
			 (looking-at "^\\s-*")
			 (match-string  0)
			 )))
	  (replace-regexp "^\\s-*" (concat indents "  ") nil (save-excursion (beginning-of-line) (point)) (save-excursion (end-of-line) (point)))) )))

(advice-add   'rjsx-indent-line :after  'my-arrow-indent)

```

**Comment by knobo** [comment]
I'll add to the regexp that there is no { at the beginning of the line either.
