### ISSUE TITLE
Next.js CSS

### ISSUE THREAD

**Issue by justinmoon** [mooz/js2-mode#540]
I'm trying a server-side React framework called [next.js](https://nextjs.org/).

Below is how it does styling. 

If I try to make a new line within the CSS with JS2-mode active, my cursor gets stuck on the left-most column of the editor and I can't tab over. The only way I can indent is to smash the space bar a bunch.

```
const PostLink = ({ post }) => (
  <li>
    <Link href="/p/[id]" as={`/p/${post.id}`}>
      <a>{post.title}</a>
    </Link>
    <style jsx>{`
      li {
        list-style: none;
        margin: 5px 0;
      }

      a {
        text-decoration: none;
        color: blue;
        font-family: 'Arial';
      }

      a:hover {
        opacity: 0.6;
      }
    `}</style>
  </li>
);
```

BTW I'm an emacs noob using [Doom](https://github.com/hlissner/doom-emacs). I think this is the right place to leave this bug report / feature request but LMK if I'm wrong!

**Comment by DoMiNeLa10** [comment]
I don't think there's any chance for JS2 to support indentation for nested languages, as it doesn't implement it at all. You might want to take a look at web-mode for your use scenario.

**Comment by dgutov** [comment]
Pretty much. Sorry.
