### ISSUE TITLE
error "Don’t know how to make a localized variable an alias"

### ISSUE THREAD

**Issue by LoganBarnett** [mooz/js2-mode#545]
Disclaimer: I'm on Spacemacs, and I am not familiar with the process of tearing down my monstrous, literate config and still have a usable editor that I could test this with (my fingers know only vim, sadly). Thus I consider this bug report to be incomplete. I have some findings though and this seems as good a way as any to share them.

Sometimes when opening a .js file, I see this error:
```
error "Don’t know how to make a localized variable an alias"
```
When this happens the mode doesn't finish getting setup. Syntax highlighting, indentation, etc don't function. It seems like I can open _some_ .js files, but after some amount of time or after some event occurs this becomes a problem suddenly. A restart fixes the issue temporarily.

A similar error was reported for #458 but it doesn't seem like a fix to either the package nor the user's config had happened. I attempted the changes mentioned but still no joy. If I invoke `toggle-debug-on-error` and produce the issue, and it lands on line [104](https://github.com/mooz/js2-mode/blob/3a80b00b477ca39c1d2bb2edf99191004c8696ca/js2-mode.el#L104), which at time of writing has this:
``` lisp
(defvaralias 'js2-basic-offset 'js-indent-level nil)
```

I am commenting out this line in my local copy of `js2-mode` and I will report back with findings after giving the issue time to manifest again.

For record keeping: A [Spacemacs issue](https://github.com/syl20bnr/spacemacs/issues/9665) was filed by the same reporter as #458 and then closed.

**Comment by dgutov** [comment]
That... is indeed a bug somewhere. But I'm not sure how to fix it in `js2-mode`.

Do you have `js2-basic-offset` customized in your init script?

**Comment by LoganBarnett** [comment]
I do! It's set as part of my configuration of `json-mode`.

I have learned something about aliases today. Thank you!

Even with this knowledge I don't have a reliable way to reproduce this. Still, I have removed my `setq-local` of `js2-basic-offset`. If the issue persists/returns I can reopen this or open a new ticket. Thanks again!

**Comment by aspiers** [comment]
I experienced this just now (why now, what changed?!) and it seems to be fixed by changing my local setting of `js2-basic-offset` to `js-indent-level`.  I guess the former variable is deprecated in favour of the latter now.
