### ISSUE TITLE
Numbers in a string highlighted seperately when highlighting from scratch

### ISSUE THREAD

**Issue by MageJohn** [mooz/js2-mode#565]
Hi there, I noticed some odd behaviour with numbers in strings.

When I write a string with numbers character by character, the numbers in the string are highlighted like the rest of the string. If the string is highlighted again from scratch, however, the numbers are highlighted as number literals. 

I took a recording to illustrate the issue:

![Screen Recording 2020-12-09 at 18 08 11](https://user-images.githubusercontent.com/3520558/101669453-da095380-3a49-11eb-8a19-a909410e3cd1.gif)

Re-highlighting is also triggered when opening the file, of course. It seems to happen with everything treated as a string, including `' '` and `` ` ` `` quoted strings, and RegExp literals.

I'd expect the numbers to be highlighted like the rest of the string, though I guess highlighting numbers separately might make sense too. 

Thanks for taking a look!

**Comment by dgutov** [comment]
Hi!

Where does the number highlighting come from? `js2-mode` does not highlight them any way specially. Whether inside strings or outside.

**Comment by MageJohn** [comment]
I was assuming that js2-mode was marking them as a certain syntactic element, and then my colour scheme was highlighting that element differently. 

I'm happy to look a little deeper, but I'm not sure where to look.

**Comment by dgutov** [comment]
Maybe you can move point to one of these numbers, when they are highlighted, and press `C-u C-x =`.

That will pop up a description buffer which, among other things, mentions the "face" that the number is highlighted with. There are no standard faces for that purpose, so it should point to the originating package.

**Comment by MageJohn** [comment]
Aha, that's done it! Looks like doom-emacs has [highlight-numbers.el](https://github.com/Fanael/highlight-numbers) installed. I'll see if I can configure/disable/raise a bug for it.  

Many thanks for the help figuring this out; I'll close this issue now.

**Comment by MageJohn** [comment]
For future reference, there seems to be an old issue raised in highlight-numbers.el for this issue: https://github.com/Fanael/highlight-numbers/issues/9
