### ISSUE TITLE
js2 as a javascript interpreter

### ISSUE THREAD

**Issue by zcaudate** [mooz/js2-mode#566]
Is it possible to do `eval` with js2?

I'd like to be able to load `react.js` within emacs itself. Is there a way to do this?

**Comment by dgutov** [comment]
There is no built-in interpreter, though someone could write one based on the syntax tree.

But check out https://github.com/emacsattic/ejacs

**Comment by zcaudate** [comment]
@dgutov ejacs is not working for me on emacs27

would you know anything about these rumors (integrating spidermonkey into emacs 28): 
- https://github.com/rocky/elisp-bytecode/blob/master/intro.texi#L252-L275
- https://zenodo.org/record/3736363

**Comment by dgutov** [comment]
> @dgutov ejacs is not working for me on emacs27

Maybe it needs updating. Either way, getting React running on it will likely require a significant experience with Elisp.

> would you know anything about these rumors (integrating spidermonkey into emacs 28):
>    https://github.com/rocky/elisp-bytecode/blob/master/intro.texi#L252-L275
>    https://zenodo.org/record/3736363

Neither of these links is about SpiderMonkey. Andrea Corallo is working on a native compilation which is based on `libgccjit` (part of the GCC project).

**Comment by zcaudate** [comment]
ah. good things take time. thanks for the explaination!
