### ISSUE TITLE
Disable all warnings

### ISSUE THREAD

**Issue by farynaio** [mooz/js2-mode#567]
Is it possible to disable all warnings not only specific ones?

I use js2-mode mostly because of it's faces config. Often times I browse external repos and it's very annoying to see plenty of warnings all around without way to switch them off.

**Comment by dgutov** [comment]
Does `M-x js2-mode-hide-warnings-and-errors` help?

**Comment by farynaio** [comment]
Yes it's perfect, thanks! No idea why I didn't stumble upon that before.
