### ISSUE TITLE
Weird highlighting when using ES6 private variables in class and get/set

### ISSUE THREAD

**Issue by wkechel** [mooz/js2-mode#570]
Emacs underlines private class members in ES6 and some other stuff. How ca I tailor the behaviour?
The attached screenshot shows my occurence of the Emacs buffer.

Code example:
------
class A extends Root
{
  #xx;
  
  constructor()
  {
    super();
    this.#xx = 7;
    this.name = 'hasso';
  }

  get xx()
  {
    return this.#xx;
  }

  set xx(newval)
  {
    this.#xx = newval;
  }

  serialize(ostream) {
    return {
      dynamics: ostream.serialize(this.#xx),
      elems: ostream.serialize(this.#xx)
    };
  }
}

![Screenshot 2021-05-26 at 15 00 23](https://user-images.githubusercontent.com/148173/119663974-28ad7d00-be33-11eb-94c4-48b310a714d1.png)

**Comment by dgutov** [comment]
No "proper" support yet, but there's a workaround here: https://github.com/mooz/js2-mode/issues/537#issuecomment-578446942

**Comment by dgutov** [comment]
@wkechel This should work now.

**Comment by wkechel** [comment]
Is is already available via MELPA or do I need to download the package manually?

**Comment by dgutov** [comment]
MELPA - sure. It builds the latest version automatically.
