### ISSUE TITLE
parse-partial-sexp expects args TO greater than FROM since Emacs 28.1

### ISSUE THREAD

**Issue by jacott** [mooz/js2-mode#571]
Affects `js2-mode-forward-sexp`

from emacs news:

* Incompatible Lisp Changes in Emacs 28.1

---
** 'parse-partial-sexp' now signals an error if TO is smaller than FROM.
Previously this would lead to the function interpreting FROM as TO and
vice versa, which would be confusing when passing in OLDSTATE, which
refers to the old state at FROM.

**Comment by dgutov** [comment]
When called with a negative argument, right?

**Comment by dgutov** [comment]
Fixed the scenario which I could reproduce. If you still see related problems, please post a step-by-step repro.

**Comment by jacott** [comment]
> When called with a negative argument, right?

Yes, like when calling `backward-up-list` 

I can confirm that b913961e410dbfdc52a80d62eb4cfe7a305b4e3e fixes the problem for me
