### ISSUE TITLE
Omitting parentheses and identifiers of CATCH should not raise errors

### ISSUE THREAD

**Issue by rayw000** [mooz/js2-mode#573]
### What happened
```javascript
try {
    // ...
} catch {}
    //  ^ An error raises here saying `missing (  before catch-block condition`
```

### Expected
No errors reported.

### Version
Currently I'm on version `20210830.12` installed from MELPA.

Perhaps we should not strictly expect a catch identifier list here?
https://github.com/mooz/js2-mode/blob/b913961e410dbfdc52a80d62eb4cfe7a305b4e3e/js2-mode.el#L9291-L9292

**Comment by dgutov** [comment]
Thanks for the report, should be fixed now.
