### ISSUE TITLE
Imenu support for mocha-like test files

### ISSUE THREAD

**Issue by DamienCassou** [mooz/js2-mode#575]
I've created [js2-imenu-mocha](https://github.com/DamienCassou/js2-imenu-mocha) which adds `describe()` and `it()` blocks to imenu entries. Would it make sense to include that in `js2-mode`'s repository directly? Maybe as part of `js2-imenu-extras`?

**Comment by dgutov** [comment]
Hi Damien,

Sure, why not? Does it fit the approach used in there?

**Comment by DamienCassou** [comment]
> Does it fit the approach used in there?

@dgutov it doesn't seem like it as `js2-imenu-extras.el` relies on regexps. Do you have any suggestion?

**Comment by DamienCassou** [comment]
Closing this in favor of #576.
