### ISSUE TITLE
private method and private property are not indenting

### ISSUE THREAD

**Issue by hage** [mooz/js2-mode#578]
```javascript
// currently
class Foo {
#private_property = 10;
#private_method() {
  //
}
}

// I hope
class Foo {
  #private_property = 10;
  #private_method() {
    //
  }
}
```

**Comment by dgutov** [comment]
Hi!

As a question about indentation, it would need to be addressed to the Emacs bug tracker for `js-mode`, as mentioned in README.

BUT! This is already https://debbugs.gnu.org/47488

Try installing a snapshot build of Emacs 28, it's fixed there.

**Comment by hage** [comment]
I see, thanks!
