### ISSUE TITLE
How to disable syntax highlight.

### ISSUE THREAD

**Issue by lazyskulptor** [mooz/js2-mode#581]
When I use typescript, I use js2-minor-mode together. In my setting highlight of js2 doesn't work properly.

So I want to disable only syntax highlight function.

I tried to change value of `js2-highlight-level` to 0, but It's still be enabled.

**Comment by dgutov** [comment]
I think you want to set `js2-mode-show-parse-errors` to nil.

**Comment by lazyskulptor** [comment]
Thank you. It works.
