### ISSUE TITLE
Make "Code has no side effects" warning optional

### ISSUE THREAD

**Issue by DamienCassou** [mooz/js2-mode#582]
Some frameworks forces the user to use property access where a function call would be more explicit. For example, [chai](https://www.chaijs.com/api/bdd/#ok) asks the user to write expressions like this:

```js
expect(true).to.be.true;
```

I think this is bad practice but I can't change chai. In such cases, js2-mode correctly warns the user:

> Code has no side effects

In files where chai is used I would prefer not to see such warnings. Would you accept a PR which adds a buffer-local configuration option to deactivate this warning?

**Comment by dgutov** [comment]
Sure, please go ahead.

**Comment by DamienCassou** [comment]
I just found out about `js2-ignored-warnings` which solves the problem for me. So I'm closing the issue.
