### ISSUE TITLE
HTML tag regex inadvertently matches types.

### ISSUE THREAD

**Issue by trev-dev** [mooz/js2-mode#583]
The catch all expression `"\\\(</?\\)\\([[:alpha:]]+\\)\\s-*\\(/?>\\)"` is probably not meaning to match types. The HTML Tag regex match could use some refinement.

I'm not feeling confused by this, but it's inconsistent.

![Screenshot from 2022-03-02 11-33-29](https://user-images.githubusercontent.com/28788713/156436168-a4dbf030-d23d-4099-b375-b42c11b985f6.png)

![Screenshot from 2022-03-02 11-36-26](https://user-images.githubusercontent.com/28788713/156436480-1a216502-4afd-4660-aa29-0f07a574a227.png)

Edit: Easier solution may be to use the same pattern for all nested types so that the HTML tags and all nested types match in face. I do think nested types could benefit from having a distinct highlight.

**Comment by dgutov** [comment]
Not sure that mixing up semantics of html tags and type specializers is a good idea (obviously, this feature never anticipated the latter), but try running with this patch. As long as it doesn't create other false positives, maybe the effect is good enough:

```diff
diff --git a/js2-mode.el b/js2-mode.el
index 38cc28d..3772d7e 100644
--- a/js2-mode.el
+++ b/js2-mode.el
@@ -7017,7 +7017,7 @@ of a simple name.  Called before EXPR has a parent node."
   "Matches a jsdoc @see tag.")
 
 (defconst js2-jsdoc-html-tag-regexp
-  "\\(</?\\)\\([[:alpha:]]+\\)\\s-*\\(/?>\\)"
+  "\\(</?\\)\\([][:alpha:][]+\\)\\s-*\\(/?>\\)"
   "Matches a simple (no attributes) html start- or end-tag.")
 
 (defun js2-jsdoc-highlight-helper ()
```

**Comment by trev-dev** [comment]
Stale
