### ISSUE TITLE
No code highlighting without menu-bar?

### ISSUE THREAD

**Issue by bbo2adwuff** [mooz/js2-mode#586]
I don't see any code highlighting when starting emacs without a menu-bar.

### No code highlighting with my init file `menu-bar-off`:
```elisp
(package-initialize)
(menu-bar-mode -1)
(require 'js2-mode)
```

### Code highlighting works with my init file `menu-bar-not-off`:
```elisp
(package-initialize)
(require 'js2-mode)
```

I'm using following emacs version:
`GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-28`

**Comment by UwUnyaa** [comment]
Can you try with a minimal init file? I disable `menu-bar` as well, and never had that issue myself.

**Comment by bbo2adwuff** [comment]
Oh sorry, what I meant above was that these are my init files. Hence these are minimal init files.

`emacs -q -l menu-bar-off` and `emacs -q -l menu-bar-not-off`

**Comment by bbo2adwuff** [comment]
### Screenshot with init file `menu-bar-off`
![Screenshot from 2022-04-28 18-34-26](https://user-images.githubusercontent.com/34131023/165801392-b0db8b23-7e6a-4e5d-98d9-fac55738f4b7.png)

### Screenshot with init file `menu-bar-not-off`
![Screenshot from 2022-04-28 18-35-07](https://user-images.githubusercontent.com/34131023/165801404-0273bc67-1fae-441e-b337-19edd76ab350.png)

**Comment by UwUnyaa** [comment]
How have you installed `js2-mode`?

**Comment by bbo2adwuff** [comment]
I installed it via melpa, but I as I upgraded to `28.1` I realized that it's related to #72.

So as in https://github.com/mooz/js2-mode/issues/72#issuecomment-15176816, this did the trick:
`(byte-recompile-directory (expand-file-name "~/.emacs.d/elpa/js2-mode-20220402.2211/") 0 t)`

**Comment by bbo2adwuff** [comment]
Just for completeness, it seems that the `menu-bar-mode -1` already played a role in another issue https://github.com/mooz/js2-mode/issues/572.
