### ISSUE TITLE
Escaped expressions containing a real expression in a template literal inside a a lambda inside a class method break the parser

### ISSUE THREAD

**Issue by ArneBab** [mooz/js2-mode#592]
When using a [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to create a string that contains an expression (`${something}`) the parser reports an error:

```js
class Bar {
  foo () {
    [1, 2, 3].forEach((a) => {
      const valid = `\${${a}}`;
      const variable = '123'; // this is highlighted in red as broken
      // in valid, the second '{' and 'a' and the second '}' and the second '`' are also highlighted in red as broken
    });
  }
}
```
I put the second comment after valid, because when adding that comment on the line of valid, the error does not spill into the line with variable anymore.

**Comment by dgutov** [comment]
Thanks for the report, should be fine now.

**Comment by ArneBab** [comment]
Awesome — thank you!
