### ISSUE TITLE
Static blocks not recognised as valid code

### ISSUE THREAD

**Issue by cyrus-and** [mooz/js2-mode#594]
Consider the following legitimate JavaScript code:

```js
class Foo {
    static {
        // ...
    }
}
```

With `js2-mode`, the second and the third curly braces are marked as errors, complaining that, respectively:

> invalid property id

> syntax error

Works seemingly fine with `js-mode`.

I'm using the latest version from MELPA: `20230408.115`

**Comment by cyrus-and** [comment]
Awesome, thank you!

**Comment by dgutov** [comment]
Thanks for the report!
