### ISSUE TITLE
Does js2-mode become obsolete in Emacs 27.1? Or that the latest stable is not available via ELPA / MELPA?

### ISSUE THREAD

**Issue by thjwong** [mooz/js2-mode#595]
Upon startup, there is an error message:

> `Error loading autoloads: (file-missing Cannot open load file No such file or directory /home/myusername/.emacs.d/elpa/js2-mode-20230509.2244/js2-mode-autoloads)
`

And in M-x list-packages, js2-mode was listed as "obsolete"
> `  js2-mode           20230408.115  obsolete              Improved JavaScript editing mode`

my dot emacs is set to point to all ELPA and MELPA archives:
> ` (add-to-list 'package-archives (cons "gnu"  (concat proto "://elpa.gnu.org/packages/")) t)`
> ` (add-to-list 'package-archives (cons "nongnu" (concat proto "://elpa.nongnu.org/nongnu/")) t)`
> ` (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)`

**Comment by dgutov** [comment]
The first error means you have some problem with the installation (missing autoloads file). It might help to remove and then reinstall.

And the "obsolete" text hints that there is a newer version available. You should be able to see it in the list as well.
