### ISSUE TITLE
Treat shebang lines like a comment

### ISSUE THREAD

**Issue by skeeto** [mooz/js2-mode#84]
This is a feature request. Both Node.js and PhantomJS support shebang lines but js2-mode (reasonably) tries to parse them like normal JavaScript code. It would be nice if a `#!` at the beginning of a script was treated like a single-line `//` comment.

**Comment by masaeedu** [comment]
@katspaugh Looks like that link wasn't anchored to a commit, so right now it just points at a random line in the file. Anyone know what the actual config is to ignore shebangs?

**Comment by skeeto** [comment]
The variable is js2-skip-preprocessor-directives.

https://github.com/mooz/js2-mode/blob/cd4a73fa21cfc6764a21cad41647a93954d940a4/js2-mode.el#L387

**Comment by jonroby** [comment]
(setq js2-skip-preprocessor-directives t)

**Comment by masaeedu** [comment]
Thanks folks.
