### ISSUE TITLE
syntax highlighting dosen't work with emacs 24.3

### ISSUE THREAD

**Issue by jaclar** [mooz/js2-mode#91]
I just upgraded to emacs 24.3 and now the syntax highlighter wont update upon change in the file.
To get the correct highlighting I have to trigger js2-mode-reset.
I double checked and js2-idle-timer-delay is set to 0.

**Comment by dennismayr** [comment]
This still happens in 2018/2019; deleted, downloaded, recompiled.
No settings were altered.

Syntax highlighting still requires saving and reverting to saved.
Emacs 26.1, spacemacs 0.200.13 (stable).
